base/web

- apps/web/src/data/ecosystem.json
Adding a series of new partners to the base ecosystem page
> EcoPage - New Partners - Json Updates

- apps/base-docs/docs/tools/node-providers.md
- apps/base-docs/docs/tools/oracles.md
Added the following node providers and oracles:
- Alchemy
- NOWNodes
- DIA
N/A
Manually
> Add Alchemy, NOWNodes, and DIA

- apps/web/src/data/ecosystem.json
Added json code for Alchemy and Fonbnk
There is a corresponding PR for logos. 
> EcoPage - 2 new partners - json

- apps/bridge/.eslintrc.js
- apps/bridge/pages/_app.tsx
- apps/bridge/src/components/TOSModal/TOSModal.tsx
- apps/bridge/src/contexts/OFACContext.tsx
- apps/bridge/src/contexts/TOSContext.tsx
- apps/web/.eslintrc.js
Make sure we're automatically catching things like https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-no-target-blank.md
> Make linting a bit stricter with eslint-react recommended

- apps/bridge/.eslintrc.js
- apps/bridge/src/components/Transactions/DepositRow/DepositRow.tsx
- apps/web/.eslintrc.js
As described by title.
Manually
> Remove Mint NFT button from Deposit Row now that onchainsummer has ended

- apps/base-docs/docs/tools/onramps.md
> Change on-ramps to onramps

- apps/base-docs/docs/tools/node-providers.md
Added Stackup as a node provider
> Add Stackup to Node Providers page

- apps/base-docs/docs/tools/oracles.md
Remove coming soon for Supra VRF mainnet
NA
NA
> Supra VRF mainnet is live

- apps/web/src/components/Layout/Nav/Nav.tsx
> [trivial] remove base.org banner

- apps/web/src/data/ecosystem.json
Did a data cleanse of BD CRM and discovered a set of projects that were featured on the ecosystem page but are not deployed on Base yet. Need to remove these projects. 
Also adding a few new partners.
> EcoPage - JSON - Additions and Removals

- apps/base-docs/docs/building-with-base/base-contracts.md
- apps/base-docs/docs/building-with-base/network-information.md
- apps/base-docs/docs/tokens.md
- apps/base-docs/docs/using-base.md
Added the new sepolia testnet network to the docs site.
> Add sepolia network information to docs

- apps/base-docs/docs/tools/node-providers.md
Update the description for NOWNodes on the Node Provider page.
Requested by the NOWNodes DevRel team.
Manually.
> Update NOWNodes description

- apps/web/src/data/ecosystem.json
Removed one partner that is not currently deployed
Adding multiple new partners
> EcoPage - New partner additions- json

- apps/base-docs/base-camp/docs/etherscan/etherscan-sbs.md
- apps/base-docs/base-camp/docs/hardhat-deploy/hardhat-deploy-sbs.md
- apps/base-docs/base-camp/docs/hardhat-forking/hardhat-forking.md
- apps/base-docs/base-camp/docs/hardhat-setup-overview/hardhat-setup-overview-sbs.md
- apps/base-docs/base-camp/docs/hardhat-testing/hardhat-testing-sbs.md
- apps/base-docs/base-camp/docs/hardhat-verify/hardhat-verify-sbs.md
* All of the docs within https://docs.base.org/base-camp/docs/hardhat-setup-overview/hardhat-setup-overview-sbs have been QAed.
* All videos were checked.
* Fixed formatting in a few places as well.
> Qa and edit hardhat docs

- apps/base-docs/docs/tools/thirdweb-sdk.md
> EMV -> EVM

- apps/bridge/src/utils/transactions/isETHOrERC20Deposit.ts
- apps/bridge/src/utils/transactions/isETHOrERCWithdrawal.ts
check that cctp is enabled on chain before including the txs on transactions page
> [trivial] add cctp enabled check to tx list

- apps/base-docs/base-camp/docs/hardhat-contract-to-contract/hardhat-contract-to-contract.md
- apps/base-docs/base-camp/docs/hardhat-profiling-gas/hardhat-profiling-gas.md
- apps/base-docs/base-camp/docs/hardhat-profiling-size/hardhat-profiling-size.md
This PR includes three new files, which were edited and moved from Edson's fork.
> Add more Hardhat docs to Base Camp

- apps/base-docs/docs/tools/network-faucets.md
Adds the [LearnWeb3 Faucet](https://learnweb3.io/faucets/base_goerli) to the list of network faucets
> Add LearnWeb3 faucet to list

- apps/bridge/src/components/DepositContainer/DepositContainer.tsx
- apps/bridge/src/components/WithdrawContainer/WithdrawContainer.tsx
- apps/bridge/src/utils/hooks/usePrepareERC20Deposit.ts
- apps/bridge/src/utils/hooks/usePrepareERC20DepositTo.ts
- apps/bridge/src/utils/hooks/usePrepareInitiateCCTPBridge.ts
- use wagmi actions to approve --> bridge in one function
> use wagmi actions for erc20 approval --> bridge

- apps/base-docs/docs/tools/oracles.md
Updated the wording and links for API3
N/A
Manually
> Update API3 documentation

- apps/base-docs/docs/tools/oracles.md
> Fix broken link syntax in oracles.md

- apps/base-docs/docs/tools/bridge-faq.md
- apps/bridge/src/components/Faq/FaqSidebar.tsx
Adding additional FAQs regarding the Bridge that we've observed in Base Discord.
Localhost
> docs(bridge): Add additional FAQs

- apps/base-docs/docs/tools/data-indexers.md
Adding [Flair](https://flair.dev)  as a data indexing solution on Base
yes
> feat: add flair indexing

- apps/bridge/src/components/Layout/Layout.tsx
- apps/bridge/src/components/OFACModal/OFACModal.tsx
Modification to withdrawal processing for native bridge to allow successfully initiated withdrawals to complete.
> Withdrawal processing completion

- apps/bridge/src/utils/transactions/explorerTxToBridgeDeposit.ts
- apps/bridge/src/utils/transactions/explorerTxToBridgeWithdrawal.ts
- apps/bridge/src/utils/transactions/isETHOrERC20Deposit.ts
- apps/bridge/src/utils/transactions/isETHOrERCWithdrawal.ts
fixes issue where tx page tries to display arbitrary (ui-unsupported) erc20s
> fix unknown asset issue

- apps/web/src/data/ecosystem.json
Fixed assets/text on a few
Added additional partners into the ecosystem page
> EcoPage - new partners json update

- apps/base-docs/base-camp/docs/hardhat-profiling-gas/improving-gas-usage-vid.md
- apps/base-docs/base-camp/docs/hardhat-profiling-gas/installing-the-gas-analyzer-vid.md
- apps/base-docs/base-camp/docs/hardhat-profiling-size/contract-sizer-setup-vid.md
- apps/base-docs/base-camp/docs/hardhat-profiling-size/hardhat-profiling-size.md
- apps/base-docs/base-camp/docs/hardhat-profiling-size/manual-contract-optimizations-vid.md
- apps/base-docs/base-camp/docs/hardhat-profiling-size/using-the-optimizer-vid.md
- apps/base-docs/base-camp/docs/interfaces/calling-another-contract-vid.md
- apps/base-docs/base-camp/docs/interfaces/contract-to-contract-interaction.md
- apps/base-docs/base-camp/docs/interfaces/intro-to-interfaces-vid.md
- apps/base-docs/base-camp/docs/interfaces/testing-the-interface-vid.md
Added Video files and minor reorg for hardhat part 2.
Content is not yet released, so not in sidebar.  It's fine if sleuths see it early.
> Add hardhat part 2 vids

- apps/bridge/chains.ts
- apps/bridge/next.config.js
> switch eth rpc

- apps/bridge/.env.goerli.example
- apps/bridge/.env.mainnet.example
- apps/bridge/.env.sepolia.example
- apps/bridge/global.d.ts
- apps/bridge/next.config.js
- apps/bridge/package.json
- apps/bridge/src/components/Transactions/WithdrawalRow/FinalizeWithdrawalButton.tsx
- apps/bridge/src/components/Transactions/WithdrawalRow/OPWithdrawalRow.tsx
- apps/bridge/src/components/Transactions/WithdrawalRow/ProveWithdrawalButton.tsx
- apps/bridge/src/contexts/OFACContext.tsx
- apps/bridge/src/data/useDeposits.ts
- apps/bridge/src/data/useWithdrawals.ts
- apps/bridge/src/utils/hooks/usePrepareFinalizeWithdrawal.ts
- apps/bridge/src/utils/hooks/usePrepareProveWithdrawal.ts
- apps/bridge/src/utils/hooks/useWithdrawalStatus.ts
- apps/bridge/src/utils/transactions/explorerTxToBridgeDeposit.ts
- apps/bridge/src/utils/transactions/explorerTxToBridgeWithdrawal.ts
- apps/bridge/src/utils/transactions/getWithdrawalMessage.ts
- apps/bridge/src/utils/transactions/indexerTxToBridgeDeposit.ts
- apps/bridge/src/utils/transactions/indexerTxToBridgeWithdrawal.ts
- apps/bridge/src/utils/transactions/isETHOrERC20Deposit.ts
- apps/bridge/src/utils/transactions/isETHOrERCWithdrawal.ts
- yarn.lock
fetch op deposits / withdrawals from our deployment of the op indexer
> use op indexer for op deposits & withdrawals

- apps/base-docs/docs/tools/cross-chain.md
Old: https://github.com/gmimnoah/happy-birthday-base-wormhole
New: https://github.com/wormhole-foundation/wormhole-examples
> Update cross-chain.md - Fix broken link for wormhole example

- apps/web/src/data/ecosystem.json
Edited two partners and added new partner json to the ecosystem page
> EcoPage - New Partner Additions

- apps/bridge/src/data/useDeposits.ts
- apps/bridge/src/data/useWithdrawals.ts
> add start block to explorer query

- apps/web/src/data/ecosystem.json
I was mis-referencing the partner logo folder in the json which was causing logos to not render for 5 partners. 
> EcoPage - Image reference json edit

- .github/ISSUE_TEMPLATE/docs_request.yml
Added an issue template to collect docs-related requests and issue reports
> Add docs issue template

- apps/bridge/assets.ts
> apps/bridge/assets: Add allowlist note

- apps/base-docs/docs/tools/onramps.md
Add MoonPay to onramp documentation
N/A
Manually
> Add MoonPay onramp

- apps/base-docs/docs/tools/network-faucets.md
Add the Superchain Faucet to the developer documentation.
N/A
Manually
> Add Superchain Faucet

- apps/base-docs/docs/connecting-to-the-blockchain/connecting-to-the-blockchain.md
Added an article on Providers and using them to connect to the blockchain.
Article is not in sidebar.  It can be merged without publishing, it's ok of someone sleuths it out.
> Brian doyle/add connecting to chain mod

- apps/web/src/data/ecosystem.json
Adding new partners to the ecosystem page. 
There is an associated logo PR that should be pushed live first!
> EcoPAge - Update ecosystem.json

- apps/web/src/data/ecosystem.json
Removing baseswap from the ecopage
> EcoPage - Remove BaseSwap

- apps/bridge/src/utils/hooks/usePrepareETHDeposit.ts
> remove deposit gas limit

- apps/base-docs/base-camp/docs/erc-721-token/erc-721-exercise.md
Exercise for ERC721 instructions were missing one of the errors.
> Add missing error to erc721 ex spec

- apps/web/src/data/ecosystem.json
Added 5 new partners
Edited one category tag
> EcoPage - new partners json

- apps/base-docs/static/google0add911fc673d45f.html
Add file for Google Search Console verification.
Adding file to verify our ownership of the sub domain in order to enable Google Search Console for developer documentation SEO purposes
Manually
> Add Google Search Console verification

- apps/base-docs/docs/connecting-to-the-blockchain/connecting-with-a-provider.md
Removed Optimism from connection example to simplify
> Remove Optimism from example

- apps/base-docs/base-camp/docs/arrays/arrays-exercise.md
- apps/base-docs/base-camp/docs/control-structures/control-structures-exercise.md
- apps/base-docs/base-camp/docs/deployment-to-testnet/deployment-to-testnet-exercise.md
- apps/base-docs/base-camp/docs/erc-20-token/erc-20-exercise.md
- apps/base-docs/base-camp/docs/erc-721-token/erc-721-exercise.md
- apps/base-docs/base-camp/docs/error-triage/error-triage-exercise.md
- apps/base-docs/base-camp/docs/imports/imports-exercise.md
- apps/base-docs/base-camp/docs/inheritance/inheritance-exercise.md
- apps/base-docs/base-camp/docs/mappings/mappings-exercise.md
- apps/base-docs/base-camp/docs/minimal-tokens/minimal-tokens-exercise.md
- apps/base-docs/base-camp/docs/new-keyword/new-keyword-exercise.md
- apps/base-docs/base-camp/docs/storage/storage-exercise.md
- apps/base-docs/base-camp/docs/structs/structs-exercise.md
- apps/base-docs/docs/building-with-base/differences.md
Remove Shanghai warning from Basecamp exercises, update note in Differences article.
> Remove/Update Shanghai warmings

- apps/base-docs/base-camp/sidebars.js
Step by step had wrong document linked.
> Fix link to step by step

- apps/base-docs/base-camp/docs/structs/structs-exercise.md
Small edit to section headers in base camp struct exercise docs to clarify what is being asked
> clarify headers in structs-exercise.md

- apps/base-docs/docs/tools/onboarding.md
- apps/base-docs/sidebars.js
Adding user onboarding platforms and tooling.
N/A
Manually
> Add user onboarding tools

- apps/base-docs/base-camp/docs/error-triage/error-triage-exercise-source.sol
- apps/base-docs/base-camp/docs/error-triage/error-triage-exercise.md
Update comment in Error Triage Exercise based off of Issue [#168](https://github.com/base-org/web/issues/168)
> Update the comment in error-triage

- apps/web/src/data/ecosystem.json
Edited 2 URLs
Added 8 new partners
Seperate PR with 8 new images, merge that one before this one please.
> EcoPage - json additions and edits

- apps/web/src/components/Layout/Footer/Footer.tsx
Adding a new google form for inbound to the footer
> Add Inbound Form to Footer

- apps/base-docs/base-camp/docs/hardhat-verify/hardhat-verify-sbs.md
- apps/base-docs/base-camp/docs/inheritance/inheritance-exercise.md
- apps/base-docs/docs/hardhat-tools-and-testing/hardhat-profiling-gas/hardhat-profiling-gas.md
- apps/base-docs/docs/overview.md
This pull request addresses several grammar and typographical issues in the documentation. It ensures that the text is clear and correct.
- Corrected the word 'identity' to 'identify' for clarity and correctness.
- Corrected the phrase 'an more complicated' to 'a more complicated' for proper grammar.
- Fixed the word 'creeate' to 'create' for accuracy.
- Added a missing 'K' in the word 'Keywords' for consistency.
I want to express my sincere appreciation for the dedication and hard work in maintaining this opensource project. The attention to detail and commitment to quality are truly commendable.
> Grammar and Typographical Fixes in Documentation

- apps/base-docs/base-camp/docs/frontend-setup/overview.md
- apps/base-docs/base-camp/docs/writing-to-contracts/useContractWrite.md
- apps/base-docs/base-camp/sidebars.js
Added an overview document for frontend course
> Add overview for frontend

- apps/base-docs/base-camp/docs/frontend-setup/overview.md
> Fix typos in FE overview

- apps/base-docs/base-camp/docs/frontend-setup/overview.md
- apps/base-docs/base-camp/docs/writing-to-contracts/usePrepareContractWrite.md
> More typos

- apps/web/src/data/ecosystem.json
11 new partners added to the page, 1 delisted
There is a seperate logo PR pending that should be merged first
> EcoPage - Updated Json 12/18

- apps/base-docs/docs/tools/account-abstraction.md
- apps/base-docs/sidebars.js
Add section for Account Abstraction tooling
N/A
Manually
> Add Account Abstraction tooling

- apps/base-docs/docs/building-with-base-and-foundry/introduction.md
- apps/base-docs/docs/building-with-base-and-foundry/testing.md
Included introduction and testing with Foundry guides
> Introduction and testing with Foundry guides

- apps/base-docs/docs/tools/hardhat.md
Fixing Comma Issue in config
There was comma issue in config for hardhat
Test the Config file its missing Comma.
It has been tested by me on local setup.
> Fix comma issue in hardhat.md

- apps/web/src/components/Layout/Footer/Footer.tsx
Footer: Update copyright year to always be current year
N/A
Localhost
> Footer: Update copyright year to always be current year

- apps/web/src/data/ecosystem.json
Adding json for partners, logo PR submitted seperately and should be merged prior to this one!
> EcoPage - Json additions

- apps/web/pages/ecosystem.tsx
- apps/web/src/components/Layout/Footer/Footer.tsx
Requested changes from BD team.
Locally.
> Remove apply button on eco page, add text to footer

- apps/base-docs/docs/building-with-base/guides/building-with-base-and-foundry/introduction.md
- apps/base-docs/docs/building-with-base/guides/deploy-smart-contracts.mdx
- apps/base-docs/docs/building-with-base/guides/deploy-with-foundry.md
- apps/base-docs/docs/building-with-base/guides/deploy-with-remix.md
- apps/base-docs/docs/connecting-to-the-blockchain/blockchain-providers.md
- apps/base-docs/docs/connecting-to-the-blockchain/connecting-with-a-provider.md
- apps/base-docs/docs/tokens.md
- apps/base-docs/docs/tools/ethers.md
- apps/base-docs/docs/tools/foundry.md
- apps/base-docs/docs/tools/hardhat.md
- apps/base-docs/docs/tools/viem.md
- apps/base-docs/docs/tools/web3.md
This PR updates guides and docs to use Base Sepolia in preparation for the deprecation and sunset of Base Goerli.
(One of multiple PRs) - These specific changes can be published ahead of the sunset date.
N/A
Manually
> Update guides and docs with Sepolia

- apps/base-docs/docs/tools/cross-chain.md
Add Chainlink CCIP to Cross-chain section
N/A
Manually
> Add Chainlink CCIP to Cross-chain section

- apps/base-docs/docs/building-with-base/guides/cross-chain-with-ccip.md
> Fix typo in docs

- apps/base-docs/docs/tools/block-explorers.md
- apps/base-docs/docs/tools/data-indexers.md
- apps/base-docs/docs/tools/network-faucets.md
- apps/base-docs/docs/tools/node-providers.md
- apps/base-docs/docs/tools/oracles.md
Updated various docs to reflect the latest state of Sepolia migrations in the Base ecosystem
N/A
Manually
> Update docs with latest updates on Sepolia migrations

- apps/bridge/pages/_app.tsx
- apps/web/src/components/Layout/Nav/Nav.tsx
> add goerli deprecation notice

- apps/base-docs/docs/tools/data-indexers.md
> Add support for Base Sepolia

- apps/web/src/data/ecosystem.json
Adding json for 12 new partners
> EcoPage- Json Edits

- apps/bridge/pages/deposit.tsx
> goerli deposit eol

- apps/base-docs/docs/tokens.md
Update broken link to standard bridge
N/A
Manually
> Fix standard bridge link

- apps/base-docs/base-camp/docs/address-and-payable/address-and-payable.md
- apps/base-docs/base-camp/sidebars.js
Added article on address and payable
**How has it been tested?** 
manually
No
- [+ ] No, this PR does not add a new token to the bridge
- [+] I've confirmed this token doesn't use a bridge override
- [- ] I've confirmed this token is an OptimismMintableERC20
> Address payable

- apps/bridge/src/components/DepositContainer/DepositContainer.tsx
- apps/bridge/src/components/WithdrawContainer/WithdrawContainer.tsx
Logic accidentally excluded "equals" ie max.
> Fix withdraw/deposit max

- apps/base-docs/docs/tools/node-providers.md
Add coinbase cloud to node providers
n/a
deployed locally
> Add coinbase cloud to node providers

- apps/web/src/components/JoinTheCommunity/JoinTheCommunity.tsx
> Remove Euler from join community

- apps/web/src/data/ecosystem.json
Small json edits and updated image reference for Arpa
Removed duplicate cymbal entry & edited the cymbal entry we are keeping. 
- [X ] No, this PR does not add a new token to the bridge
> Ecopage - minor json edits

- apps/base-docs/base-camp/docs/development-tools/overview.md
**What changed? Why?** updated typo
**Notes to reviewers** added before and after screen shots
> typo correct devtool overview

- apps/base-docs/docs/building-with-base/guides/complex-onchain-nfts.md
- apps/base-docs/sidebars.js
Rename and publish guide to make complex nfts
> Rename and publish svg nft guide

- apps/base-docs/docs/building-with-base/guides/using-pyth-price-feeds.md
- apps/base-docs/docs/contracts.md
- apps/base-docs/docs/tools/bridges-testnet.md
- apps/base-docs/docs/tools/node-providers.md
Remove more references to Base Goerli throughout the docs, including currently non-migrated tools.
N/A
Manually
> Additional docs clean up for Base Goerli sunset

- apps/base-docs/docs/building-with-base/guides/account-abstraction-with-biconomy.md
- apps/base-docs/sidebars.js
Add a guide on implementing account abstraction into a Base project using Biconomy.
N/A
Manually
> Add Account Abstraction (Biconomy) guide

- apps/web/pages/ecosystem.tsx
BD team asked to have this added back.
Manually.
> Add back Apply form link to ecosystem page

- apps/web/src/components/Bootcamp/Dates.tsx
- [ x] No, this PR does not add a new token to the bridge
> Update bootcamp page

- apps/bridge/pages/_app.tsx
- apps/web/src/components/Layout/Nav/Nav.tsx
Remove Goerli deprecation notices as it has been deprecated.
> Remove Goerli Deprecation Notice

- apps/web/src/components/Bootcamp/Dates.tsx
Pushing back Cohort start date to allow more time for recruiting
> Push back bootcamp dates

- apps/web/pages/cookie-policy.tsx
- apps/web/pages/third-party-cookies.tsx
- apps/web/src/components/Layout/Layout.tsx
Added page where third party cookies will be listed.
Ran app locally to test link to page and responsive styles on page.
> Add Third-Party Cookie Page

- apps/base-docs/base-camp/docs/exercise-contracts.md
- apps/base-docs/base-camp/sidebars.js
Learners often ask for the unit tests for Base Camp Exercises.  PR provides them in a list, with links directly to the code on Sepolia Basescan
> Add list of contracts for exercises

- apps/base-docs/docs/building-with-base/guides/frame-transactions.md
- apps/base-docs/sidebars.js
> Add frame transaction tutorial

- apps/web/src/data/ecosystem.json
Added json and added one edit to existing json to feature new partners on the ecopage
Please merge the 2 image PRs before this one
- [ x] No, this PR does not add a new token to the bridge
> EcoPage - Json updates for new partners

- apps/base-docs/docs/building-with-base/guides/frame-transactions.md
Added debugging and frame flow tips.
its docs
- [x ] No, this PR does not add a new token to the bridge
> chore(frame transactions docs): add note about tx simulation & tx monitoring

- apps/base-docs/docs/building-with-base/guides/run-a-base-node.md
Update CPU and HDD in hardware requirements when running a Base Node
N/A
Localhost
> docs(Base Node): Update CPU and HDD in hardware requirements

- apps/web/src/data/ecosystem.json
Update json to properly add the new logos for rubyscore / lore
merge this AFTER the logo PR
- [ x] No, this PR does not add a new token to the bridge
> EcoPage [merge second] - 2 json edits

- apps/base-docs/docs/building-with-base/guides/hyperframes.md
Updated hyperframes tutorial to use the state property and teach it's use
> Update hyperframes to use state

- apps/base-docs/docs/tools/data-indexers.md
Added Moralis to the data indexers page in docs.
> Added Moralis to data indexers

- apps/bridge/pages/_app.tsx
Updates the notice to the new, rescheduled date
Localhost
> docs(bridge): Update bridge pause to new date

- apps/bridge/pages/_app.tsx
Drops bridge maintenance notice
N/A
Localhost
> refactor(bridge): Drop bridge maintenance notice

- apps/base-docs/docs/tools/node-providers.md
Add Base Sepolia support for Chainstack
N/A
Manually
> Add Base Sepolia support for Chainstack

- apps/base-docs/docs/tools/block-explorers.md
Add OKLink to block explorers
N/A
Manually
> Add OKLink to block explorers

- apps/base-docs/docs/tokens/token-list.md
- apps/base-docs/docs/tokens/wallet.md
- apps/base-docs/sidebars.js
- apps/base-docs/src/pages/tutorials/index.jsx
- apps/base-docs/tutorials/data.json
Update tokens section
N/A
Manually
> Update tokens section

- apps/base-docs/docs/tools/node-providers.md
Added OnFinality and SubQuery as node providers
> Added SubQuery and OnFinality

- .github/PULL_REQUEST_TEMPLATE.md
For newcomers to the repo, the question about adding a token to the bridge is confusing and only seems to apply to a small percentage of PRs.
It would be helpful to remove friction in contributions if the PR template made it a little clearer to contributors what the question is asking.
None
N/A
> Clarify bridge question on PR template

- apps/web/middleware.ts
Add redirects to middleware.js
N/A
Manually
> Add redirects to middleware

- apps/base-docs/src/theme/DocItem/Content/index.js
By request - disable DocChat AI widget.
This PR disables the DocChat widget until we re-train or tweak the model to give higher quality and more consistent answers to users.
Manually
> Disable DocChat widget

- apps/base-docs/base-camp/docs/new-keyword/new-keyword-exercise.md
Clarified instructions for new keyword exercise.  
> Clarify exercise for new keyword

- apps/base-docs/tutorials/docs/2_account-abstraction-with-privy-and-base-paymaster.md
- apps/base-docs/tutorials/docs/4_hardhat-debugging.md
- apps/base-docs/tutorials/docs/4_hardhat-profiling-gas.md
- apps/base-docs/tutorials/docs/4_hardhat-profiling-size.md
- apps/base-docs/tutorials/docs/4_hardhat-test-coverage.md
- apps/base-docs/tutorials/docs/4_intro-to-foundry-setup.md
- apps/base-docs/tutorials/docs/4_intro-to-foundry-testing.md
A few articles/videos were attributed to me that either I didn't write, or didn't do alone.
> Fix articles misattributed to me

- apps/base-docs/scripts/updateTutorials.js
- apps/base-docs/src/theme/DocItem/Content/index.js
- apps/base-docs/src/theme/DocItem/Content/styles.module.css
- apps/base-docs/tutorials/data.json
- apps/base-docs/tutorials/docs/0_deploy-with-foundry.md
- apps/base-docs/tutorials/docs/0_deploy-with-hardhat.mdx
- apps/base-docs/tutorials/docs/0_deploy-with-remix.md
- apps/base-docs/tutorials/docs/0_deploy-with-tenderly.md
- apps/base-docs/tutorials/docs/0_deploy-with-thirdweb.md
- apps/base-docs/tutorials/docs/1_build-with-thirdweb.md
- apps/base-docs/tutorials/docs/2_account-abstraction-with-biconomy.md
- apps/base-docs/tutorials/docs/2_account-abstraction-with-privy-and-base-paymaster.md
- apps/base-docs/tutorials/docs/2_cross-chain-with-ccip.md
- apps/base-docs/tutorials/docs/2_cross-chain-with-layerzero.md
- apps/base-docs/tutorials/docs/2_oracles-chainlink-price-feeds.md
- apps/base-docs/tutorials/docs/2_oracles-pyth-price-feeds.md
- apps/base-docs/tutorials/docs/2_oracles-supra-vrf.md
- apps/base-docs/tutorials/docs/4_intro-to-providers.md
- Added author, last updated timestamp, and duration info to top of tutorial content pages
- Fixed styling of display info
- Updated all tutorials to use synthetic headers determined from title front matter
**Screenshots**
N/A
Manually
> Add info to tutorial content

- apps/base-docs/src/pages/tutorials/index.jsx
- apps/base-docs/static/json/authors.json
- apps/base-docs/tutorials/data.json
- apps/base-docs/tutorials/docs/2_account-abstraction-with-particle-network.md
- Updated latest tutorial with proper tagging
- Updated tutorial filtering to fail gracefully if tutorial is not tagged properly
N/A
Manually
> Fix tutorial and broken filtering

- apps/base-docs/docs/contracts.md
Adds Uniswap V2 contracts for mainnet and testnet
N/A
Localhost
> docs(Contracts): Add Uniswap V2

- apps/base-docs/base-camp/docs/erc-20-token/erc-20-exercise.md
Updating "Votes" to "Vote", cause it may cause some confusion for the person working on the exercise and lead to function signatures issue
Just a general copy fix
It's a copy fix
**No**
> Updating ERC 20 exercise doc

- apps/base-docs/docs/tokens/token-list.md
- Updated sidebar title for token list doc to better reflect page content
N/A
Manually
> Update sidebar title for token list doc

- apps/base-docs/base-camp/docs/imports/imports-exercise.md
Clarified instructions in imports exercise.  Resolves issue #449 
> Clarify instructions in imports exercise

- apps/base-docs/src/components/StudentProgress/index.jsx
Updated Base Camp student progress page to use wagmi v2.
N/A
Manually
> Fix Base Camp student progress page

- apps/base-docs/base-camp/docs/erc-20-token/erc-20-exercise.md
- apps/base-docs/base-camp/docs/imports/imports-exercise.md
Clarified the instructions in a couple of exercises
> Add clarification to the exercises

- apps/base-docs/tutorials/docs/0_run-a-base-node.md
Add instructions to help people who want to restore from snapshot
N/A
Localhost
> docs(node): Add instrux for restoring from snapshot

- apps/base-docs/docusaurus.config.js
- apps/base-docs/src/components/FooterCategory/index.tsx
- apps/base-docs/src/components/FooterCategory/styles.module.css
- apps/base-docs/src/components/ImageCard/index.tsx
- apps/base-docs/src/components/PageSection/index.tsx
- apps/base-docs/src/theme/Navbar/Content/index.js
Implemented fixes for accessibility issues described by @stevenmalenz in #438 
Only made changes that didn't visually alter the website. I.E no content or design changes. Low contrast issues remain.
No
Built, run, and previewed in the local environment. Reviewed across multiple browsers on desktop and mobile resolutions.
No
> Add digital accessibility improvements to Base Docs

- apps/base-docs/base-camp/docs/mappings/mappings-exercise.md
Clarify instructions on mapping ex
> Clarify instructions on mapping ex

- apps/web/next.config.js
> allow cca in CSP

- apps/base-docs/base-camp/docs/minimal-tokens/minimal-tokens-exercise.md
Fixed a missed change in minimal tokens exercise
> Change Goerli to Sepolia

- apps/base-docs/server.js
- apps/base-docs/tutorials/docs/2_account-abstraction-with-particle-network.md
This PR is to add a missing redirect link reported by developers, and update other stale / old links within the docs.
N/A
Manually
> Add redirects for AA guide

- apps/base-docs/docs/building-with-base/network-information.md
> docs(network-information): update the path link to docs

- apps/bridge/pages/_app.tsx
- apps/bridge/src/components/DeprecationModal/DeprecationModal.tsx
- apps/bridge/src/components/Faq/FaqSidebar.tsx
Updates Superbridge's URL to the correct one:
s/superbridge.com/sueprbridge.app/
N/A
Localhost
> docs(bridge): Fix Superbridge URL

- apps/base-docs/docs/tools/nft-minting.md
Apologies for another commit onto an patch that was already merged. I noticed that there was a formatting issue at the bottom due to a missing space. I just fixed it. 
Please merge this as well. Thanks once again
Same as above
Tested preview
> doc fix: Update nft-minting.md to fix formatting

- apps/base-docs/scripts/updateTutorials.js
Updated the tutorial data generation script to properly update the `lastModified` data field for each tutorial.
N/A
Manually
> Fix tutorial update script to reflect accurate `lastModified` data.

- apps/base-docs/tutorials/docs/2_signature-mint.md
Add tutorial for signature mint
> Add tutorial for signature mint

- apps/base-docs/docs/tools/node-providers.md
- apps/base-docs/tutorials/docs/4_intro-to-providers.md
Updated the naming from Coinbase Cloud to CDP
Added CDP in "intro to providers" page
> Updated naming from Coinbase Cloud to CDP

- apps/bridge/pages/_app.tsx
- apps/bridge/src/components/Faq/FaqSidebar.tsx
Updates the switchover date from the 17th to the 21st.
N/A
Localhost
> docs(bridge) Update Superchain Bridge date to May 21st

- apps/web/src/components/Layout/Nav/OcsBanner.tsx
> Hide OCS Banner correctly when on builder summer

- apps/base-docs/docs/tools/hardhat.md
A comma is missing in the sample code.
No, this is a Markdown document.
> Fix Typo in hardhat.md

- apps/bridge/src/components/DeprecationContent/BridgeCards.tsx
> Fix team name

- apps/base-docs/scripts/updateTutorials.js
- apps/base-docs/tutorials/data.json
- This PR updates the script for generating data associated with tutorials.
- This will prevent `data.json` from being overwritten unless there are changes to content within a tutorial markdown file.
- Publish / last updated dates have also been accurately updated, as they have been erroneously updated in the past due to a script bug.
N/A
Manually.
> Fix for tutorial data script

- apps/bridge/src/components/DeprecationContent/BridgeCards.tsx
- apps/bridge/src/components/DeprecationContent/DeprecationContent.tsx
- apps/bridge/src/components/Faq/FaqSidebar.tsx
- apps/bridge/src/components/Faq/QuestionAccordion.tsx
- apps/bridge/src/components/Nav/Nav.tsx
- apps/bridge/tailwind.config.js
Just makes the bridge deprecation page look better.
Manually in QA with designer
> Design pass with Shelly

- apps/base-docs/tutorials/docs/0_run-a-base-node.md
Update requirements for full and archive nodes
N/A
Localhost
> docs(base node): HDD requirements

- apps/web/next.config.js
- apps/web/pages/jobs.tsx
- apps/web/src/components/Jobs/JobsList.tsx
Since we're changing the roles quite often recruiting asked us to make this dynamic.
Manually.
> Always dynamically load jobs page, no SSR

- apps/web/src/data/ecosystem.json
Recategorize Zora from NFT to Social per request from Zora team
N/A
Localhost
> maintenance(ecosystem): Update Zora

- apps/web/src/components/Button/Button.tsx
- apps/web/src/components/ConnectWalletButton/ConnectWalletButton.tsx
- apps/web/tailwind.config.js
See what effect a minimal bounce on the connect wallet button does for conversions.
Manually.
> Add bounce motion effect to connect button

- apps/web/package.json
- yarn.lock
> Update Sprig sdk to 2.29.0

- apps/base-docs/docs/tools/node-providers.md
Add RockX to node providers
N/A
Manually
> Add RockX to node providers

- apps/web/next.config.js
> Add redirect for base.org/registry to the OCS registry form

- apps/web/src/components/OnchainSummer/RewardsBlock.tsx
> Change gas credits link

- apps/web/src/components/OnchainSummer/Hero.tsx
Updated the Share Your Ideas link on [Onchain Summer](base.org/onchainsummer)'s hero section.
Manually, locally.
> updated Share Your Ideas link

- apps/bridge/src/components/Nav/DesktopNav.tsx
- apps/web/src/components/Layout/Nav/DesktopNav.tsx
More directly surfaced our learning resources by adding a link at the top-level nav bar.
+1'd by Gardo
Manually
> Add Learn link to Nav

- yarn.lock
> chore: run yarn dlx update-browserslist-db@latest

- apps/base-docs/package.json
- apps/base-docs/src/components/Icon/index.tsx
- apps/base-docs/src/components/OnchainSummer/OcsBanner.tsx
- apps/base-docs/src/components/OnchainSummer/styles.module.css
- apps/base-docs/src/theme/Navbar/index.js
- yarn.lock
Added the same OnchainSummer banner that we have on base.org to docs.base.org.
Designs and banner behavior matches that of the banner on base.org.
> Feat: OcsBanner added to docs.base.org

- apps/web/next.config.js
> Add redirect link to registry edit

- apps/base-docs/src/components/OnchainSummer/OcsBanner.tsx
Changed the link attribution on the OnchainSummer banner on docs.base.org.
locally, manually.
> Updated link attribution

- apps/base-docs/Dockerfile
> Revert "Updated Dockerfile in Base-Docs to build at runtime"

- apps/base-docs/docs/tools/onramps.md
To apply and add an on-ramp introduction with Alchemy Pay
> To apply and add an onramp introduction with Alchemy Pay

- apps/base-docs/Dockerfile
> Revert "Update Base-Docs Dockerfile to build at runtime"

- apps/base-docs/src/pages/tutorials/index.jsx
Fixed three errors with the tutorials page: 2x react key errors, and 1x nested anchor tags.
> Fixed key errors on tutorials page

- apps/base-docs/docs/tools/data-indexers.md
Add Nexandria to data indexers list
Nexandria platform has supported Base for a few quarters now
Our portal which supports Base: https://beta.nexandria.com/
Our API suite, which has been used by Base developers: https://docs.nexandria.com/
> Update data-indexers.md (Add Nexandria)

- apps/web/next.config.js
- apps/web/package.json
- apps/web/pages/_app.tsx
- package.json
- yarn.lock
Updating this package so @Keshavrajsinghal can work on adding smart wallet/paymaster features
> chore: update rainbowkit to support smart wallet

- apps/base-docs/docs/tools/registry-api.md
Added Registry API docs page
Tested locally
> Add registry api page

- apps/web/pages/api/registry/entries.ts
- apps/web/pages/api/registry/featured.ts
OCS data doesn't change frequently so we can set a pretty long cache time on these.
> Set OCS registry caching headers

- apps/base-docs/src/components/OnchainSummer/OcsBanner.tsx
- apps/web/src/components/Layout/Nav/OcsBanner.tsx
Updated the OCS Banner text.
locally.
> Updated text on OCS Banners

- apps/base-docs/package.json
- apps/base-docs/src/theme/Root.jsx
- apps/web/package.json
- yarn.lock
* Updated RainbowKit to version 2.1.3 in both base-web and base-docs.
locally.
> Updated rainbowkit version on base-docs and base-web.

- apps/base-docs/src/components/OnchainSummer/styles.module.css
- apps/web/src/components/Layout/Nav/OcsBanner.tsx
Underline CTA link in OCS banner.
Manually.
> Make banner CTA a bit more visible

- apps/base-docs/src/theme/NavbarItem/ComponentTypes.js
- apps/web/src/components/ConnectWalletButton/ConnectWalletButton.tsx
- libs/base-ui/utils/logEvent.ts
* changed wallet type event property from camel to snake case. This follows Amplitude convention.
* locally
> Fix: change wallet type property from camel to snake case

- apps/web/pages/api/registry/entries.ts
- apps/web/src/utils/ocsRegistry.ts
Return updated_at data for ocs registry
tested locally
> Return updated_at data for ocs registry

- apps/base-docs/docs/building-with-base/base-contracts.md
Will add challenger address in separate PR once we finalize it.
> Add addresses for Fault Proof contracts on Sepolia L1

- apps/base-docs/tutorials/docs/0_gassless-transactions-with-paymaster.md
> update tag to AA

- apps/base-docs/docs/tools/registry-api.md
- apps/base-docs/sidebars.js
I updated the Registry API content to reflect the most recent data structure changes and added the Registry API link to the sidebar now that we are no longer in beta.
I tested these changes by running the docs site locally.
> Registry updates

- apps/web/src/data/ecosystem.json
Fixes an erroneously supplied project name in 0xPPL's ecosystem submission
N/A
Localhost
> fix(ecosystem): Update project name for 0xPPL

- apps/base-docs/base-learn/docs/frontend-setup/building-an-onchain-app.md
Fix typo in Building an Onchain App
> Fix typo in Building an Onchain App

- apps/web/pages/api/registry/entries.ts
- apps/web/pages/api/registry/featured.ts
- apps/web/src/utils/ocsRegistry.ts
add request stats capturing on registry. This will let us analyze OCS Registry traffic.
tested locally
> add request stats capturing on registry

- apps/base-docs/server.js
> Fix: Added Amplitude urls to base-docs csp

- apps/base-docs/docs/tools/node-providers.md
Include Validation Cloud to document
Validation Cloud now supports Base Mainnet. We are adding in our website with this PR.
> Add Validation Cloud to node-providers.md

- apps/base-docs/tutorials/docs/0_gasless-transactions-with-paymaster.md
> lowercase AA

- apps/web/package.json
- apps/web/pages/api/basenames/[name]/assets/cardImage.svg.tsx
- apps/web/pages/api/basenames/[name]/assets/coverImage.png.tsx
- apps/web/pages/api/basenames/contract-uri.json.ts
- apps/web/pages/api/basenames/metadata/[tokenId].ts
- apps/web/src/components/ConnectWalletButton/ConnectWalletButton.tsx
- yarn.lock
Note: Waiting on onchainkit new version.
> fix asset resolution and metadata domains

- apps/web/pages/names.tsx
- apps/web/src/components/Basenames/RegistrationFlow.tsx
> Automatically switch chain to base

- apps/web/next-env.d.ts
- apps/web/pages/_app.tsx
- apps/web/pages/_document.tsx
- apps/web/pages/about.tsx
- apps/web/pages/bootcamp.tsx
- apps/web/pages/cookie-policy.tsx
- apps/web/pages/ecosystem.tsx
- apps/web/pages/index.tsx
- apps/web/pages/jobs.tsx
- apps/web/pages/name/[username].tsx
- apps/web/pages/names.tsx
- apps/web/pages/onchainsummer.tsx
- apps/web/pages/third-party-cookies.tsx
- apps/web/src/components/Basenames/UsernameProfile/index.tsx
- apps/web/src/components/Basenames/UsernameProfileCard/index.tsx
- apps/web/src/components/Basenames/UsernameProfileSectionExplore/index.tsx
- apps/web/src/hooks/useReadBaseEnsTextRecords.ts
- ECO-176: Fix social overflow
- ECO-176: Fix bio overflow
- ECO-179: Fix base learn link
- ECO-180: Fix card links
- ECO-171: Fix document metadata
> Basename feedback fixes

- apps/base-docs/src/components/Hero/index.tsx
* Changed the `EXPERIMENT_KEY` used in the Hero experiment
vercel preview
> Fix: Update experiment key

- apps/web/pages/api/basenames/contract-uri.json.ts
- apps/web/pages/api/basenames/contract-uri.ts
- apps/web/src/components/ConnectWalletButton/ConnectWalletButton.tsx
> Fix ens dropdown

- apps/web/src/components/Basenames/RegistrationForm/index.tsx
this error is already assigned to another value which is used
> chore: rm log and duplicate error assignment

- .github/workflows/node.js.yml
> Remove node16 from node build gh action

- apps/base-docs/docusaurus.config.js
> Revert "fix: disable trailingSlash to fix relative link resolution in docs"

- apps/web/src/components/Basenames/RegistrationBrand/index.tsx
- apps/web/src/components/ConnectWalletButton/ConnectWalletButton.tsx
removes duplicate classes and unnecessary whitespace
> chore: cleans up some tailwind classes

- apps/web/src/components/Basenames/RegistrationContext.tsx
> fix: disregard calls success/failure and proceed when ens resolves

- apps/web/src/components/Basenames/RegistrationFlow.tsx
- apps/web/src/components/Basenames/RegistrationSearchInput/index.tsx
- apps/web/src/components/Basenames/RegistrationSearchInput/types.tsx
> Adjust home page search input for mobile

- apps/web/src/components/Basenames/RegistrationFlow.tsx
Ref: https://linear.app/coinbase/issue/ECO-238/mobile-pills-registration-page
> ECO-238: Update registration step and padding for mobile/desktop

- apps/web/src/components/Basenames/RegistrationSearchInput/index.tsx
> Hide 'available' in search on mobile

- apps/web/src/components/Basenames/UsernameProfileEditModal/index.tsx
> Always close edit profile modal on tx success

- apps/web/src/components/Basenames/FloatingENSPills.tsx
- apps/web/src/components/Basenames/RegistrationBrand/index.tsx
- apps/web/src/components/Basenames/RegistrationFlow.tsx
|before|after|
|-|-|
|![image](https://github.com/user-attachments/assets/59bfc9aa-2b31-4200-9795-6a3646d948c5)|![image](https://github.com/user-attachments/assets/30d12545-c055-4c76-8e91-86e3cca2463a)|
> stop trying to access window client-side; make text smaller on tiny screens

- apps/web/src/components/Basenames/RegistrationFlow.tsx
- apps/web/src/components/Basenames/UsernamePill/index.tsx
- apps/web/src/components/Basenames/UsernamePill/types.ts
- apps/web/src/components/Basenames/UsernameProfileSidebar/index.tsx
- apps/web/tailwind.config.js
> Registration pill dark shimmer effect

- apps/web/src/components/Basenames/RegistrationBackground/index.tsx
So we don't make motion sensitive people sick with the spinning backgrounds
> Hide video backgrounds for people with prefers-reduced-motion

- apps/web/app/(base-org)/ecosystem/page.tsx
- apps/web/app/(basenames)/name/not-found/page.tsx
- apps/web/app/(basenames)/names/page.tsx
- apps/web/package.json
- yarn.lock
> [CHORE] Try latest nextjs version

- apps/web/src/components/Basenames/RegistrationBackground/index.tsx
> Add playsInline and muted to video background elements

- apps/base-docs/tutorials/data.json
- apps/base-docs/tutorials/docs/1_thirdweb-unreal-nft-items.md
- apps/base-docs/tutorials/docs/2_coinbase-smart-wallet.md
- apps/base-docs/tutorials/docs/2_simple-onchain-nfts.md
> Fix simple onchain nfts

- .buildkite/pipeline.yml
- apps/base-docs/Dockerfile
- apps/base-docs/tutorials/data.json
- apps/bridge/Dockerfile
- apps/web/Dockerfile
- apps/web/package.json
- yarn.lock
> Use node LTS and Update nextjs

- apps/web/app/(basenames)/layout.tsx
- apps/web/app/(basenames)/name/[username]/page.tsx
- apps/web/app/(basenames)/names/page.tsx
- apps/web/app/AppProviders.tsx
- apps/web/app/datadog.ts
- apps/web/contexts/Errors.tsx
- apps/web/pages/api/basenames/[name]/assets/cardImage.svg.tsx
- apps/web/pages/api/basenames/[name]/assets/coverImage.png.tsx
- apps/web/pages/api/basenames/contract-uri.json.ts
- apps/web/pages/api/basenames/contract-uri.ts
- apps/web/pages/api/basenames/metadata/[tokenId].ts
- apps/web/src/components/Basenames/RegistrationContext.tsx
- apps/web/src/components/Basenames/RegistrationForm/index.tsx
- apps/web/src/components/Basenames/RegistrationProfileForm/index.tsx
- apps/web/src/components/Basenames/UsernameProfileEditModal/index.tsx
- apps/web/src/components/Jobs/JobsList.tsx
- apps/web/src/components/Layout/UsernameNav/index.tsx
- apps/web/src/hooks/useAlternativeNameSuggestions.ts
- apps/web/src/hooks/useAttestations.ts
- apps/web/src/hooks/useBasenameChain.ts
- apps/web/src/hooks/useRegisterNameCallback.ts
Reference: https://linear.app/coinbase/issue/ECO-258/basename-log-caught-errors-to-datadog
Log errors, fallback to console for development
> ECO-258: Log error to DD

- apps/web/src/components/Basenames/RegistrationSearchInput/index.tsx
Search input magics away disallowed characters now.
> Filter to only allowed characters

- apps/web/src/components/Basenames/RegistrationSearchInput/index.tsx
- apps/web/src/components/Basenames/UsernameTextRecordInlineField/index.tsx
> Disable Autocapitalize in username search and social inputs

- apps/web/src/components/Basenames/RegistrationFlow.tsx
- apps/web/src/components/ConnectWalletButton/ConnectWalletButton.tsx
> fix: consistent border rad; click-to-copy

- apps/web/next.config.js
> [fix]: try no-cache so CF can (maybe) cache our page properly

- apps/web/app/(base-org)/ecosystem/page.tsx
- apps/web/next.config.js
- apps/web/pages/api/basenames/[name]/assets/cardImage.svg.tsx
- apps/web/pages/api/basenames/[name]/assets/coverImage.png.tsx
- apps/web/src/components/About/Hero.tsx
- apps/web/src/components/Basenames/FloatingENSPills.tsx
- apps/web/src/components/Basenames/UsernameAvatarField/index.tsx
- apps/web/src/components/Basenames/UsernameProfileNotFound/index.tsx
- apps/web/src/components/BuilderNft/BuilderNftHero.tsx
- apps/web/src/components/CoreContributors/CoreContributors.tsx
- apps/web/src/components/Ecosystem/Card.tsx
- apps/web/src/components/Ecosystem/List.tsx
- apps/web/src/components/ImageAdaptive/index.tsx
- apps/web/src/components/ImageOptimized/index.tsx
- apps/web/src/components/ImageRaw/index.tsx
- apps/web/src/components/ImageSmart/index.tsx
- apps/web/src/components/ImageWithLoading/index.tsx
- apps/web/src/components/JoinTheCommunity/JoinTheCommunity.tsx
- apps/web/src/components/Layout/UsernameNav/index.tsx
- apps/web/src/components/Logo/Logo.tsx
- apps/web/src/components/OnchainSummer/EventsBlock.tsx
- apps/web/src/components/OnchainSummer/Hero.tsx
- apps/web/src/components/OnchainSummer/SponsorsBlock.tsx
- apps/web/src/components/Partnerships/Partnerships.tsx
- apps/web/src/components/StartBuildingOnBase/StartBuildingOnBase.tsx
- apps/web/src/utils/images.ts
- apps/web/tsconfig.json
Using NextJS `<Image/>` for everything and allowing IPFS and other domains via remotePatterns was highlighted as a security risk.
Changes:
Will output images with direct source, instead of proxy via image optimizer.
Will figure out wether using `<ImageRaw/>` or next's `<Image/>` based on the source, for ease of development.
> Feat: <ImageAdaptive /> 

- apps/web/src/components/Basenames/RegistrationFlow.tsx
- apps/web/src/components/Basenames/RegistrationForm/index.tsx
- apps/web/src/components/Basenames/RegistrationSearchInput/index.tsx
- apps/web/src/components/BuilderNft/BuilderNftHero.tsx
- apps/web/src/components/EmpoweredByCoinbase/EmpoweredByCoinbase.tsx
- apps/web/src/components/GetConnected/GetConnected.tsx
- apps/web/src/components/Home/Hero.tsx
**After**
https://github.com/user-attachments/assets/a91394eb-8303-47cc-b146-6517c787af03
**Before**
https://github.com/user-attachments/assets/d1eb86fa-1029-493d-9ab0-1a31198353f3
> feat: better name price loading state and clean up empty spaces in class names

- apps/web/src/components/Basenames/RegistrationContext.tsx
- apps/web/src/components/Basenames/RegistrationForm/index.tsx
- apps/web/src/hooks/useRegisterNameCallback.ts
Removing the experimental hooks since we don't rely on them anymore.
> [CHORE] Remove experimental hooks

- apps/web/package.json
- apps/web/src/components/Basenames/UsernameProfileContent/index.tsx
- apps/web/src/components/Basenames/UsernameProfileSectionBadges/Badges/index.tsx
- apps/web/src/components/Basenames/UsernameProfileSectionBadges/index.tsx
- apps/web/src/components/Basenames/UsernameProfileSectionExplore/index.tsx
- apps/web/src/components/Basenames/UsernameProfileSectionTitle/index.tsx
- apps/web/src/components/Layout/UsernameNav/index.tsx
- yarn.lock
> Basename: Fix mobile badge and navigation layout

- apps/web/src/components/Layout/Nav/DesktopNav.tsx
- apps/web/src/components/Layout/Nav/MobileMenu.tsx
- apps/web/src/components/Layout/Nav/Nav.tsx
* Added event logging to base.org navbar
locally
> Feat: Log Events from Base.org Navbar

- apps/web/next.config.js
- apps/web/package.json
- apps/web/src/components/Basenames/UsernameAvatarField/index.tsx
- apps/web/src/components/Basenames/UsernamePill/index.tsx
- apps/web/src/components/Basenames/UsernameProfileEditModal/index.tsx
- apps/web/src/components/ConnectWalletButton/UserAvatar.tsx
- apps/web/src/components/DropdownItem/index.tsx
- apps/web/src/components/DropdownMenu/index.tsx
- apps/web/src/hooks/useBaseEnsAvatar.ts
- apps/web/src/hooks/useBaseEnsName.ts
- apps/web/src/utils/images.ts
- apps/web/src/utils/urls.ts
- apps/web/src/utils/usernames.ts
- yarn.lock
> BAAP-135: Basename IPFS avatar support

- apps/web/src/components/Button/Button.tsx
- apps/web/src/components/Button/ButtonWithLink.tsx
- apps/web/src/components/Button/ButtonWithLinkAndEventLogging.tsx
* added two new Button components
* ButtonWithLink natively includes a link
* ButtonWithLinkAndEventLogging builds upon ButtonWithLink, adding event logging
locally
> Feat: Added ButtonWithLink and ButtonWithLinkAndEventLogging

- apps/web/src/components/Basenames/RegistrationForm/index.tsx
removes a link from some copy in anticipation of GA launch
> chore: remove interest form

- apps/web/src/utils/proofs/sybil_resistance.ts
This PR applies 2 fixes to the attestation discount signing process:
1: set the signature expiration time equal to the current time + the expiration in seconds value. currently the expiration time is equal to the expiration in seconds value
2: sign the message using a signing utility that will not automatically add the ` "\x19Ethereum Signed Message:\n000000"` header.
locally on testnet
> Fix expiration and signing for attestation discounts

- apps/web/pages/api/proofs/baseEthHolders/index.ts
- apps/web/pages/api/proofs/bns/index.ts
- apps/web/src/addresses/usernames.ts
- apps/web/src/hooks/useAttestations.ts
- apps/web/src/utils/proofs/proofs_storage.ts
- apps/web/src/utils/proofs/types.ts
Add Base.eth NFT Holders discount. Did small cleanup so that we can reuse the reponse object for all merkle tree proof requests
local testing
> Add Base.eth NFT Holders discount

- apps/base-docs/base-learn/docs/welcome.md
- apps/base-docs/src/theme/DocItem/Content/index.js
- apps/base-docs/tutorials/data.json
- apps/base-docs/tutorials/docs/0_deploy-with-fleek.md
Testing using `image` in the frontmatter for docs pages to confirm it will correctly override image set in docusaurus config.
> Test Image property in frontmatter

- apps/web/src/components/Basenames/UsernameProfileCard/index.tsx
- apps/web/src/components/Basenames/UsernameProfileSidebar/index.tsx
- apps/web/src/utils/usernames.ts
|before|after|
|-|-|
|![image](https://github.com/user-attachments/assets/dc97342b-0ecd-4a23-bc2e-fccf5017836b)|<img width="262" alt="image" src="https://github.com/user-attachments/assets/72bf66b7-503b-49b2-bf18-9c490402b7a1">|
> small fixes to the UsernamesProfileSidebar

- apps/base-docs/docusaurus.config.js
> move metadatas to theme, remove image tag

- apps/base-docs/base-learn/docs/frontend-setup/wallet-connectors.md
- apps/base-docs/docs/tools/hardhat.md
- apps/base-docs/docs/tools/web3.md
- apps/base-docs/src/theme/Root.jsx
- apps/base-docs/tutorials/data.json
- apps/base-docs/tutorials/docs/0_deploy-with-hardhat.md
- apps/base-docs/tutorials/docs/0_run-a-base-node.md
- apps/base-docs/tutorials/docs/1_2_smart-wallet-and-eoa-with-onchainkit.md
- apps/base-docs/tutorials/docs/1_3_smart-wallet-and-rainbowkit.md
- apps/base-docs/tutorials/docs/1_4_farcaster-frames-nft-minting.md
- apps/base-docs/tutorials/docs/1_5_farcaster-frames-nocode-minting.md
- apps/base-docs/tutorials/docs/2_1_simple-onchain-nfts.md
- apps/base-docs/tutorials/docs/4_account-abstraction-with-biconomy.md
- apps/base-docs/tutorials/docs/4_hardhat-profiling-size.md
- apps/base-docs/tutorials/docs/5_cross-chain-with-ccip.md
- apps/base-docs/tutorials/docs/5_cross-chain-with-layerzero.md
- apps/base-docs/tutorials/docs/5_oracles-chainlink-price-feeds.md
- apps/base-docs/tutorials/docs/5_oracles-pyth-price-feeds.md
- apps/base-docs/tutorials/docs/5_oracles-supra-vrf.md
- Remove `mounted` checks on the providers to enable SSR
- Fix broken links preventing build
> Enable SRR and fix broken links

- apps/web/src/components/GetStarted/Funding.tsx
* Updated card 3 of Fund Your Project to Ecosystem Fund
locally
> Chore: Add Ecosystem Fund to `/getstarted`

- apps/web/src/components/Basenames/UsernameProfileContext/index.tsx
- apps/web/src/components/Basenames/UsernameProfileSidebar/index.tsx
- apps/web/src/components/Basenames/UsernameProfileTransferOwnershipModal/index.tsx
- apps/web/src/components/Basenames/UsernameTextRecordInlineField/index.tsx
- apps/web/src/hooks/useReadBaseEnsTextRecords.ts
- apps/web/src/utils/usernames.ts
https://linear.app/coinbase/issue/BAPP-262/customize-profile-add-validation-on-social-text-records-inputs
Validate textRecords
Sanitize textRecords
Tidy up modal:
> Design feedback & sanitize / validate text records BAPP-262

- apps/web/src/addresses/usernames.ts
Update mainnet discount validator contract addresses
> Update mainnet discount validator contract addresses

- apps/web/src/components/ConnectWalletButton/ConnectWalletButton.tsx
* added a property to the `wallet_connected` event context to track wallet connector id for additional granularity
locally
> Chore: Added `wallet_connector_id` to `wallet_connected` event context

- apps/web/pages/api/proofs/baseEthHolders/index.ts
- apps/web/pages/api/proofs/bns/index.ts
- apps/web/pages/api/proofs/cb1/index.ts
- apps/web/pages/api/proofs/cbid/index.ts
- apps/web/pages/api/proofs/coinbase/index.ts
- apps/web/pages/api/proofs/earlyAccess/index.ts
- apps/web/src/hooks/useAttestations.ts
- apps/web/src/utils/proofs/index.ts
- apps/web/src/utils/proofs/proofs_storage.ts
- apps/web/src/utils/proofs/requests.ts
- apps/web/src/utils/proofs/types.ts
Refactor proof APIs to avoid repeating code.
Moved the error checking back to utils
Added a new proof exception to keep status codes
Refactored Merkle proofs into shared codebase
tested errors and happy flow for sybil and merkle focused proofs
> Refactor proof APIs

- apps/web/src/components/GetStarted/BuildersMostWanted.tsx
* changed description to coming soon
locally
> Chore: Update Basename Claim Card

- apps/web/src/components/Basenames/UsernameProfileContent/index.tsx
> hotfix:duplicate badge render

- apps/web/src/components/Basenames/UsernameProfileContent/index.tsx
- apps/web/src/components/Basenames/UsernameProfileSettingsManageProfile/index.tsx
- apps/web/src/utils/usernames.ts
> Feature flag on the Pin Casts feature

- apps/web/src/addresses/usernames.ts
Add mainnet contract addresses for registrar and price oracle
> Add mainnet contract addresses for registrar and price oracle

- apps/web/src/components/Basenames/UsernameProfileSectionBadges/Badges/index.tsx
Talent Protocol request copy edits.
> Update Talent Protocol badge copy

- apps/web/src/components/Basenames/RegistrationFlow.tsx
- apps/web/src/components/Basenames/RegistrationLearnMoreModal/index.tsx
Add cb.id cutoff of August 9 to the discount tooltip.
> Add cb.id cutoff + update tooltip

- apps/web/src/hooks/useBasenameChain.ts
> Always use a supported chain

- apps/web/src/components/Basenames/RegistrationForm/index.tsx
Don't disable the network switch button when ETH balance is too low on the wrong chain.
> Fix network switch button disabled when balance is too low

- apps/web/src/components/ConnectWalletButton/ConnectWalletButton.tsx
- apps/web/src/components/Layout/UsernameNav/index.tsx
> Prompt network switching on profile, switch directly don't show network modal on connect wallet

- apps/web/src/components/ConnectWalletButton/ConnectWalletButton.tsx
- apps/web/src/components/Layout/UsernameNav/index.tsx
> Fix banner and connect wallet

- apps/web/src/components/Basenames/PremiumExplainerModal/index.tsx
- apps/web/src/components/Basenames/RegistrationForm/index.tsx
- apps/web/src/hooks/useAttestations.ts
This also fixes the basedoteth discount
> fix: stop attempting to double discount

- apps/base-docs/docs/tools/basenames-faq.md
- apps/base-docs/docs/tools/basenames.md
- apps/base-docs/sidebars.js
Basenames Full FAQ on docs site.
> Add Basenames FAQ

- apps/base-docs/src/components/Banner/Banner.tsx
- apps/base-docs/src/components/Icon/index.tsx
- apps/base-docs/src/components/Modal/BasenamesLaunchModal/HomepageModal.jsx
- apps/base-docs/src/components/Modal/BasenamesLaunchModal/ModalClose.jsx
- apps/base-docs/src/components/Modal/BasenamesLaunchModal/ModalCta.jsx
- apps/base-docs/src/components/Modal/BasenamesLaunchModal/index.jsx
- apps/base-docs/src/components/Modal/BasenamesLaunchModal/styles.module.css
- apps/base-docs/src/pages/index.tsx
- libs/base-ui/contexts/Analytics.tsx
* added a basenames launch modal on docs.base.org
locally
> Feat: Basename Launch Modal on Docs

- apps/web/src/components/Basenames/PoweredByEns/index.tsx
- apps/web/src/components/Basenames/RegistrationFaq/index.tsx
- apps/web/src/components/Basenames/RegistrationValueProp/index.tsx
> Updates to landing page copy

- apps/web/src/components/Layout/Nav/DesktopNav.tsx
- apps/web/src/components/Layout/Nav/MobileMenu.tsx
> bapp-101: add names menu nav

- apps/web/src/components/Basenames/RegistrationFlow.tsx
> Prevent discount pricing with huge numbers from overlapping

- apps/web/src/components/GetStarted/BuildersMostWanted.tsx
* updated the Basenames card copy and link post-launch
locally
> Chore: Update /getstarted Basenames Card

- apps/web/src/components/Basenames/PremiumExplainerModal/index.tsx
- apps/web/src/components/Basenames/RegistrationForm/index.tsx
> Fix price display modal

- apps/base-docs/src/components/Modal/BasenamesLaunchModal/ModalCta.jsx
* updated the link on the docs basenames launch modal
locally
> Chore: Update link with utm code

- apps/web/src/components/Basenames/PoweredByEns/index.tsx
> Remove dash in open source on the lp

- apps/base-docs/sidebars.js
- apps/base-docs/tutorials/data.json
update sidebar.js to include wagmi + onchainkit basename tutorials
> update sidebar.js to include wagmi + onchainkit basename tutorials

- apps/web/src/components/Basenames/RegistrationSearchInput/index.tsx
- apps/web/src/components/Layout/Nav/DesktopNav.tsx
- apps/web/src/components/Layout/Nav/MobileMenu.tsx
> Switch nav + regex

- apps/base-docs/src/components/Banner/Banner.tsx
- apps/base-docs/src/theme/Navbar/index.js
- apps/web/src/components/Layout/Nav/Nav.tsx
* changed the banners on base.org and docs.base.org for basenames launch
locally
> Feat: Basenames Launch Banners

- apps/web/app/(basenames)/name/[username]/page.tsx
- apps/web/src/utils/usernames.ts
Makes http://base.org/name/türkiye visible
> Allow discovery of names with unicode

- apps/web/pages/api/basenames/metadata/[tokenId].ts
> [FIX]: Fix token metadata json: Enforce 32 bytes for toHex

- apps/web/middleware.ts
> Allow blob: in CSP so image upload previews work

- apps/web/src/components/Basenames/RegistrationSearchInput/index.tsx
> Don't strip dashes from search input

- apps/web/app/datadog.ts
Add APM tracing into next.js APIs. This will give more tracing context into RUM monitoring
> Add APM tracing into next.js APIs

- apps/web/src/components/Basenames/RegistrationShareOnSocials/index.tsx
* removed link from social share text to ensure URL metadata is to user's name
> Fix: Update social share text

- apps/web/src/components/Basenames/HomepageModal/ModalCta.tsx
* added utm codes to launch modal on base-web
> Chore: added utm code to basenames launch modal

- apps/base-docs/tutorials/docs/1_verify-contract-with-basescan.md
Fixed a broken reference link to Foundry
> fix foundry reference link

- apps/web/pages/api/basenames/frame/frameResponses.ts
* fixed the path for the tx success image
> Fix: Tx Success image path

- .codeflow.yml
- tools/ci/build-dockerfile.sh
Switch to using amd64 compatible build 
> Build with amd64 compatible image

- apps/web/pages/api/basenames/frame/assets/registrationFrameImage.png.tsx
* added conditional to plurality of "years" in confirmation frame
locally
> added conditional to plural

- apps/web/app/AppProviders.tsx
- apps/web/app/datadog.ts
- apps/web/contexts/Errors.tsx
- apps/web/next.config.js
- apps/web/pages/api/basenames/[name]/getBasenameRegistrationPrice.ts
- apps/web/pages/api/basenames/frame/01_inputSearchValue.ts
- apps/web/pages/api/basenames/metadata/[tokenId].ts
- apps/web/pages/api/basenames/talentprotocol/[address].ts
- apps/web/pages/api/checkNftProof/index.ts
- apps/web/pages/api/name/[alreadyClaimedName].ts
- apps/web/pages/api/paymaster/index.ts
- apps/web/pages/api/proofs/baseEthHolders/index.ts
- apps/web/pages/api/proofs/bns/index.ts
- apps/web/pages/api/proofs/cb1/index.ts
- apps/web/pages/api/proofs/cbid/index.ts
- apps/web/pages/api/proofs/coinbase/index.ts
- apps/web/pages/api/proofs/earlyAccess/index.ts
- apps/web/pages/api/registry/entries.ts
- apps/web/pages/api/registry/featured.ts
- apps/web/src/cdp/api/get_linked_addresses.ts
- apps/web/src/utils/logger.ts
- apps/web/src/utils/paymasterSponsor.ts
- apps/web/src/utils/usernames.ts
Add datadog logging for APIs
logger object won't work on FE since the datadog key is not present there
tested locally
> Datadog logs

- .codeflow.yml
- tools/ci/build-dockerfile.sh
> Revert "Build with amd64 compatible image"

- apps/web/app/(basenames)/name/[username]/page.tsx
- apps/web/src/components/Basenames/ProfilePromo/dynamic.tsx
- apps/web/src/components/Basenames/UsernameProfileContext/index.tsx
- apps/web/src/hooks/useReadBaseEnsTextRecords.ts
- apps/web/src/hooks/useSetPrimaryBasename.ts
- apps/web/src/utils/usernames.ts
- Disable refetchOnWindowFocus where relevant
- Dynamically import ProfilePromo to avoid rehydration errors
> BAPP-463: disable refetch on window focus, fix hydration error

- apps/base-docs/docs/tools/data-indexers.md
- apps/base-docs/tutorials/data.json
Added The Indexing Company to the list of indexers, because we support the Base chain.
Yes, tested build locally without errors. Production build failed due to vercel permissions.
> add Indexing Co to list of indexers

- apps/base-docs/docs/tools/data-indexers.md
Added DipDup indexer in the Data indexers section
Started the project locally according to the instructions in [README.md](https://github.com/base-org/web/blob/master/README.md)
> Added DipDup indexer

- apps/base-docs/docs/tools/account-abstraction.md
Adding thirdweb to list of Account Abstraction tooling.
> Update account-abstraction docs

- apps/web/src/components/Basenames/RegistrationForm/index.tsx
- apps/web/src/hooks/useRegisterNameCallback.ts
> Basename: don't see new name as primary if user already has one

- apps/web/app/AppProviders.tsx
- apps/web/app/datadog.ts
- apps/web/contexts/Errors.tsx
- apps/web/next.config.js
- apps/web/pages/api/basenames/[name]/getBasenameRegistrationPrice.ts
- apps/web/pages/api/basenames/frame/01_inputSearchValue.ts
- apps/web/pages/api/basenames/metadata/[tokenId].ts
- apps/web/pages/api/basenames/talentprotocol/[address].ts
- apps/web/pages/api/checkNftProof/index.ts
- apps/web/pages/api/name/[alreadyClaimedName].ts
- apps/web/pages/api/paymaster/index.ts
- apps/web/pages/api/proofs/baseEthHolders/index.ts
- apps/web/pages/api/proofs/bns/index.ts
- apps/web/pages/api/proofs/cb1/index.ts
- apps/web/pages/api/proofs/cbid/index.ts
- apps/web/pages/api/proofs/coinbase/index.ts
- apps/web/pages/api/proofs/earlyAccess/index.ts
- apps/web/pages/api/registry/entries.ts
- apps/web/pages/api/registry/featured.ts
- apps/web/src/cdp/api/get_linked_addresses.ts
- apps/web/src/utils/logger.ts
- apps/web/src/utils/paymasterSponsor.ts
- apps/web/src/utils/usernames.ts
Adding back datadog logs. Previous implementation had an issue while using an uninitialized logger on cookies logging.
tested locally and in dev.
> Add datadog logs

- apps/web/pages/api/decorators.ts
- apps/web/pages/api/proofs/cb1/index.ts
- apps/web/src/utils/logger.ts
- apps/web/src/utils/metrics.ts
- apps/web/src/utils/proofs/sybil_resistance.ts
Add metrics and latencies for sybil resistance
tested locally: [metric](https://app.datadoghq.com/metric/explorer?fromUser=false&start=1724702037019&end=1724702937019&paused=false#N4Ig7glgJg5gpgFxALlAGwIYE8D2BXJVEADxQEYAaELcqyKBAC1pEbghkcLIF8qo4AMwgA7CAgg4RKUAiwAHOChASAtnADOcAE4RNIKtrgBHPJoQaUAbVBGN8qVoD6gnNtUZCKiOq279VKY6epbINiBQnhhOGvjaAMZKyCDqCLrxllQiGOrKQdpYZAYg+TTJGABuMMgARhhabjAAdPLaODiCGk0aWDUQaE2YCHAi8VhN8AhOnsMaCJ6SIhrAAFQ8IDwAulSu7niYoeG7qvsYeWYFRVtUc1hoSaDyGPcIw8pQODBO8QcaEPHFNCiOBOOSKZSxIFQQHApz0JjKERuDxoDb8CD2TBYUEKJIgOraSxbHh8ECY8QAYSkwhgKBE+zQPCAA)
> Add metrics and latencies for sybil resistance

- apps/web/pages/api/proofs/cb1/index.ts
> Update latency metric

- apps/web/app/(base-org)/ecosystem/page.tsx
- apps/web/src/components/Ecosystem/Content.tsx
- apps/web/src/components/Ecosystem/List.tsx
Ecosystem page doesn't work properly unless done as a client side render.
> Fix client side functionality of ecosystem page

- apps/web/app/(basenames)/name/[username]/page.tsx
- apps/web/src/components/Basenames/UsernameProfileContext/index.tsx
- apps/web/src/components/Basenames/UsernameProfileSectionBadges/index.tsx
- apps/web/src/components/Basenames/UsernameProfileSettings/index.tsx
- apps/web/src/components/Basenames/UsernameProfileSettingsAvatar/index.tsx
- apps/web/src/components/Basenames/UsernameProfileSettingsManageProfile/index.tsx
- apps/web/src/components/Basenames/UsernameProfileSettingsName/index.tsx
- apps/web/src/components/Basenames/UsernameProfileSettingsOwnership/index.tsx
- apps/web/src/components/Basenames/UsernameProfileSidebar/index.tsx
- apps/web/src/components/Basenames/UsernameProfileTransferOwnershipModal/context.tsx
- apps/web/src/components/Basenames/UsernameProfileTransferOwnershipModal/index.tsx
- apps/web/src/hooks/useSetPrimaryBasename.ts
- apps/web/src/utils/usernames.ts
> Add "Claim name" button for direct NFT transfers

- apps/web/src/components/Basenames/UsernameProfileSectionBadges/hooks/useBuildathon.ts
- apps/web/src/components/Basenames/UsernameProfileSectionBadges/index.tsx
> Add buildathon SBT winner badge

- apps/web/next.config.js
Added csp entries for fonts-src default-src a connect-src
This should reduce many of these issues:
https://app.datadoghq.com/rum/performance-monitoring?query=%40session.type%3Auser%20%40application.id%3A16db4f8f-831a-4df5-b78b-546405085227&filters=%5B%22env%22%2C%22service%22%2C%22version%22%2C%22%40session.type%22%2C%22%40geo.country%22%2C%22%40device.type%22%2C%22%40usr.email%22%5D&fromUser=false&fullscreen_end_ts=1724792312000&fullscreen_paused=false&fullscreen_refresh_mode=sliding&fullscreen_start_ts=1724788712000&tab=errors&view=spans&from_ts=1724788712164&to_ts=1724792312164&live=true
> Csp add resrouces

- apps/web/next.config.js
> revert font-src

- apps/web/pages/api/basenames/metadata/[tokenId].ts
- apps/web/pages/api/basenames/talentprotocol/[address].ts
- apps/web/pages/api/name/[alreadyClaimedName].ts
- apps/web/pages/api/paymaster/index.ts
- apps/web/pages/api/proofs/bns/index.ts
- apps/web/pages/api/proofs/cb1/index.ts
- apps/web/pages/api/proofs/cbid/index.ts
- apps/web/pages/api/proofs/coinbase/index.ts
- apps/web/pages/api/proofs/earlyAccess/index.ts
- apps/web/pages/api/registry/entries.ts
- apps/web/pages/api/registry/featured.ts
- apps/web/scripts/helpers/getAvatarUri.js
- apps/web/src/cdp/api/cb-gpt.ts
- apps/web/src/cdp/api/get_linked_addresses.ts
- apps/web/src/utils/logger.ts
- apps/web/src/utils/proofs/sybil_resistance.ts
- apps/web/src/utils/usernames.ts
> Log errors correctly

- apps/web/pages/api/proofs/cb1/index.ts
> remove unneeded log

- apps/web/app/(basenames)/name/[username]/page.tsx
from
```
base.org/shrek.base.eth
```
to
```
base.org/name/shrek
```
> FIX: Basename og:url

- apps/web/package.json
- apps/web/pages/api/proofs/cb1/index.ts
- apps/web/pages/api/proofs/coinbase/index.ts
- apps/web/tracer/initialize.js
- apps/web/tracer/tracer.ts
- yarn.lock
Add datadog APM for tracing, statsd events, and other metrics.
local + dev
> tracer pkg

- .codeflow.yml
- apps/web/Dockerfile
Target arm64 architecture in web Dockerfile
dev
> Graviton build update

- .codeflow.yml
> Specify architecture for docs and bridge

- apps/web/app/(basenames)/name/[username]/opengraph-image.tsx
- apps/web/pages/api/basenames/[name]/assets/cardImage.svg.tsx
Use Viem's `getEnsAvatar` for proper resolution
> [FIX] Basename Avatar IPFS resolution for card and cover image

- apps/base-docs/docs/tokens/token-list.md
- apps/web/src/components/Features/Features.tsx
- apps/web/src/components/Partnerships/Partnerships.tsx
This updates a few references to highlight the collective Superchain that Base is part of
N/A
Localhost
> style: Update Optimism references

- apps/web/pages/api/basenames/metadata/[tokenId].ts
- apps/web/src/utils/usernames.ts
> Basenames: add nameExpires to the tokenMetadata JSON

- apps/web/src/components/Layout/Footer/Footer.tsx
* Update one of the footer links to Builder Resource Kit
locally
> Chore: update footer with builder resource kit

- apps/base-docs/src/theme/Navbar/ColorModeToggle/index.js
* Added event logging for toggling colorMode on base docs
locally
> Chore: Add event logging to colorMode toggle

- apps/web/src/components/Basenames/UsernameProfileSectionBadges/hooks/useBaseGrant.ts
- apps/web/src/components/Basenames/UsernameProfileSectionBadges/index.tsx
Adds implementation of Base Grantee badge.
> Add Base Grantee badge

- apps/base-docs/docs/tools/basenames-faq.md
- apps/web/src/components/Basenames/UsernameProfileSettingsContext/index.tsx
> Update FAQ + remove subdomain from profile settings

- apps/web/src/components/Basenames/RegistrationFlow.tsx
- apps/web/src/components/Basenames/RegistrationSearchInput/index.tsx
- apps/web/src/components/Basenames/UsernameProfile/index.tsx
- Remove load/render events in favor of pageview
- Fix invalid name event
> Basename: Fix analytics events

- apps/base-docs/tutorials/data.json
- apps/base-docs/tutorials/docs/2_dynamic-nfts.md
We recently updated some of our tooling and reorganized our docs. This PR updates the dynamic NFT tutorial to use the most recent versions. 
The "core content" of the tutorial has not changed at all, just details on how to use the tooling. 
> Update Irys Dynamic NFT to use latest version of Irys tooling

- apps/base-docs/base-learn/docs/error-triage/error-triage.md
- apps/base-docs/base-learn/docs/hardhat-verify/hardhat-verify-sbs.md
- apps/base-docs/tutorials/data.json
- apps/base-docs/tutorials/docs/5_cross-chain-with-layerzero.md
> Correction of typos

- apps/base-docs/tutorials/docs/5_basename-frames.md
Made paragraphs flow better and improved  basename claim CTA.
> Frames tutorial updates

- apps/web/pages/api/name/[alreadyClaimedName].ts
- apps/web/src/cdp/api/cb-gpt.ts
Add owner registry componentId to cbgpt request. This is required by CB-GPT team
> Add owner registry componentId to cbgpt request

- apps/web/package.json
- yarn.lock
> Revert "fix: bump @frames.js/render version"

- apps/web/src/components/Basenames/UsernameProfileSectionFrames/Frame.tsx
Not all frame responses include the `accepts` data necessary to discriminate between open frames/non. This persists any observed open frame `accepts` data to ensure we don't end up in a state where frames that don't require it are asking for a farcaster signer.
> BAPP-645: User is prompted to sign in with farcaster when interacting with open frames

- apps/web/src/components/Basenames/ConfigureFramesPageContent/FrameBuilder.tsx
|before|after|
|-|-|
|<img width="527" alt="image" src="https://github.com/user-attachments/assets/02a738f0-3aa4-4824-94c8-5029f2f5dd37">|<img width="344" alt="image" src="https://github.com/user-attachments/assets/0ee60598-01d4-468a-80c4-845ff1648a6c">|
> [Polish] “Back” button on mobile should match what we have in settings

- apps/base-docs/docs/building-with-base/fees.md
- apps/base-docs/docs/tools/basenames-faq.md
- apps/base-docs/docs/tools/oracles.md
I changed a few links in the docs that were leading to a dead-end.
> Deadlinks Repair

- apps/web/src/components/Basenames/UsernameProfileSectionHeatmap/index.tsx
|before|after|
|-|-|
|<img width="873" alt="image" src="https://github.com/user-attachments/assets/894bf613-4757-48b4-89b7-e83226e8bc11">|<img width="888" alt="image" src="https://github.com/user-attachments/assets/8043ad8d-aa1d-4a81-9abf-b3f97aee60a0">|
> heatmap-color-update

- apps/web/src/components/SearchAddressInput/index.tsx
https://linear.app/coinbase/issue/BAPP-660/send-name-view-on-basescan-link-directs-to-sepolia
> BAPP-660: Fix explorer redirect link in send name flow

- apps/web/app/frames/route.tsx
- apps/web/src/middleware/ipSafe.spec.ts
@dneilroth had a good nit, and I noticed a thing I could clean up in my tests
> chore: some pr nits

- apps/web/src/components/ChainDropdown/index.tsx
- apps/web/src/components/ConnectWalletButton/ConnectWalletButton.tsx
- apps/web/src/components/Layout/Nav/DesktopNav.tsx
- apps/web/src/components/Layout/Nav/MobileMenu.tsx
- apps/web/src/components/Layout/UsernameNav/index.tsx
- libs/base-ui/utils/logEvent.ts
**Issue**: Coinbase Smart Wallet has no way to switch chain programmatically or within their settings UI. 
**Solution**: Pass `?showChainSwitcher=true` to url to see the current chain / switch chain dropdown.
Default:
Hover:
> chain switcher for developers

- apps/web/src/data/ecosystem.json
Remove broken link that 404s
N/A
Localhost
> fix(ecosystem): Drop Earn Finance

- apps/web/src/components/base-org/root/VideoCardsSection/VideoCard.tsx
- apps/web/src/components/base-org/root/VideoCardsSection/index.tsx
* added superchain link to the decentralization VideoCard
* enabled a ReactNode to be passed as the argument for VideoCard's `description` prop
> Fix: superchain link

- apps/web/src/components/base-org/root/VideoCardsSection/index.tsx
* changed Link component on homepage to our custom implementation for tracking
locally
> Fix: use custom link component

- apps/web/src/components/Basenames/UsernameTextRecordInlineField/index.tsx
- apps/web/src/hooks/useReadBaseEnsTextRecords.ts
- apps/web/src/utils/usernames.ts
https://linear.app/coinbase/issue/BAPP-663/add-the-ability-to-add-up-to-three-websites
> add more websites to default profile

- apps/web/src/utils/usernames.ts
https://linear.app/coinbase/issue/BAPP-527/add-more-skills-to-profiles
adds:
- Data
- Design
- Digital Art
- Photography
> add skill types

- README.md
- apps/web/app/(base-org)/ecosystem/page.tsx
This adds documentation to assist builders updating the Ecosystem page so they can submit their own projects
N/A
Localhost
> docs(ecosystem): Add instrux, how to add an app

- apps/base-docs/docusaurus.config.js
- apps/bridge/src/components/Nav/DesktopNav.tsx
- apps/bridge/src/components/Nav/MobileMenu.tsx
- apps/web/src/components/GetConnected/GetConnected.tsx
- apps/web/src/components/base-org/shared/TopNavigation/index.tsx
* updated farcaster social link to a page that can be viewed in a logged-out state
locally
> updated farcaster social link

- apps/web/app/frames/proxy-ip-check.ts
- apps/web/pages/api/basenames/frame/04_txSubmitted.ts
- apps/web/pages/api/basenames/frame/constants.ts
- apps/web/pages/api/basenames/frame/frameResponses.ts
- apps/web/pages/api/basenames/frame/tx.ts
- apps/web/src/components/Basenames/UsernameProfileSectionFrames/Context.tsx
- apps/web/src/components/Basenames/UsernameProfileSectionFrames/Frame.tsx
- apps/web/src/components/Basenames/UsernameProfileSectionFrames/FrameTheme.tsx
* added support for the Open Frame standard (on top of the existing Farcaster support)
locally
> feat: convert basenames claim frame to open frame

- apps/web/src/components/Basenames/RegistrationLearnMoreModal/index.tsx
- apps/web/src/hooks/useAggregatedDiscountValidators.ts
> Fix coupon code discount priority + talent protocol discount

- apps/web/app/(base-org)/jobs/page.tsx
Add a max age of 30m for the jobs page.
> Fix: Jobs page: Max age 30m for jobs

- apps/web/src/components/CookieBannerWrapper/index.tsx
* added cookie banner to base.org
locally
> fix: restore cookie banner

- apps/web/app/(base-org)/(root)/page.tsx
- apps/web/src/components/ThreeHero/dynamic.tsx
Use dynamic file-as-component.
Before:
```
Route (app)                                                         Size     First Load JS
┌ ○ /                                                               336 kB          538 kB
```
After:
```
Route (app)                                                         Size     First Load JS
┌ ○ /                                                               14.5 kB         217 kB
```
> Fix: Dynamic file import

- apps/web/package.json
- yarn.lock
> Upgrade next

- .github/workflows/file-size-checker.yml
Adding a new action to check for large files (>40MB).
> Github action: check for large files

- apps/web/app/(basenames)/name/[username]/opengraph-image.tsx
- apps/web/pages/api/basenames/[name]/assets/cardImage.svg.tsx
- apps/web/src/components/Basenames/RegistrationProfileForm/index.tsx
- apps/web/src/components/Basenames/UsernameProfileCard/index.tsx
- apps/web/src/components/Basenames/UsernameProfileCasts/index.tsx
- apps/web/src/components/Basenames/UsernameProfileSectionFrames/Context.tsx
- apps/web/src/components/Basenames/UsernameProfileSettingsAvatar/index.tsx
- apps/web/src/components/Basenames/UsernameProfileSettingsManageProfile/index.tsx
- apps/web/src/components/Basenames/UsernameProfileSidebar/index.tsx
- apps/web/src/components/ConnectWalletButton/UserAvatar.tsx
- apps/web/src/components/WalletIdentity/index.tsx
- apps/web/src/hooks/useBaseEnsAvatar.ts
- apps/web/src/hooks/useReadBaseEnsTextRecords.ts
- apps/web/src/hooks/useWriteBaseEnsTextRecords.ts
- apps/web/src/utils/images.ts
- apps/web/src/utils/pinata.ts
- apps/web/src/utils/urls.ts
- apps/web/src/utils/usernames.ts
Leverage Cloudinary & Pinata public gateway for a wider and more flexible IPFS support.
> Feat: IPFS + Cloudinary integration

- apps/web/src/hooks/useAttestations.ts
Update data passed into discount validator contract to correctly include packed token ids. 
Tested locally on testnet + mainnet.
> Fix 1155 Discount validator token encoding

- apps/web/src/components/Layout/UsernameNav/index.tsx
> Fix nav padding

- apps/web/app/AppProviders.tsx
- apps/web/src/components/ConnectWalletButton/ConnectWalletButton.tsx
- apps/web/src/components/ConnectWalletButton/UserAvatar.tsx
> fix wallet avatar dropdown on mobile

- apps/web/src/components/base-org/root/SlidingTextSection/index.tsx
* updated Arabic translation
locally
> fix: update Arabic translation

- apps/base-docs/tutorials/docs/5_cross-chain-with-layerzero.md
> Updated layerZero endpoint URL

- tools/ci/generate-dockerfiles-pipeline.sh
**Description**:  
This PR fixes a minor typo in a comment within the `generate-dockerfiles-pipeline.sh` script. The comment:  
```bash
```  
has been updated to:  
```bash
```  
1. **Improved Readability**: Removing the redundant "a" and properly capitalizing "Buildkite" and "Docker" enhances the clarity and professionalism of the script.  
2. **Consistency**: Ensures comments align with the conventions used in the rest of the project, maintaining a polished and standardized codebase.  
3. **Ease of Understanding**: Clear and accurate comments help contributors and maintainers understand the code and its purpose more effectively.  
No functionality has been changed, and the fix strictly pertains to improving documentation within the code.  
Please review and merge! 🎉
> Typo Update generate-dockerfiles-pipeline.sh

- libs/base-ui/components/Layout/Nav/Banner.tsx
- libs/base-ui/contexts/Analytics.tsx
- libs/base-ui/contexts/Experiments.tsx
- **Removed unnecessary dependencies** in `useCallback` for `linkClick` to optimize performance by reducing unnecessary re-renders.
- **Removed `onKeyDown`** from the close button, as it’s not required for functionality. This streamlines the component’s behavior.
- **Simplified `logEvent` usage**: The `linkClick` function now has a minimal dependency array, making it more concise and efficient.
- The `linkClick` function has been optimized to include only essential dependencies.
- If keyboard accessibility is needed in the future, `onKeyDown` can be reintroduced with specific key checks.
- These changes do not impact the component's behavior, only its performance and readability.
- Manually tested the banner …
> Optimized Banner Component

- apps/base-docs/docs/tools/oracles.md
- apps/base-docs/docusaurus.config.js
- apps/base-docs/src/components/DocFeedback/styles.module.css
Corrected spelling mistakes in documentation and UI text:
`verifable` → `verifiable` 
`Langauge` → `Language` x2.  
`Feedbak` → `Feedback`
These changes improve the clarity and accuracy of the documentation and user interface.
- Please verify that all corrected spellings are consistent throughout the documentation and UI.
- Ensure that no functionality was affected by these text changes.
- Review the corrected terms to make sure they align with the overall style guide.
- Manually reviewed the affected documentation and UI components to confirm spelling corrections.
- Verified that no other content or functionality was unintentionally altered.
> Correct spelling mistakes in documentation and UI text

- README.md
- apps/base-docs/base-learn/docs/advanced-functions/function-modifiers.md
- apps/base-docs/base-learn/docs/arrays/filtering-an-array-sbs.md
- apps/base-docs/base-learn/docs/deployment-to-testnet/contract-verification-sbs.md
- apps/base-docs/base-learn/docs/hardhat-deploy/hardhat-deploy-sbs.md
- apps/base-docs/base-learn/docs/hardhat-testing/hardhat-testing-sbs.md
- apps/base-docs/base-learn/docs/mappings/mappings-sbs.md
- apps/base-docs/base-learn/docs/storage/simple-storage-sbs.md
- apps/base-docs/docs/tools/basenames-faq.md
What changed? Why?
Fixed several typographical errors across multiple documentation files.
Corrected punctuation and formatting issues (e.g., built-in, step-by-step).
Clarified sentence structures for better readability.
These changes aim to enhance the professionalism and readability of the documentation.
Notes to reviewers
Please check if all typographical errors are fixed and if the readability of the text has improved.
Suggest any further edits or improvements if needed.
How has it been tested?
The documents were manually reviewed for spelling, grammar, and formatting issues.
No changes to functionality were made, so no technical testing was required.
> Fix Typographical Errors and Improve Documentation Clarity

- apps/web/app/(basenames)/name/[username]/opengraph-image.tsx
- apps/web/pages/api/basenames/[name]/assets/cardImage.svg.tsx
Issue: Early return is breaking the cards / covers images in some cases.
fix: better conditional usage.
> fix card / cover rendering bug

- apps/web/src/data/ecosystem.json
> fix: fix Contango image

- apps/base-docs/docs/notices/decomissioning-public-geth-archive-snapshots.md
- apps/base-docs/tutorials/docs/0_run-a-base-node.md
Updates our docs post Geth archive snapshot deprecation
N/A
Localhost
> docs(node): Update post Geth archive snapshot deprecation

- apps/base-docs/tutorials/docs/2_ock-fund-tutorial.md
**Description**
Refined and enhanced the tutorial for building a Smart Wallet Funding app using OnchainKit. Improved clarity, fixed typos, and streamlined the setup and implementation steps to ensure a smoother developer experience.
- Corrected typos and grammatical errors for better readability.
- Clarified steps for setting up the project and configuring Smart Wallets.
- Improved code snippets and added inline comments for better understanding.
- Updated references to ensure they align with the latest versions of dependencies and tools.
These changes aim to make the tutorial more approachable and reduce potential friction for developers.
- Double-check if all external links (e.g., to OnchainKit, Viem, and Coinbase) are functioning and …
> Improve Clarity in OnchainKit Smart Wallet Guide

- apps/web/next.config.js
- apps/web/src/hooks/useWriteContractsWithLogs.ts
- tools/ci/generate-dockerfiles-pipeline.sh
> chore: correct typos docs

- apps/base-docs/docs/contracts.md
> Fix broken link: contracts.md

- apps/base-docs/docs/tools/bridges-mainnet.md
- apps/base-docs/tutorials/docs/1_verify-contract-with-basescan.md
- apps/web/src/components/Basenames/UsernameProfileSectionFrames/types.ts
- apps/web/src/hooks/useSetPrimaryBasename.ts
This PR addresses typos and grammatical issues in the project documentation and code comments to improve clarity and readability.  
**Changes Made:**  
1. **Documentation Fixes:**  
- Updated "Double check" → "Double-check" in `bridges-mainnet.md`.  
- Changed "a environment variable" → "an environment variable" in `1_verify-contract-with-basescan.md`.  
2. **Code Comments Fixes:**  
- Corrected "an signer" → "a signer" in `types.ts`.  
- Updated "an name" → "a name" in `useSetPrimaryBasename.ts`.  
Please review the changes to ensure proper grammar usage and that no additional context is required for these updates.  
- Reviewed changes manually for correctness and consistency.  
- Verified no functional code changes were introduced.
> Fix typos and grammatical inconsistencies

- apps/base-docs/tutorials/docs/5_oracles-supra-vrf.md
Updated the Supra Router Contract documentation link to the current working URL.
This update ensures developers can access the correct and up-to-date contract addresses for Supra VRF integration.
> Supra VRF 

- apps/web/app/(basenames)/api/basenames/avatar/ipfsUpload/route.ts
**What changed? 
**Rerrer validation**  -   Referer**
> chore: correct typo route.ts

- apps/bridge/next.config.js
Hey !
Glad I could help .
Br, Guayaba221
> docs fix spelling issue

- apps/web/src/data/ecosystem.json
**Description correction:**
Corrected `transitions` to `transactions` x3
Corrected `OpenFrind` to `OpenFriend`
Corrected `liquitidy` to `liquidity` and also extra spaces deleted.
> fix: typos in documentation files

- apps/base-docs/base-learn/docs/minimal-tokens/minimal-token-sbs.md
correct  **address are visible - address is visible**
> correct minimal-token-sbs.md

- apps/web/src/data/ecosystem.json
**What changed?**
*Openfort:* 
- Updated the description text for better clarity but without altering the meaning.
*Manifold:*
- Updated the description text, likely to improve grammatical clarity or alignment with branding style.
*Everyworld:*
- Fixed a typo in the key for `name`, changing `"name": "Everyworld "` to `"name": "Everyworld",` (removed an extraneous comma).
**Why?**
- The changes appear to focus on improving text clarity, ensuring consistency in descriptions, and fixing syntax issues (e.g., the extra comma in the Everyworld key).
**Notes to reviewers:**
- Ensure the updated descriptions align with the product or service's branding and tone.
- Confirm that the removed comma in the Everyworld key does not introduce errors in parsing or runtime.
1. …
> Update Ecosystem Descriptions and Fix Syntax Issues in JSON

- apps/base-docs/docs/notices/decomissioning-public-geth-archive-snapshots.md
- apps/base-docs/docs/tools/oracles.md
- apps/base-docs/tutorials/docs/1_smart-wallet-spend-permissions.md
- apps/base-docs/tutorials/docs/1_verify-contract-with-basescan.md
- apps/base-docs/tutorials/docs/4_hardhat-test-coverage.md
This PR addresses several minor typographical errors and outdated links in the documentation files to improve readability, accuracy, and user experience. 
The following changes have been made:
1. **Typographical Fixes**:
- **`1_verify-contract-with-basescan.md`**:
- Corrected usage of "a" to "an" in references to "RPC URL".
- **`4_hardhat-test-coverage.md`**:
- Fixed grammatical errors in test descriptions, updating "a owner" to "an owner".
- **`1_smart-wallet-spend-permissions.md`**:
- Corrected "an wallet" to "a wallet" for proper grammatical usage.
2. **Link Updates**:
- **`decomissioning-public-geth-archive-snapshots.md`**:
- Updated GitHub URL to point to the correct Base node repository.
- **`oracles.md`**:
- Updated Supra documentation link to the latest valid URL.
**Notes to …
> Fix Typos and Update Links in Documentation

- apps/web/src/data/ecosystem.json
This pull request contains changes to improve clarity, correctness and structure.
**Description correction:**
Corrected `focussed`" to `focused`
Please review the changes and let me know if any additional changes are needed.
> typo improvement

- apps/base-docs/tutorials/docs/2_ock-fund-tutorial.md
Corrected `set up an account on with` to `set up an account with`. The extra word is `on`
> Improve Grammar in Docs

- apps/web/src/data/ecosystem.json
**What changed?**
Fixed grammatical errors in descriptions:
- Replaced `it's` with `its` in Equalizer's description to correct improper contraction usage.
- Changed `optimises` to `optimizes` in Orbiter Finance's description to align with American English spelling.
**Why?**
These changes were made to improve grammatical accuracy and maintain consistency in language usage throughout the document.
*
*Notes to reviewers:**
Please verify that the changes align with the project's language style guide and ensure no additional inconsistencies exist.
The JSON file was validated for syntax correctness, and the updated descriptions were reviewed to ensure they align with the intended meaning.
> Fix Grammatical Errors in Descriptions for Equalizer and Orbiter Finance

- README.md
Adds a link to the requirements mentioned in the Base editorial style guide for ecosystem submissions
N/A
Localhost
> docs(README): Add link to Base editorial style guide

- .github/ISSUE_TEMPLATE/docs_request.yml
The description for the other field could be reworded slightly for clarity and to avoid an awkward sentence structure.
> Grammar in "Additional context" Description

- apps/base-docs/tutorials/docs/2_paymaster-sponsor-using-wagi.md
Corrected `Passskey` to `Passkey`
> fix: typos

- apps/web/src/components/Basenames/RegistrationSearchInput/index.tsx
- apps/web/src/hooks/useAlternativeNameSuggestions.ts
> Test mobile selection fix

- apps/web/src/hooks/useWriteContractsWithLogs.ts
This pull request addresses a typographical error in the `useWriteContractsWithLogs.ts` file. The word "Successfull" has been corrected to "Successful."
- Fixed the typo from "Successfull" to "Successful" in a comment.
> typo fix useWriteContractsWithLogs.ts

- apps/web/src/data/ecosystem.json
> update Alien Base

- apps/web/src/components/GetStarted/GetInvolved.tsx
* added Base Community Leaders link to `/build` Get Involved section
> chore: add base community leaders

- apps/web/src/components/GetStarted/GetInvolved.tsx
* updated GetInvolved build card
> chore: choreupdate build card

- apps/web/app/(base-org)/jobs/JobsScript.tsx
- apps/web/app/(base-org)/jobs/page.tsx
* added jobs script to jobs page
> chore: add jobs script

- apps/base-docs/docs/why-base.md
Added "Why Base?" to Base Docs
New guide on Why Base
> add why base guide to docs site

- apps/base-docs/docs/using-base.md
- apps/base-docs/docs/why-base.md
- apps/base-docs/sidebars.js
updated `sidebar.js` to include Why Base article
> Update sidebar to include Why Base

- README.md
Because "will becoming" is incorrect. The grammatically correct phrase is "will be coming."
> incorrect README.md

- .eslintrc.js
> spelling issue .eslintrc.js

- libs/base-ui/contexts/Analytics.tsx
a AnalyticsProvider - an AnalyticsProvider
> error article Analytics.tsx

- apps/web/next-env.d.ts
- apps/web/next.config.js
* updated reference in csp for lottiefiles handling
> fix: update lottie csp

- apps/web/next-env.d.ts
- apps/web/next.config.js
* add another version to csp for lottie 
> fix: add csp

- apps/web/.gitignore
- apps/web/app/(basenames)/api/basenames/[name]/assets/cardImage.svg/route.tsx
Migrates problematic API to app router and fixes font import path
Co-authored by @kirkas
Co-authored by @brendan-defi
> fix: fix API route in Next 15

- package.json
- yarn.lock
> fix: fix build

- apps/web/src/components/ClientAnalyticsScript/ClientAnalyticsScript.tsx
* Add Google Analytics to baseweb
> add google analytics

- .gitignore
- apps/web/next.config.js
> fix: update CSP to allow Google tag 

- apps/web/next.config.js
https://developers.google.com/tag-platform/security/guides/csp
> fix: update CSP for Google

- apps/web/app/layout.tsx
- apps/web/next.config.js
> fix: fix CSP

- apps/base-docs/Dockerfile
* updated dockerfile final command to serve the page
> fix: update docs dockerfile for vocs

- apps/web/src/components/Builders/Landing/Apps/index.tsx
- apps/web/src/components/Builders/Landing/Hero/SearchModal.tsx
- apps/web/src/components/Builders/Shared/LiveDemo/constants.ts
- apps/web/src/components/Builders/Shared/LiveDemo/index.tsx
- apps/web/src/components/Builders/SmartWallet/Customers.tsx
* smart wallet
* remove moshicam from SW apps
* remove frenpet as link is broken
* onchainkit
* update wallet component with custom avatar to handle image source
> fix: sw and ock issues

- apps/web/middleware.ts
* fix cookie policy link
locally
> fix: cookie policy link

- apps/base-docs/docs/pages/api/_health.mdx
- apps/base-docs/docs/public/serve.json
- apps/base-docs/vite.config.ts
> fix: add health check for CD

- apps/base-docs/docs/pages/builderkits/onchainkit/earn/earn.mdx
- apps/base-docs/docs/pages/builderkits/onchainkit/earn/types.mdx
- apps/base-docs/docs/pages/builderkits/onchainkit/transaction/transaction.mdx
- apps/base-docs/docs/pages/builderkits/onchainkit/transaction/types.mdx
> docs: add `isSponsored` prop to `Earn` docs

- apps/base-docs/docs/contexts/CookieBannerWrapper.tsx
- apps/base-docs/docs/pages/builderkits/onchainkit/checkout/checkout.mdx
- apps/base-docs/docs/pages/builderkits/onchainkit/identity/avatar.mdx
- apps/base-docs/docs/pages/builderkits/onchainkit/identity/badge.mdx
- apps/base-docs/docs/pages/builderkits/onchainkit/identity/identity.mdx
- apps/base-docs/docs/pages/builderkits/onchainkit/identity/name.mdx
- apps/base-docs/docs/pages/builderkits/onchainkit/identity/socials.mdx
- apps/base-docs/docs/pages/builderkits/onchainkit/installation/nextjs.mdx
- apps/base-docs/docs/pages/builderkits/onchainkit/installation/remix.mdx
- apps/base-docs/docs/pages/builderkits/onchainkit/mint/nft-card.mdx
- apps/base-docs/docs/pages/builderkits/onchainkit/mint/nft-mint-card.mdx
- apps/base-docs/docs/pages/builderkits/onchainkit/swap/swap-settings.mdx
- apps/base-docs/docs/pages/builderkits/onchainkit/token/token-search.mdx
- apps/base-docs/docs/pages/builderkits/onchainkit/token/token-select-dropdown.mdx
- apps/base-docs/docs/pages/builderkits/onchainkit/wallet/wallet-dropdown-basename.mdx
- apps/base-docs/docs/pages/builderkits/onchainkit/wallet/wallet-dropdown-disconnect.mdx
- apps/base-docs/docs/pages/builderkits/onchainkit/wallet/wallet-dropdown-fund-link.mdx
- apps/base-docs/docs/pages/builderkits/onchainkit/wallet/wallet-dropdown-link.mdx
- apps/base-docs/docs/pages/builderkits/onchainkit/wallet/wallet-island.mdx
- apps/base-docs/docs/pages/builderkits/onchainkit/wallet/wallet.mdx
- apps/base-docs/docs/pages/cookbook/use-case-guides/transactions.mdx
- apps/base-docs/docs/pages/identity/smart-wallet/guides/siwe.mdx
- apps/base-docs/docs/pages/use-cases/decentralize-social-app.mdx
- yarn.lock
* removed invalid twoslash code focus directives
locally
> fix: code highlighting

- apps/base-docs/package.json
- apps/web/package.json
- yarn.lock
bump OnchainKit to the latest version
> OnchainKit Docs: Latest

- apps/web/src/components/Builders/MiniKit/Hero.tsx
* corrected minikit cta (removed extraneous dash)
> fix: minikit cta

- apps/web/app/(base-org)/resources/page.tsx
* updated metadata on resource page
> trivial: resource page metadata

- apps/base-docs/docs/pages/identity/smart-wallet/guides/paymasters.mdx
- apps/base-docs/sidebar.ts
Updated the twoslash code blocks to expect the import error so it renders properly 
This is a short term resolution of the broken docs. Long term we need to consider updating the doc for accuracy with the latest from permissionless.js, but thats out of scope for this fix
Running locally
> Fix broken paymaster doc

- apps/web/src/components/GetStarted/GetNoticed.tsx
Tile numbering required update following removal of OCN tile
-
-
> Fixed Tile Numbering

- apps/base-docs/docs/components/App.tsx
- apps/base-docs/docs/pages/builderkits/onchainkit/appchain/bridge.mdx
- apps/base-docs/docs/pages/builderkits/onchainkit/appchain/types.mdx
- apps/base-docs/sidebar.ts
add documentation for `AppchainBridge`
`hooks` will be added to the docs in a later PR
ran locally and vercel preview
> docs: `AppchainBridge`

- apps/base-docs/docs/public/serve.json
- apps/web/middleware.ts
- apps/web/next.config.js
* added link redirects
locally
> fix: link redirects

- apps/base-docs/docs/pages/builderkits/onchainkit/guides/build-onchain-apps.mdx
- apps/base-docs/docs/pages/builderkits/onchainkit/guides/troubleshooting.mdx
- apps/base-docs/docs/pages/builderkits/onchainkit/paymaster/gasless-transactions-with-paymaster.mdx
- apps/base-docs/docs/pages/cookbook/account-abstraction/gasless-transactions-with-paymaster.mdx
- apps/base-docs/docs/pages/identity/wallet-sdk/sw-setup.mdx
- apps/base-docs/docs/pages/use-cases/go-gasless.mdx
> fix: fix Discord invite links

- apps/base-docs/docs/contexts/CookieBannerWrapper.tsx
- apps/base-docs/docs/public/serve.json
- apps/web/middleware.ts
* added redirects for docs-site hierarchy changes
in dev env: 
https://github.com/user-attachments/assets/8b38e22a-5fdc-43ec-9a8c-e6354dd08d2d
> fix: more redirects

- apps/web/src/components/base-org/shared/TopNavigation/BuildersDropdown.tsx
- apps/web/src/components/base-org/shared/TopNavigation/index.tsx
> fix: hackerone link

- apps/web/middleware.ts
- apps/web/next.config.js
* fixed job link redirects to use url.searchParams
> fix: jobs links redirects

- apps/base-docs/README.md
> fix: update base-docs readme

- apps/base-docs/docs/pages/learn/arrays/arrays-exercise.md
- apps/base-docs/docs/pages/learn/control-structures/control-structures-exercise.md
- apps/base-docs/docs/pages/learn/deployment-to-testnet/deployment-to-testnet-exercise.md
- apps/base-docs/docs/pages/learn/erc-20-token/erc-20-exercise.md
- apps/base-docs/docs/pages/learn/error-triage/error-triage-exercise.md
- apps/base-docs/docs/pages/learn/imports/imports-exercise.md
- apps/base-docs/docs/pages/learn/inheritance/inheritance-exercise.md
- apps/base-docs/docs/pages/learn/mappings/mappings-exercise.md
- apps/base-docs/docs/pages/learn/minimal-tokens/minimal-tokens-exercise.md
- apps/base-docs/docs/pages/learn/new-keyword/new-keyword-exercise.md
- apps/base-docs/docs/pages/learn/storage/storage-exercise.md
- apps/base-docs/docs/pages/learn/structs/structs-exercise.md
Updated Basic Math link and Deploying to a Testnet link
> docs: update links to `deployment-to-testnet-exercise.md`

- apps/base-docs/docs/pages/identity/smart-wallet/guides/sub-accounts/creating-sub-accounts.mdx
- apps/base-docs/docs/pages/identity/smart-wallet/guides/sub-accounts/incorporate-spend-permissions.mdx
- apps/base-docs/docs/pages/identity/smart-wallet/guides/sub-accounts/overview.mdx
- apps/base-docs/docs/pages/identity/smart-wallet/guides/sub-accounts/setup.mdx
- apps/base-docs/docs/pages/identity/smart-wallet/guides/sub-accounts/using-sub-accounts.mdx
Add a link to the sub account guide repo for developers who want to skip ahead and just get the final code
> update sub account guide

- apps/base-docs/docs/public/serve.json
* added redirects for network faucets and deploy with foundry
> fix: docs links

- apps/base-docs/docs/pages/buildathons/2025-02-flash.mdx
- apps/base-docs/docs/pages/identity/smart-wallet/sdk/CoinbaseWalletProvider/request/Overview.mdx
**Fixed minor typos in documentation:**
- Corrected `freindly` to `friendly` in `buildathons/2025-02-flash.mdx`
- Corrected `handled` to `handled` in `CoinbaseWalletProvider` documentation
These changes improve readability and consistency of the documentation.
> Docs: Fix spelling errors in mobile app and request handling descriptions

- apps/base-docs/docs/pages/chain/bridges-mainnet.mdx
- apps/base-docs/sidebar.ts
* added more info to bridges doc
* added bridges doc to sidebar
locally
> chore: update bridges

- apps/base-docs/docs/pages/use-cases/launch-ai-agents.mdx
- apps/base-docs/docs/pages/use-cases/onboard-any-user.mdx
This PR includes the following changes:
- Fixed typo in launch-ai-agents.mdx: "prefered" -> "preferred"
- Minor formatting improvements in documentation files
- Updated text styling in onboard-any-user.mdx
These changes improve documentation readability and correct spelling errors.
> Fix typo in documentation

- apps/base-docs/docs/pages/builderkits/onchainkit/paymaster/quickstart-headless.mdx
- apps/base-docs/docs/pages/identity/mobile-wallet-protocol/spec-overview.mdx
This PR enhances the documentation clarity by:
1. Fixing typos and improving text formatting in mobile wallet protocol specification:
- Corrected `univeral` to `universal`
- Enhanced description of decentralized features
2. Improving text formatting in quickstart guide:
- Corrected `exsiting` to `existing`
These changes make the documentation more professional and easier to read.
> Documentation: Improve readability and fix typos

- apps/base-docs/docs/pages/cookbook/client-side-development/introduction-to-providers.mdx
Fix incorrect link for easy navigation
> Fix incorrect link

- apps/base-docs/docs/pages/cookbook/token-gating/gate-irl-events-with-nouns.mdx
> Updated links for docs

- apps/web/src/components/ThreeHero/models.tsx
**What changed? 
rename function
> fix: rename function `controlerModel`  to  `controllerModel`

- apps/web/next.config.js
> fix: fix `frame-src` to enable WalletConnect

- apps/web/src/components/Basenames/UsernameProfileCasts/index.tsx
- apps/web/src/components/NeynarCast/index.tsx
- apps/web/src/components/NeynarFrame/index.tsx
- apps/web/src/utils/frames.ts
> fix: fix typos in Neynar components and types

- apps/web/src/data/ecosystem.json
> Zarp stablecoin link fix

- apps/base-docs/docs/pages/builderkits/onchainkit/guides/troubleshooting.mdx
> docs: update OnchainKit troubleshooting docs with note regarding React Native support

- apps/base-docs/docs/pages/identity/smart-wallet/guides/sub-accounts/overview.mdx
- apps/base-docs/docs/pages/identity/smart-wallet/sdk/CoinbaseWalletProvider/request/wallet_addSubAccount.mdx
Update the ERC number 
Smart wallet docs update
Manually
> update erc number

- apps/base-docs/docs/pages/builderkits/onchainkit/fund/fetch-onramp-transaction-status.mdx
> fix: fix JSON syntax error

- .github/PULL_REQUEST_TEMPLATE.md
* updated PR template to cue the testing of multiple base.org pages for every PR
> feat: update default PR template

- apps/web/app/(base-org)/builders/base-appchains/page.tsx
- apps/web/src/components/Builders/Appchains/FAQ.tsx
- Added FAQs to the Appchain product page and a link out to CDP Appchain FAQ
- Do not merge until Appchain FAQ is merged on CDP
- Mobile & desktop locally
> added FAQs to appchain page

- apps/web/src/components/Builders/MiniKit/Hero.tsx
- apps/web/src/components/Builders/MiniKit/SupportedPlatforms.tsx
* updated minikit installation command
locally
> chore: update minikit installation command

- apps/base-docs/docs/pages/builderkits/minikit/getting-started.mdx
- apps/base-docs/sidebar.ts
- Add MiniKit to Vocs `sidebar.ts`
- [] base.org
- [] base.org/build
> Minikit docs

- apps/base-docs/docs/pages/builderkits/onchainkit/use-coinbase-smart-wallet-and-eoas.mdx
- apps/base-docs/docs/pages/cookbook/client-side-development/introduction-to-providers.mdx
- apps/base-docs/docs/pages/cookbook/nfts/complex-onchain-nfts.mdx
Fix Broken Documentation Links
> Fix Broken Documentation Links

- apps/web/app/(base-org)/builders/minikit/page.tsx
- apps/web/src/components/Builders/MiniKit/Hero.tsx
* udpated minikit cta
BaseWeb
- [] base.org
BaseDocs
> fix: update minikit cta

- apps/base-docs/docs/pages/identity/smart-wallet/sdk/CoinbaseWalletProvider/request/request-overview.mdx
> Minor documentation improvements: typo fix

- apps/base-docs/docs/pages/cookbook/account-abstraction/account-abstraction-on-base-using-particle-network.mdx
> Fix: links

- apps/base-docs/docs/pages/builderkits/onchainkit/use-coinbase-smart-wallet-and-eoas.mdx
using [Wallet] - using the [Wallet]
a the end - at the end
> fix correction use-coinbase-smart-wallet-and-eoas.mdx

- apps/base-docs/docs/pages/identity/smart-wallet/guides/spend-permissions/overview.mdx
> typos overview.mdx

- apps/base-docs/docs/pages/identity/smart-wallet/guides/erc20-paymasters.mdx
> deleted duplicate erc20-paymasters.mdx

- apps/base-docs/docs/pages/identity/smart-wallet/sdk/CoinbaseWalletProvider/request/Overview.mdx
> fix `make make` Overview.mdx

- apps/base-docs/docs/pages/builderkits/onchainkit/fund/fund-card.mdx
BaseWeb
- [] base.org
BaseDocs
> chore: update fund card docs

- apps/base-docs/docs/pages/cookbook/smart-contract-development/foundry/setup-with-base.mdx
> error in setup-with-base.mdx

- apps/base-docs/docs/pages/chain/why-base.md
eligible for Optimism `RPFG` 
eligible for Optimism `RPGF`
> fix issue why-base.md

- apps/base-docs/docs/pages/builderkits/onchainkit/paymaster/gasless-transactions-with-paymaster.mdx
slug: /gasless-transaction-`wtih`-paymaster - slug: /gasless-transaction-`with`-paymaster
> typo gasless-transactions-with-paymaster.mdx

- apps/base-docs/docs/pages/builderkits/onchainkit/paymaster/errors.mdx
> fix typo errors.mdx

- apps/base-docs/docs/pages/cookbook/token-gating/gate-irl-events-with-nouns.mdx
- apps/base-docs/docs/pages/cookbook/use-case-guides/deploy-to-vercel.mdx
- apps/base-docs/docs/pages/cookbook/use-case-guides/finance/access-real-time-asset-data-pyth-price-feeds.mdx
> Fix broken links

- apps/base-docs/docs/pages/cookbook/nfts/complex-onchain-nfts.mdx
> Update link complex-onchain-nfts.mdx

- apps/base-docs/docs/pages/builderkits/onchainkit/guides/build-onchain-apps.mdx
> incorrect build-onchain-apps.mdx

- apps/base-docs/docs/pages/builderkits/onchainkit/fund/fetch-onramp-options.mdx
> fix correct

- apps/base-docs/docs/pages/builderkits/onchainkit/wallet/wallet-island.mdx
- apps/base-docs/docs/pages/builderkits/onchainkit/wallet/wallet.mdx
- apps/web/src/components/Builders/Shared/LiveDemo/constants.ts
- apps/web/src/components/Builders/Shared/LiveDemo/index.tsx
BaseWeb
- [] base.org
BaseDocs
> chore: update ock component docs

- apps/base-docs/docs/pages/chain/base-contracts.mdx
A handful of Base contract addresses were out-of-date or incorrect. This PR updates all necessary addresses.
BaseWeb
- [] base.org
BaseDocs
> (chore): fix incorrect contract addresses

- apps/web/app/(base-org)/builders/minikit/page.tsx
- apps/web/app/(base-org)/builders/smart-wallet/page.tsx
- apps/web/src/components/Builders/MiniKit/Hero.tsx
- apps/web/src/components/Builders/Onchainkit/CtaBanner.tsx
- apps/web/src/components/Builders/Shared/LiveDemo/index.tsx
Added
- OnchainKit
- MiniKit
- Smart Wallet
BaseWeb
- [] base.org
BaseDocs
> add product-specific llms.txt to product pages

- apps/base-docs/docs/pages/builderkits/onchainkit/wallet/types.mdx
- apps/base-docs/docs/pages/builderkits/onchainkit/wallet/wallet-island.mdx
- apps/base-docs/docs/pages/builderkits/onchainkit/wallet/wallet.mdx
- apps/web/src/components/Basenames/RegistrationForm/RegistrationButton.tsx
- apps/web/src/components/Builders/Shared/LiveDemo/constants.ts
- apps/web/src/components/Builders/Shared/LiveDemo/index.tsx
- apps/web/src/components/ConnectWalletButton/ConnectWalletButton.tsx
BaseWeb
- [] base.org
BaseDocs
> chore: update OCK ConnectWallet docs

- apps/base-docs/docs/pages/cookbook/IPFS/deploy-with-fleek.mdx
- apps/base-docs/docs/pages/cookbook/account-abstraction/account-abstraction-on-base-using-biconomy.mdx
- apps/base-docs/docs/pages/cookbook/client-side-development/introduction-to-providers.mdx
> Fixing important links for smooth understanding of documentation 

- apps/base-docs/docs/pages/cookbook/use-case-guides/deploy-to-vercel.mdx
> fix vercel deploy-to-vercel.mdx

- apps/base-docs/docs/pages/identity/smart-wallet/concepts/features/built-in/networks.mdx
Adding Lordchain as per: https://x.com/Nick_Prince12/status/1910751226817552460
BaseDocs
> Update Smart Wallet list of Networks

- apps/base-docs/sidebar.ts
Removing "request" as it's not the right syntax and renaming sub-section.
BaseDocs
> Removing request from Coinbase Wallet SDK Technical Reference

- apps/base-docs/docs/pages/chain/security/app-blocklist.md
Updated existing article contents according to latest agreed upon version
Reference: https://docs.google.com/document/d/1A-uBB0a_WpeMrHjo6Y9phk-hsVHQ4NsBMNZc9aqGCsU/edit?tab=t.0
Locally
BaseDocs
> docs: Update blocklist article

- apps/base-docs/sidebar.ts
Fixing a casing issue at the Smart Wallet sidebar
BaseDocs
> Add a small patch to sidebar

- apps/base-docs/docs/pages/identity/smart-wallet/examples/coin-a-joke-app.mdx
Adding support for Sub Accounts to the example page
BaseDocs
> Add sub accounts to Coin your Bangers example

- apps/base-docs/docs/pages/chain/oracles.mdx
BaseWeb
- [] base.org
BaseDocs
> Fixed a link

- apps/base-docs/docs/pages/cookbook/client-side-development/viem.mdx
- apps/base-docs/docs/pages/cookbook/client-side-development/web3.mdx
Reopened pr to fix issue with link in 
https://github.com/base/web/pull/1953#
> Viem link fix

- apps/base-docs/README.md
-revised to give a more formal yet simple tone
BaseWeb
- [] base.org
BaseDocs
> Revise README.md

- apps/base-docs/docs/pages/identity/wallet-sdk/switching-chains.mdx
> fix err switching-chains.mdx

- apps/base-docs/docs/pages/learn/storage/storage-exercise.mdx
BaseWeb
- [] base.org
BaseDocs
> Fix :Update storage-exercise.mdx

- apps/base-docs/docs/pages/chain/network-faucets.mdx
Adding a free Chainstack faucet
By claiming the Base Sepolia ETH through the faucet.
BaseWeb
- [] base.org
BaseDocs
> Add Chainstack faucet

- apps/base-docs/docs/footer.tsx
Hi Devs. nothing fancy, just got rid of an unnecessary TODO comment
> fix: got rid of redundant comment

- apps/base-docs/docs/pages/identity/wallet-sdk/tracking-assets.mdx
hey! I fixed error in `tracking-assets.mdx`
alphanumerical - alphanumeric
> fix error tracking-assets.mdx

- apps/base-docs/docs/pages/identity/smart-wallet/guides/sub-accounts/setup.mdx
- apps/base-docs/docs/pages/identity/smart-wallet/guides/sub-accounts/using-sub-accounts.mdx
Small patches to the Sub Accounts guide
BaseDocs
> Fix broken link and using sub accounts page

- apps/web/src/data/ecosystem.json
- apps/web/src/data/ecosystem/aviator-arcade/metadata.json
- apps/web/src/scripts/buildEcosystem.ts
Updating the base.org/ecosystem page
N/A
Localhost
BaseWeb
BaseDocs
> web(ecosystem): Update with latest editions for week ended

- apps/base-docs/docs/pages/learn/arrays/arrays-exercise.mdx
- apps/base-docs/docs/pages/quickstart.mdx
BaseWeb
- [] base.org
BaseDocs
> Fixed a link 

- apps/base-docs/docs/pages/builderkits/minikit/existing-app-integration.mdx
- apps/base-docs/docs/pages/builderkits/minikit/quickstart.mdx
Fixed minikit import and cdp links
BaseWeb
- [] base.org
BaseDocs
> fixed links and imports

- apps/web/app/(base-org)/builders/onchainkit/page.tsx
* removed onchainkit testimonials
BaseWeb
BaseDocs
> chore: remove onchainkit testimonials

- apps/base-docs/docs/pages/wallet-app/beta-faq.mdx
- apps/base-docs/docs/pages/wallet-app/mini-apps.mdx
- apps/base-docs/sidebar.ts
Added coinbase wallet beta section
> added beta

- apps/base-docs/sidebar.ts
BaseWeb
- [] base.org
BaseDocs
> Add profiles to sidebar

- apps/base-docs/docs/pages/identity/smart-wallet/guides/profiles.mdx
BaseWeb
- [] base.org
BaseDocs
> Smart Wallet Profiles: Moving from dev env to prod

- apps/web/src/data/ecosystem/arkham/metadata.json
Change Arkham URL to updated address
BaseWeb
- [] base.org
> Update Arkham URL

- apps/web/app/AppProviders.tsx
- apps/web/e2e/appSession.ts
- apps/web/src/components/Banner/PolicyBanner.tsx
- apps/web/tailwind.config.js
Adding privacy policy banner to base.org
https://github.com/user-attachments/assets/3b695da7-2e50-4a04-b395-ff06f2659d82
BaseWeb
- [] base.org
> feat: privacy banner

- apps/web/app/(base-org)/layout.tsx
- apps/web/src/components/Layout/Footer/Footer.tsx
- apps/web/src/components/base-org/BasePay/BuyRealThings.tsx
- apps/web/src/components/base-org/BasePay/Earn.tsx
- apps/web/src/components/base-org/BasePay/OneClickCheckout.tsx
- apps/web/src/components/base-org/BasePay/SpendCrypto.tsx
Some simple copy/link changes
BaseWeb
- [] base.org
> feat: copy/link changes

- apps/web/src/components/Brand/Hero/Background/scene.tsx
- apps/web/src/components/Brand/Hero/Background/shaders/useAsciiPattern.ts
- apps/web/src/components/WebGL/Scenes/AsciiFluidScene.tsx
> Basement: Improve hero shader's render resolution & prevent color patterns from mixing

- apps/web/src/components/Layout/UsernameNav/index.tsx
https://github.com/user-attachments/assets/a3904d71-a3da-44d4-b9a1-82f12e9c163f
BaseWeb
- [] base.org
> [feat] Add new design to sidebar on names pages

- apps/web/app/CryptoProviders.tsx
- apps/web/package.json
- package.json
- yarn.lock
> [chore] Bump onchainkit version

- apps/web/app/CryptoProviders.tsx
- apps/web/package.json
- package.json
- yarn.lock
Reverts base/web#2555 which causes all name/<valid-emojis-basename> to fail. Reverting until we figure out the root cause
> Revert "[chore] Bump onchainkit version"

- apps/web/src/components/Basenames/RegistrationFaq/index.tsx
> feat(BA-2843): Remove text about cb1 discounted renewals

- apps/web/src/components/Resources/section/Fund/index.tsx
- apps/web/src/components/Resources/section/GetInvolved/index.tsx
- apps/web/src/components/Resources/section/GetNoticed/index.tsx
- apps/web/src/components/Resources/section/StartBuilding/index.tsx
This PR updates the Resources page with improved copy and updated links across all sections. All changes have been linted with no errors.
Locally
BaseWeb
- [] base.org
> Update Resources page content and links
