base/web

apps/web/next.config.js
I added another CCA Lite domain to the CSP. This domain was not causing CSP errors in local dev, but once deployed to prod, the following was logged in the console:
N/A
I opened a PR (but didn't merge) in protocols/base-web and validated with a dev deployment that the new CSP fixed the error. Looks to be working fine in [dev](https://base.cbhq.net/).
=> Add CCA Lite domain to CSP

apps/base-docs/server.js
I added another CCA Lite domain to the CSP. This domain was not causing CSP errors in local dev, but once deployed to prod, the following was logged in the console:
N/A
I opened a PR (but didn't merge) in protocols/base-web and validated with a dev deployment that the new Docs CSP fixed the error. Looks to be working fine in [dev](https://base-docs.cbhq.net/using-base).
=> Add CCA Lite domains to Base Docs CSP.

apps/base-docs/docs/building-with-base/guides/run-a-base-node.md
**Note:** EBS callout is due to multiple reports in https://github.com/base-org/node/issues/105
N/A
Localhost preview
=> Add hardware requirements, snapshots instrux and EBS callout to Node guide

apps/web/src/components/JoinTheCommunity/JoinTheCommunity.tsx
We recently changed Ecosystem images from PNG to WEBP which
inadvertently broke this component.
Build on localhost
=> fix(homepage): query community builder webp images

apps/base-docs/server.js, apps/web/next.config.js
Removed the cbhq analytics URL from the Web and Docs CSP. This was only needed to get the CSP working in local dev, but the URL is not necessary for analytics to work in prod and should not be committed to the codebase.
N/A
I removed the cbhq URL in [this test PR](https://github.cbhq.net/protocols/base-web/pull/490/files) to protocols/base-web to validate that analytics still works in the deployed Web and Docs apps with that URL removed from the CSP.
=> Remove cbhq URL from CSP

apps/web/src/components/Bootcamp/WhatsIncluded.tsx
Small nit, replaces a backtick that should be an apostrophe
N/A
Localhost
=> chore(bootcamp): replace backtick with apostrophe

apps/base-docs/src/theme/SearchBar.jsx, apps/base-docs/src/theme/kbar.module.css
Fix search box that is overflowing into logo on handheld devices in docs
Localhost
=> fix(doc search): Refactor search box for optimal display on handheld devices

apps/bridge/pages/transactions.tsx, apps/bridge/src/components/Transactions/WithdrawalRow/ProveWithdrawalButton.tsx, apps/bridge/src/components/Transactions/WithdrawalRow/WithdrawalRow.tsx, apps/bridge/src/utils/hooks/useBlockNumberOfLatestL2OutputProposal.ts, apps/bridge/src/utils/hooks/usePrepareProveWithdrawal.ts, apps/bridge/src/utils/hooks/useWithdrawalStatus.ts
generate withdrawal proofs using latest l2 block. this is valid and does not require archive nodes
=> generate withdrawal proofs using latest l2 block

.github/workflows/update-algolia.yml, apps/base-docs/algolia.json
We're preparing to replace the existing docs search with an Algolia-powered search. This Github Action (emulating [this cloud docs example](https://github.com/bisontrails/cloud-docs/blob/f92053379575629b461f9c84159db01b1b2e6e08/.github/workflows/update-algolia.yml)) will crawl docs.base.org following its sitemap and using the selectors defined in the algolia.json config file.
N/A
We'll be testing the action once it's on master.
=> Add Algolia indexer Github Action and config.

apps/base-docs/algolia.json
I'm adopting some settings from the algolia.json file used for docs.cloud.coinbase.com to test if their selector hierarchy gives better search results.
I may end up reverting this PR if the resulting index is not an improvement.
**How has it been tested?**\
This PR will only update the config used by the Algolia Github Action. Once this is merged with master, I'll be locally testing a new search UI.
=> Update config for algolia index docs crawler.

apps/base-docs/docs/building-with-base/guides/run-a-base-node.md
instructions seem outdated. `OP_NODE_L1_ETH_RPC` is no longer configurable in `docker-compose.yml`
none
compiled the md file
=> docs: update "run a base node" instructions

apps/web/src/components/Layout/Nav/DesktopNav.tsx, apps/web/src/components/Layout/Nav/MobileMenu.tsx
Sangita designed the new nav and asked for the external link icons to be removed.
**Before**
**After**
N/A
Removed the icons and checked results locally.
=> Remove external link icons from nav.

apps/base-docs/docusaurus.d.ts, apps/base-docs/src/components/DocFeedback/FeedbackModal.tsx, apps/base-docs/src/components/DocFeedback/index.tsx, apps/base-docs/src/components/DocFeedback/styles.module.css, apps/base-docs/src/components/Icon/index.tsx, apps/base-docs/src/components/Modal/ModalBody.tsx, apps/base-docs/src/components/Modal/ModalFooter.tsx, apps/base-docs/src/components/Modal/ModalHeader.tsx, apps/base-docs/src/components/Modal/index.tsx, apps/base-docs/src/components/Modal/styles.module.css, apps/base-docs/src/theme/DocItem/Content/index.js
Added thumbs up and down buttons so users can submit feedback indicating if a doc was helpful or not. Added modal form so users can submit a specific reason for why a doc was helpful or not.
**Before**
**After**
I [swizzled](https://docusaurus.io/docs/swizzling) the DocItem/Content component for this PR, which docusaurus warns is unsafe. But in [this Slack thread](https://coinbase.slack.com/archives/C04CU9E5YTA/p1698266566681439) the team expressed that, as long as minimal changes are made, it should be okay to swizzle this component. I added the DocFeedback component to DocItem/Content and made no other changes.
When running the app locally, CCA debug logs show the `doc_feedback` events are firing correctly, and …
=> Add Doc Feedback UI

apps/bridge/chains.ts
* Using `satisfies Chain[]` lets typescript complain if the provided object doesn't match the expected type
* There are a couple custom props that are not part of `Chain`, so I added a `ChainMetadata` type describing those (otherwise `satisfies Chain[]` would cause typescript to complain about unknown props) 
* Using `as const` slightly improves the devex because each the string literals for each chain can be inferred by typescript and displayed by the IDE
* Running `dev` and `build` without issues
=> improve type safety in chains.ts

apps/bridge/Dockerfile, apps/bridge/Dockerfile.example
* The `apps/bridge` dockerfile used an internal image, and included Base specific config params (ie a Bugsnag API key).
* This PR changes the base image to a public node docker image and removes the Base specific config params
* Tested by building with docker locally using ` docker build -f apps/bridge/Dockerfile .` from the root directory and running with docker afterwards
=> update Dockerfile to use public image and remove base bugsnag params

apps/bridge/next.config.js, apps/bridge/src/wallet/connect.ts
https://chainlist.org/chain/1
Adds `cloudflare-eth` and `llamarpc.com` as additional backup public nodes.
=> Configure additional backup public ETH RPCs

apps/base-docs/src/components/DocFeedback/index.tsx, apps/base-docs/src/utils/initCCA.ts
To ensure more consistent data, trailing slashes are now removed from page paths before CCA logs `pageview` or `doc_feedback` events.
Also removed referrerURL from `src/utils/initCCA.ts` because CCA collects that data without needing to add it as a custom attribute.
Triggered `pageview` and `doc_feedback` events and reviewed local debug logs to confirm the resulting data is correct.
=> Remove Trailing Slashes from CCA Page Path Data

apps/web/src/components/Layout/Nav/MobileMenu.tsx
People were unable to scroll pages after navigating from mobile menu.
Honestly not ideal to use DOM mutations when using React, although admittedly Next makes it hard to get at the <body> tag any other way.
Manually.
=> Remove no-scroll from body upon navigating from MobileMenu

apps/base-docs/base-camp/docs/control-structures/control-structures.md
This is about a single-word swap: `require` instead of `revert`
=> Fix documentation error in the control-structures module

apps/base-docs/src/components/DocFeedback/index.tsx, apps/base-docs/src/components/DocFeedback/styles.module.css, apps/base-docs/src/components/Icon/index.tsx
Added a link to 'edit doc on GitHub' at the bottom of the doc layout.
Opened base camp links and docs links from all directories of the nav to confirm they all lead to the expected file in GitHub.
=> Add Link to Edit Doc on GitHub

apps/base-docs/base-camp/docs/introduction-to-solidity/introduction-to-solidity-overview.md
Closes #127
Added the "y" letter missing: "the contain" now says "they contain"
This fixes the typo that can be seen at https://docs.base.org/base-camp/docs/introduction-to-solidity/introduction-to-solidity-overview/#objectives
Ran `yarn workspace @app/base-docs dev` locally and navigated to http://localhost:3000/base-camp/docs/introduction-to-solidity/introduction-to-solidity-overview#objectives to confirm the sentence is now fixed. Screenshot showing sentence now saying "Describe constraints related to assignment of structs depending on the types they contain":
=> Docs - Fix typo in Smart Contract Development Overview - Add missing y

apps/base-docs/base-camp/docs/erc-20-token/erc-20-token-sbs.md
I´m changing the name of a function referred to in an explanation within the ERC20 token section.
'transfer' instead of '_mint'
=> swap '_mint' for 'transfer'

apps/web/src/data/ecosystem.json
The URL for the drawtech has a typo. The full logo is [drawtechlogo.png](https://github.com/base-org/web/blob/master/apps/web/public/images/partners/drawtechlogo.png)
=> Fix typo in image url for drawtech

apps/base-docs/base-camp/docs/error-triage/error-triage-exercise-source.sol, apps/base-docs/base-camp/docs/error-triage/error-triage-exercise.md
Error triage exercise has a problem that specifies an input of >1000 but tests an input of 1000.
=> Fix error triage instructions to specify >= 1000 for modifier problem

apps/base-docs/docs/tools/block-explorers.md, apps/base-docs/docs/tools/data-indexers.md
Arkham was added to the set of block explorers and data indexers that support Base under tools within the developer docs since it was missing from the respective lists.
Was referred here and advised to submit a PR by the Base team.
Previewed the verbiage and links within my own fork.
=> Update of tools docs with addition of Arkham to block explorers and data indexers

apps/base-docs/base-camp/docs/welcome.md
Add a more concise description to the Base Camp welcome page so that it doesn't appear somewhat duplicated when the link gets shared and the rich snippet appears:
Provides additional context about what Base Camp is.
N/A
Localhost
=> welcome: Add more concise description to Base Camp welcome page

apps/bridge/src/components/Tooltip/Tooltip.tsx, apps/bridge/src/components/WithdrawContainer/TransactionSummaryModal.tsx, apps/bridge/src/components/WithdrawContainer/WithdrawContainer.tsx, apps/bridge/src/utils/hooks/useConversionRate.ts, apps/bridge/src/utils/hooks/useGetWithdrawalFeeEstimates.ts
- added modal that shows before initiating withdrawals with L1 gas estimates for proving & finalizing withdrawal transactions
=> add withdrawal L1 fee info modal

apps/base-docs/docs/tools/node-providers.md
Resolves https://github.com/base-org/web/issues/155
- What:
- Updated 2 node providers (GetBlock, QuickNode) to reflect that they now support Base Sepolia
- Fixed URL typo, where Chainstack was incorrectly linking to GetBlock
- Why:
- Hopefully helpful to builders to see initial support for Base Sepolia testnet
N/A
- Manual review test, checking the updated markdown, low risk
=> Add initial Base Sepolia node providers; Fix URL typo

apps/base-docs/docs/tools/data-indexers.md
What changed? Why?
Added Envio to the data indexers section under tools within the developer docs that support Base. 
Notes to reviewers
Envio was listed on Base Ecosystem as part of a new partnership.
How has it been tested?
Previewed page and links within my own fork
=> add Envio to Data Indexers section

apps/base-docs/base-camp/docs/contracts-and-basic-functions/basic-types.md, apps/base-docs/base-camp/docs/mappings/mappings-sbs.md
_mappings-sbs.md_
Update sentence for clarity from "Another issue with this contract is that public means anyone and everyone with a wallet and funds to pay gas fees." to "Another issue with this contract is that a public function can be called by anyone and everyone with a wallet and funds to pay gas fees." 
_basic-types.md_
Change from 'two and from' to 'to and from'.
=> Update mappings-sbs and basic-types

apps/base-docs/base-camp/docs/error-triage/error-triage.md, apps/base-docs/base-camp/docs/new-keyword/new-keyword-exercise.md, apps/base-docs/base-camp/docs/new-keyword/new-keyword-sbs.md, apps/base-docs/base-camp/docs/storage/simple-storage-sbs.md
typos, caution ui and added missing link to docs.
Caution Section
| Before | After |
| ------------- | ------------- |
| <img width="400" alt="Screenshot 2023-12-05 at 11 39 54 AM" src="https://github.com/base-org/web/assets/60794961/88214c4b-f976-40d0-af1e-09fde0bc4a1f">  | <img width="400" alt="Screenshot 2023-12-05 at 11 42 01 AM" src="https://github.com/base-org/web/assets/60794961/9f80e5d6-802c-45df-8234-59ca6f719b48"> |
=> update error-triage, simple-storage & new-keyword

apps/base-docs/docs/building-with-base/guides/run-a-base-node.md
Update the snapshot URLs and frequency information.
Locally
=> Update snapshot URLs

apps/base-docs/docs/tools/web3.md
web3.js links pointing to v4
this PR closes the issue #185
=> updated web3.js v4 import and link

apps/base-docs/docs/tools/onboarding.md
This PR adds **Particle Network** (Wallet-as-a-Service provider) to onboarding.md alongside Dynamic and Privy. Particle has full support for Base, both on the EOA (traditional account) and AA (smart account) side. The "Particle Network" keyword has also been added to this page.
=> Includes Particle Network within onboarding.md

apps/bridge/package.json, yarn.lock
Check that connect-kit is on version 3.1.10 in the new lockfile.
=> Update to latest wagmi to prevent ledger connect-kit vulnerability

apps/base-docs/docs/tools/data-indexers.md
Added Index Supply's Shovel project to the list of data indexer projects. I think people who are wanting to index data on Base may find Shovel useful.
I ran the project locally and viewed my changes looking for spelling issues or visual anomalies.
=> add shovel to data indexers section

apps/base-docs/docs/building-with-base/guides/using-chainlink-price-feeds.md, apps/base-docs/sidebars.js
Add Chainlink Data Feed guide
N/A
Manually
=> Add Chainlink Data Feeds guide

apps/web/src/data/ecosystem.json
Updated the Seamless URL to include the scheme and full prefix. Fixes broken link on the ecosystem page.
Related https://github.com/base-org/web/issues/215.
n/a
n/a
=> Fix Seamless ecosystem link (#215)

apps/base-docs/docs/tools/hardhat.md
This seeks to introduce support for the Sepolia testnet in the [toolchains guide for Hardhat configurations](https://docs.base.org/tools/hardhat/), since Sepolia is recommended for smart contract development where Goerli was depreciated in Q1 2023 with support terminating in Q4 2023.
The addition includes updating the example `hardhat.config.ts` file to include the Sepolia network settings with the appropriate endpoints on base, but retains Goerli in the hopes that its removal in the documentation can occur in phases.
This change does not remove or alter any existing functionality, and all tests have passed.
=> Add support for Sepolia testnet in documentation

apps/base-docs/docs/building-with-base/guides/cross-chain-with-ccip.md, apps/base-docs/sidebars.js
- Add a new guide for integrating Chainlink CCIP in your Base smart contracts to perform cross-chain messaging and sending tokens to different chains.
N/A
Manually
=> Add cross-chain messaging guide (using Chainlink CCIP)

apps/base-docs/docs/building-with-base/guides/run-a-base-node.md
Update hardware requirements in guide for running a full node (current req = 1.8TB, guide says 1TB)
N/A
Localhost
=> run-a-base-node: Update HDD requirements

apps/base-docs/docs/tools/network-faucets.md
Instead of pointing directly to Base Goerli's faucet, we point to our main faucets page so users can choose between Base Goerli and Base Sepolia themselves
N/A
N/A
=> Update LearnWeb3's faucet link to point to Base Sepolia

apps/web/src/components/Bootcamp/Cost.tsx, apps/web/src/components/Bootcamp/Dates.tsx, apps/web/src/components/Bootcamp/Faq/FaqSidebar.tsx, apps/web/src/components/Bootcamp/Hero.tsx, apps/web/src/components/Bootcamp/HowItWorks/index.tsx
Update bootcamp page to current information
=> Update bootcamp page

apps/base-docs/base-camp/docs/development-tools/overview.md, apps/base-docs/base-camp/docs/events/hardhat-events-sbs.md, apps/base-docs/base-camp/docs/interfaces/calling-another-contract-vid.md, apps/base-docs/base-camp/docs/interfaces/contract-to-contract-interaction.md, apps/base-docs/base-camp/docs/interfaces/intro-to-interfaces-vid.md, apps/base-docs/base-camp/docs/interfaces/testing-the-interface-vid.md, apps/base-docs/base-camp/sidebars.js
Hardhat and Foundry are much easier to setup now than when the first series of Remix videos was created.  In response to feedback from Builder channel, moved them to to the top to make it easier for devs to make an informed choice for which tools to do the content using.
Also moved the evens and interfaces sections to be inside Smart Contract Development, and added a warning that they're done with hardhat, but will still work in Remix.
=> Move Foundry and Hardhat to Top of Basecamp

apps/base-docs/docs/tools/account-abstraction.md, apps/base-docs/docs/tools/onboarding.md
Hi team, this PR adds [WalletKit](https://walletkit.com) to the onboarding and AA docs alongside similar services. WalletKit has full support for Base and generally defaults to it
We're here to answer any questions. Thanks!
=> Add WalletKit to onboarding and AA docs

apps/base-docs/sidebars.js
https://docs.base.org/tools/nft-checkout/
This category was not showing up on the sidebar under "Tools". Committing this change to add it
=> Update sidebars.js to add NFT Checkout

apps/base-docs/base-camp/docs/deployment-to-testnet/deployment-to-base-sepolia-sbs.md
I omitted this line "The Coinbase Wallet has faucets built in. You can find them by clicking Settings -> Developer settings -> Testnet faucets." from the path: web/apps/base-docs/base-camp/docs/deployment-to-testnet/deployment-to-base-sepolia-sbs.md since the information no longer is valid.
This is my first PR. I noticed this issue while reviewing the docs and then checked the issues tab in the repo. It seemed that it was fair game to submit a PR. Forgive me if I didnt anything out of convention, Im just trying to help :)
Its has nothing to do with any functional code and is just a slight adjustment to the docs.
=> Removed outdated line from base camp docs

apps/bridge/src/components/BridgeInput/BridgeInput.tsx
=> [trivial] max button fix for erc20s

apps/base-docs/base-camp/docs/imports/imports-exercise.md
I updated the imports-exercise doc to include a custom-styled block of text to inform @dev about contract verification best practices. 
I kept running into this issue with contract verification where I couldnt verified my contract that included import statements unless I flattened the contract or deployed the "imported" contracts individually and then interacted in my "main" contract via their deployed addresses.
I tried to use concise, yet descriptive language. If this was known to me initially while working on the contract exercises it wouldve saved me time and frustration so thats why I figured the update is valuable. 
Thanks team! Im honored to be able to contribute. 
I tested the changes locally using a …
=>  modified: "imports-exercise.md" to include a custom-styled block of text to inform @dev about contract verification best practices

apps/bridge/src/data/useDeposits.ts, apps/bridge/src/data/useWithdrawals.ts, apps/bridge/src/utils/array/dedupeTransactions.ts, apps/bridge/src/utils/transactions/isETHOrERC20Deposit.ts, apps/bridge/src/utils/transactions/isETHOrERCWithdrawal.ts
In order to get around our problem with the Goerli indexer, but also more robust in general.
Manually.
=> Merge transactions from indexer and explorer for redundancy

apps/base-docs/src/css/root.css
Fix code block line highlighting for dark and light mode.
**Before**
**After**
N/A
Manually
=> Fix code block line highlighting

apps/base-docs/base-camp/docs/arrays/arrays-exercise.md, apps/base-docs/base-camp/docs/control-structures/control-structures-exercise.md, apps/base-docs/base-camp/docs/deployment-to-testnet/deployment-to-testnet-exercise.md, apps/base-docs/base-camp/docs/erc-20-token/erc-20-exercise.md, apps/base-docs/base-camp/docs/erc-721-token/erc-721-exercise.md, apps/base-docs/base-camp/docs/error-triage/error-triage-exercise.md, apps/base-docs/base-camp/docs/imports/imports-exercise.md, apps/base-docs/base-camp/docs/inheritance/inheritance-exercise.md, apps/base-docs/base-camp/docs/mappings/mappings-exercise.md, apps/base-docs/base-camp/docs/minimal-tokens/minimal-tokens-exercise.md, apps/base-docs/base-camp/docs/new-keyword/new-keyword-exercise.md, apps/base-docs/base-camp/docs/storage/storage-exercise.md, apps/base-docs/base-camp/docs/structs/structs-exercise.md, apps/base-docs/docs/building-with-base/guides/nft-minting-frame.md, apps/base-docs/src/pages/base-camp/progress.jsx, apps/base-docs/src/theme/Root.jsx
Remove the option to submit contracts to the Basecamp app on Goerli.  Sepolia only.
Upgrade messaging to reflect this.
=> Remove goerli from basecamp app

apps/web/src/data/ecosystem.json
Added 7 new partners. Edited 1 existing partner.
Corresponding image PR that needs to be merged first. 
=> EcoPage - updated.json

apps/base-docs/docs/building-with-base/guides/cross-chain-with-layerzero.md
Specify OpenZeppelin dependency contracts to be v4 (the version LZ expects)
Not specifying a version will install the latest version (v5) and results in a breaking change. 
N/A
Manually
=> Update OpenZeppelin dependency version for LayerZero V2

apps/base-docs/docs/building-with-base/guides/nft-minting-frame.md
Updated hyperlink for Base Camp in Prerequisites section from https://base.org.camp to https://docs.base.org/base-camp/docs/welcome because the original link was dead.
=> Fix Base Camp hyperlink in Farcaster Frames guide

apps/bridge/src/utils/transactions/explorerTxToBridgeDeposit.ts, apps/bridge/src/utils/transactions/explorerTxToBridgeWithdrawal.ts
Now that we've changed to use `explorer` and `indexer` endpoints as redundant sources of data we no longer use the `explorer` only for CCTP transactions, therefore we need to re-enable handling other transaction types in the explorer transaction transforms.
Manually on the three support tickets.
=> Revert explorerTx transform logic to handle all transaction types

apps/base-docs/src/css/fonts.css
- Resolves #259
- Incorrect font file was referenced in `fonts.css` causing code blocks to render fonts in `sans-serif`
**Screenshots**
|Before|After|
|---|---|
|![before](https://github.com/base-org/web/assets/12480362/956bde6a-9ac0-4286-a4e6-01072f141f98)|![after](https://github.com/base-org/web/assets/12480362/99cf041e-0306-4def-8f02-164aae79bc3e)|
=> fix(docs): ensure code blocks use monofont

apps/bridge/pages/transactions.tsx, apps/bridge/src/components/WarningBanner/WarningBanner.tsx, apps/bridge/tailwind.config.js
Adds a banner to the Transaction page indicating that transactions may take a few minutes to appear
manual inspection
=> Add warning banner on Transactions page

apps/base-docs/docs/building-with-base/base-contracts.md
Add [LegacyERC20ETH](https://basescan.org/address/0xDeadDeAddeAddEAddeadDEaDDEAdDeaDDeAD0000) contract address for [Base Mainnet](https://docs.base.org/base-contracts#base-mainnet) and [Base Testnet (Sepolia)](https://docs.base.org/base-contracts#base-testnet-sepolia) in the documentation. 
This address [is in the Optimism docs](https://docs.optimism.io/chain/addresses#op-mainnet-l2), but was missing from Base documentation
=> Add LegacyERC20ETH contract addresses to Base contracts

apps/bridge/src/components/WithdrawProgressBar/WithdrawProgressBar.tsx
Adding a big ole button to the Transaction page during the withdraw flow to hopefully help people notice the existence of that page.
Manually.
=> Add a more obvious button to the transaction page within withdraw flow

apps/web/package.json, apps/web/pages/index.tsx, yarn.lock
Add basic Farcaster Frame for base.org.
Displays same image as OpenGraph / Twitter (for now)
Displays two buttons (same ones as homepage):
- Read the docs - link to docs
- Bridge assets - link to bridge
N/A
Manually
=> Add a basic Frame to base.org

apps/base-docs/docs/building-with-base/guides/account-abstraction/implementing-the-paymaster.md
Base Paymaster changes likely break the Privy tutorial.  Added a warning until I can fix next week.
=> Add warning about paymaster changes

apps/base-docs/server.js
Add Sepolia RPC and Walletconnect verify to Content Security Policy to fix Base Camp App:
=> Add Sepolia RPC and Walletconnect verify to CSP

apps/web/Dockerfile, apps/web/next.config.js, apps/web/pages/_app.tsx, apps/web/pages/index.tsx, apps/web/pages/jobs.tsx, apps/web/src/components/Home/Hero.tsx, apps/web/src/components/Layout/Footer/Footer.tsx, apps/web/src/components/Layout/Nav/DesktopNav.tsx, apps/web/src/components/Layout/Nav/MobileMenu.tsx, apps/web/src/components/StartBuildingOnBase/StartBuildingOnBase.tsx, apps/web/src/constants.ts, apps/web/src/utils/initCCA.ts
This cleans up the way we get ENV vars, enabling us to use [Automatic Static Optimization](https://nextjs.org/docs/pages/building-your-application/rendering/automatic-static-optimization) to improve performance. It also looks cleaner because we don't have to import `getConfig` everywhere just to use an ENV var.
Tested on a development deployment.
=> Experimentally fix ENV var setup for web

apps/base-docs/docs/building-with-base/guides/advanced-frame-behavior.md, apps/base-docs/docs/building-with-base/guides/deploy-frame-on-vercel.md, apps/base-docs/docs/building-with-base/guides/hyperframes.md, apps/base-docs/docs/building-with-base/guides/linked-minting-frame.md, apps/base-docs/docs/building-with-base/guides/nft-minting-frame.md
Opened Issue (#353)
I have updated the relative paths in the markdown files for the Base Guides to ensure they lead to the correct locations when hosted on the production site. The original relative paths, which worked as expected in a local development environment, resulted in incorrect, nested URLs in the production environment, leading to 404 errors. This update changes the relative paths to root-relative paths, ensuring they function correctly in all environments.
Please review the changes to ensure that the updated URLs correspond to the actual paths where the documents are located. This update is critical for maintaining the integrity of the documentation and ensuring that users can navigate it without encountering dead links.
I've made …
=> Fixing URLs throughout Building with Base Guides (#353)

apps/base-docs/src/components/StudentProgress/index.jsx
- Modified the renderNFTs function in the StudentProgress component to change the order in which the NFTs are displayed, according to issue https://github.com/base-org/web/issues/343#issue-2170026700
- The NFT with key '19' (Imports) is now rendered between the NFTs with keys '8' (Inheritance) and '10' (Errors).
- This change was made to improve the logical flow and grouping of the NFTs based on their topics.
- The rest of the NFTs are still rendered in ascending order based on their keys.
Let me know if you have any suggestions or improvements to make the code more readable or efficient. I considered changing the key of Imports from 19 to 9 as there is none, but decided manually changing the order during rendering was safer.
**How has it been …
=> change positioning of Imports NFT according to issue request

apps/base-docs/src/utils/nft-exercise-data.js
- The error message displayed when connecting to the wrong network while tracking progress with Base Camp has been updated.
- The previous error message was not clear and informative enough, lacking guidance for users on how to resolve the issue.
- The updated error message now clearly communicates that the user is connected to an unsupported network, provides the specific chain ID, and instructs them to connect to the Base Sepolia network.
- Please review the updated error message in the useNFTData function in the nft-exercise-data.js file.
- Ensure that the error message is clear, concise, and actionable, guiding users to switch to the Base Sepolia network.
- Consider any additional feedback or suggestions to further improve the user …
=> Improve Base Camp Invalid chain ID error (#349)

apps/web/middleware.ts, apps/web/src/components/GetConnected/GetConnected.tsx, apps/web/src/components/Layout/Footer/Footer.tsx, apps/web/src/components/Layout/Nav/DesktopNav.tsx, apps/web/src/components/Layout/Nav/MobileMenu.tsx
In some cases CloudFlare isn't redirecting properly to our Discord invite page via base.org/discord; this updates the link so that all users go directly to the invite page
N/A
Localhost
- [X ] No, this PR does not add a new token to the bridge
=> fix(discord): Resolve double redirect to invite

apps/web/middleware.ts
This adds back the route to our middleware to ensure that base.org/discord always works since that link will have propagated throughout the web and we don't want it to 404
Context: #361 
N/A
Localhost
- [X ] No, this PR does not add a new token to the bridge
=> refactor(middleware): Preserve Discord redirect

apps/bridge/README.md
Trivial change to README to enable a deployment on sepolia-bridge.base.org on top of a stale commit.
Stale commit that wasn't deployed:
fb4b13cd0da90eda9216593635d1419167bf63b3
N/A
Localhost
=> chore(README): Force redeploy on sepolia-bridge.base.org

apps/web/src/data/ecosystem.json
There was a typo in Rubyscore's image name in ecosystem.json
=> fix(ecosystem): Typo in partner image name

apps/bridge/pages/_app.tsx
Add a note to the top of bridge.base.org so people are aware of the planned one-hour withdrawal pause on Wednesday.
Localhost
=> feat(bridge): Add planned withdrawal pause note to top of page

apps/base-docs/docs/building-with-base/guides/run-a-base-node.md
mentioned setting `OP_NODE_L1_BEACON` var when starting a base node
=> mention setting `OP_NODE_L1_BEACON`

apps/base-docs/docs/contracts.md
We have Uniswap V3 contracts listed in our docs for mainnet but not testnet; this adds the contracts on testnet also, so that developers can use them for help when building
Contracts for reference: https://docs.uniswap.org/contracts/v3/reference/deployments#sepolia-addresses
Localhost
=> docs(contracts): Add Uniswap V3 Base Sepolia addresses

apps/web/pages/jobs.tsx
Use getStaticProps instead of getServerSideProps to statically render jobs page.
Manually
=> Improve loading experience on jobs page

apps/base-docs/base-camp/docs/frontend-setup/building-an-onchain-app.md, apps/base-docs/base-camp/docs/frontend-setup/overview.md, apps/base-docs/base-camp/docs/frontend-setup/wallet-connectors.md, apps/base-docs/base-camp/docs/reading-and-displaying-data/configuring-useContractRead.md, apps/base-docs/base-camp/docs/reading-and-displaying-data/useAccount.md, apps/base-docs/base-camp/docs/reading-and-displaying-data/useContractRead.md, apps/base-docs/base-camp/docs/writing-to-contracts/useContractWrite.md, apps/base-docs/base-camp/docs/writing-to-contracts/usePrepareContractWrite.md, apps/base-docs/base-camp/sidebars.js
Wagmi V2 is almost 100% breaking for our current frontend guides.  Adding a warning until I can update them.
I didn't use reference-style links to make it easier to add and remove the warning.
- [ x] No, this PR does not add a new token to the bridge
=> Add warning message about v1 to v2 for wagmi

apps/base-docs/base-camp/docs/erc-20-token/erc-20-exercise.md
The ERC-20 exercise tests for an expected revert for `NoTokensHeld` in a way that also triggers `QuorumTooHigh`.  If the submitted contract has the latter before the former, they will incorrectly fail the test.
Added a warning describing this.
=> Add warning about reverts to erc-20 exercise

apps/base-docs/src/css/doc-page.css, apps/base-docs/src/pages/tutorials/styles.module.css
The Tutorials page CSS included an overly broad selector that affected all anchor tags on the site, coloring them white. I made that selector more specific so it only affects anchor tags on the Tutorials page cards. I also adjusted the padding on the Tutorials table of contents to even out the edges of the page layout.
Ran the app locally and confirmed links are rendering blue.
=> Fix Docs Link CSS

apps/base-docs/base-camp/sidebars.js
Outdated link that 404s replaced with the correct tutorial link
Confirmed with @briandoyle81CB in base discord that this is the correct link to use
yes
=> fix: update foundry tutorial link

.github/workflows/update-algolia.yml
Updated the GitHub Action that indexes docs content for Algolia search. Followed the example [here](https://github.com/bisontrails/cloud-docs/blob/main/.github/workflows/update-algolia.yml) from Coinbase Cloud Docs repo.
The Algolia search index currently contains links to /guides content, which has been migrated to /tutorials. Once this GitHub Action is fixed, we can index the new /tutorials content and search results should no longer link to /guides pages with a 404.
=> Update Algolia Indexer Action

apps/base-docs/base-camp/docs/advanced-functions/function-modifiers.md, apps/base-docs/base-camp/docs/arrays/filtering-an-array-sbs.md, apps/base-docs/base-camp/docs/erc-20-token/erc-20-token-sbs.md, apps/base-docs/base-camp/docs/erc-721-token/erc-721-sbs.md, apps/base-docs/base-camp/docs/error-triage/error-triage.md, apps/base-docs/base-camp/docs/hardhat-testing/hardhat-testing-sbs.md, apps/base-docs/base-camp/docs/imports/imports-sbs.md, apps/base-docs/base-camp/docs/inheritance/abstract-contracts-sbs.md, apps/base-docs/base-camp/docs/inheritance/inheritance-sbs.md, apps/base-docs/base-camp/docs/inheritance/multiple-inheritance.md, apps/base-docs/base-camp/docs/mappings/mappings-sbs.md, apps/base-docs/base-camp/docs/minimal-tokens/minimal-token-sbs.md, apps/base-docs/base-camp/docs/new-keyword/new-keyword-sbs.md, apps/base-docs/base-camp/docs/reading-and-displaying-data/useAccount.md, apps/base-docs/base-camp/docs/storage/simple-storage-sbs.md, apps/base-docs/base-camp/docs/structs/structs-sbs.md
Put code solutions to questions in dropdowns to improve the learning experience by hiding the solutions.
An idea by @Valcoholics 
Issue https://github.com/base-org/web/issues/196 
- Base Camp docs improved;
I've put the solutions to questions in dropdowns to improve the learning experience; avoids instantly showing/spoiling the answers.
Went from start to finish through the Base Camp docs to improve the UI/ UX where possible.
UI is tested locally
- [] I've confirmed this token doesn't use a bridge override
- [] I've confirmed this token is an OptimismMintableERC20
=> - Basecamp docs improved;

apps/base-docs/algolia.json
[Previous attempt](https://github.com/base-org/web/pull/399) to fix Algolia crawler resolved some errors/warnings related to outdated dependencies, but the crawler is still finding 0 records to index.
This PR adds the `js_render` and `js_wait` fields to the Algolia crawler config, which addresses the possibility that the crawler is running before page load completes. Docs on these fields [here](https://docsearch.algolia.com/docs/legacy/config-file#js_render-optional).
=> Algolia Crawler Config Update

apps/base-docs/sidebars.js
Removed duplicate `Security` link in sidebar
N/A
Manually
=> Remove duplicate Security link in sidebar

apps/bridge/src/components/Logo/Logo.tsx, apps/web/src/components/Logo/Logo.tsx
Fix invalid logo svg `width` attr
=> fix: Logo svg width error

apps/base-docs/docs/using-base.md, apps/base-docs/docusaurus.config.js, apps/base-docs/src/pages/tutorials/index.jsx, apps/base-docs/tutorials/data.json, apps/web/src/components/Layout/Nav/DesktopNav.tsx, apps/web/src/components/Layout/Nav/MobileMenu.tsx
- Update primary block explorer links to `https://explorer.base.org/`
- Add query parameters to tutorial filtering, enabling the sharing of pre-filtered pages (i.e. `http://docs.base.org/tutorials?tag=frames`)
N/A
Manually
=> Update block explorer links & add query parameters to tutorial filtering

apps/base-docs/tutorials/docs/5_farcaster-cast-actions-simple.md
Example for a frame action doesn't specify timezone.  Community member pointed out it was confusing.  Updated to specify UTC since I don't think we can see the user's timezone in the request.
=> Add utc to example message

apps/base-docs/src/theme/DocItem/Content/index.js
Hotfix for Base Camp content
N/A
Manually
=> Hotfix for Base Camp

apps/bridge/next.config.js, apps/bridge/src/components/AssetList/AssetList.tsx, apps/bridge/src/components/BridgeInput/BridgeInput.tsx, apps/bridge/src/components/BridgeToInput/BridgeToInput.tsx, apps/bridge/src/components/Faq/FaqSidebar.tsx, apps/bridge/src/components/Header/Header.tsx, apps/bridge/src/components/Sidebar/Sidebar.tsx, apps/bridge/src/components/TransactionSummary/TransactionSummary.tsx
Implemented fixes for accessibility issues described by @stevenmalenz in https://github.com/base-org/web/issues/439
Low contrast issues somewhat resolved using the tailwind class `text-stone-400` instead of `text-stone-600` a secondary colour could be a better solve. Having a light mode theme option could provide more stylistic freedom.
No notes
Built, run, and previewed in the local environment. Reviewed across multiple browsers on desktop and mobile resolutions.
No
=>  Add digital accessibility improvements to Base Bridge

apps/web/src/components/Layout/Nav/DesktopNav.tsx, apps/web/src/components/Layout/Nav/MobileMenu.tsx, apps/web/src/components/Layout/Nav/Nav.tsx
Previously:
Now:
Manually using remote debugging on local iOS device.
=> Fix nav align on mobile

.github/PULL_REQUEST_TEMPLATE.md
We haven't seen any pull requests adding tokens directly to the bridge for many weeks so I was thinking we can drop this since it is not relevant for most contributors
N/A
Localhost
=> docs(pr-template): Drop token questionnaire from pull request template

apps/base-docs/tutorials/docs/3_farcaster-frames-transactions.md
Drops the warning that there is no support for testnet
N/A
Localhost
=> docs(frame-transactions): Drop warning regarding no support for testnet

apps/bridge/pages/_app.tsx, apps/bridge/src/components/Faq/FaqSidebar.tsx
Updates the banner with deprecation date, expands additional FAQs and adds link to Superbridge
N/A
Localhost
=> docs(bridge): Update banner and FAQs

apps/web/src/components/OnchainSummer/RewardsBlock.tsx
Coinbase docs changed their domains and the redirects don't work properly.
=> Change docs link

apps/web/pages/_document.tsx, apps/web/pages/buildersummer.tsx, apps/web/src/components/OnchainSummer/EventsBlock.tsx, apps/web/src/components/OnchainSummer/SponsorsBlock.tsx
- Changed SEO metatitle from `Base | About` to `Onchain Summer | Buildathon`
- Added dates to SEO metadescription: `Onchain Summer is inviting everyone to unleash onchain creativity & build all summer long. Build, create, & get rewarded. Jun – Aug 2024.`
- Made small fixes for consistency (“Buildation” typo, added .’s where needed, etc.)
- Added a link + CTA to Bountycaster (https://www.bountycaster.xyz/onchainsummer) to its section
Manually
=> Add Bountycaster CTA, update SEO, & small fixes

apps/web/src/components/OnchainSummer/SponsorsBlock.tsx
So that we don't end up hiding sponsors behind a scroll bar
=> Use grid layout, kill scroll

apps/base-docs/docs/tools/data-indexers.md
This PR added GhostGraph to `data-indexers.md` file
Added GhostGraph as a data indexer for Base data in data-indexers.md
* Run `yarn workspace @app/base-docs dev`
* Navigate to `http://localhost:3000/docs/tools/data-indexers`
* Validate that the changes worked as expected: ![GhostGraph_Base_Docs](https://github.com/base-org/web/assets/13743841/9bf9c7a1-0a65-4db7-b684-5c8f9a6ba598)
* No, this PR does not add a new token to the bridge
* [NA] I've confirmed this token doesn't use a bridge override
* [NA] I've confirmed this token is an OptimismMintableERC20
* https://twitter.com/0xGhostLogs/status/1790415744833843659
=> Update data-indexers.md to include GhostGraph

apps/base-docs/docs/tokens/token-list.md
This drops a docs reference to the official Base Bridge which has now been deprecated
N/A
Localhost
=> docs(token-list): Drop bridge.base.org language

apps/base-docs/server.js, apps/bridge/next.config.js, apps/web/next.config.js
- Currently, using Coinbase Smart Wallet on base.org results in an infinite spinner because the website fails to communicate with the popup. This is due to the `Cross-Origin-Opener-Policy` HTTP header being set to `same-origin` which prevents the popup from accessing the `window.opener` property
- This PR updates the header to `same-origin-allow-popups` which allows the Smart Wallet popup to access `window.opener` and establish the connection
| Before | After |
| ------------- | ------------- |
| <video src="https://github.com/base-org/web/assets/16995513/ba228ebd-d3ad-42db-adbc-655b60986a78">  | <video src="https://github.com/base-org/web/assets/16995513/21777265-44e3-484c-bf15-67d3a9cd4e97">|
=> Update HTTP Header for Coinbase Smart Wallet

apps/base-docs/docs/tools/onboarding.md
Adding [Sequence](https://sequence.xyz/) to onboarding docs.
N/A
Links have been tested, Sequence added in alphabetical order following convention.
No
=> Add Sequence to onboarding docs

apps/web/pages/onchainfont.tsx
Previously the downloaded zip file could fail to open because the response handler would resolve before the file finished streaming.
Manually expanding the resulting zip file.
=> Fix early termination of the filestream

apps/base-docs/docs/cookie-policy.mdx, apps/base-docs/tutorials/docs/0_deploy-with-foundry.md
There are 2 mdx files in the base docs set and each has 1 relative link -- both are broken as the syntax differs in an mdx vs md file.
Was not tested against a locally run Docusaurus server
=> chore: fix relative links in mdx files

apps/base-docs/docs/contracts.md
Updates the contracts page to add links to Base Sepolia testnet interfaces
Localhost
=> Add testnet interfaces for interacting w/ Uniswap contracts

apps/base-docs/docs/tools/onramps.md, apps/web/src/data/ecosystem.json
- Update naming from Coinbase Pay to Coinbase Onramp
- Update language to say they can get started by going to Coinbase Developer Platform [here](https://docs.cdp.coinbase.com/onramp/docs/getting-started/) instead of joining the waitlist
- Update URL for marketing link to https://www.coinbase.com/developer-platform/products/onramp instead of https://www.coinbase.com/cloud/products/pay-sdk
Ran locally
=> Update Coinbase Onramp page

apps/base-docs/docs/tools/onramps.md
Changed link for "getting started" to https://docs.cdp.coinbase.com/onramp/docs/getting-started/
=> Update Coinbase Onramp getting started link

apps/base-docs/docs/building-with-base/base-contracts.md
We updated the owner for both L1 and L2 ProxyAdmin and SystemConfig to Safe because of the MCP initiative from OP-stack. Thus updating the documentation.
=> Update ProxyAdmin and SystemConfig owner on Sepolia

apps/base-docs/tutorials/docs/2_coinbase-smart-wallet.md
Broken link on https://docs.base.org/tutorials/coinbase-smart-wallet/
Coinbase Smart Wallet linked to `https://docs.base.org/tutorials/coinbase-smart-wallet/www.smartwallet.dev`
N/A
`yarn workspace @app/base-docs dev` and tested locally
=> (fixes): fix tutorial broken link

apps/base-docs/tutorials/docs/0_run-a-base-node.md
Bumps hardware requirements from 700 to 750 for a full node, and 4TB to 4.5TB for an archive node
N/A
Localhost
=> docs(node): Bump HDD requirements

apps/web/package.json, apps/web/src/components/Layout/Layout.tsx, yarn.lock
When running the local dev server we currently see:
```
⚠ Your project has `@next/font` installed as a dependency, please use the built-in `next/font` instead. The `@next/font` package will be removed in Next.js 14. You can migrate by running `yarn dlx @next/codemod@latest built-in-next-font .`. Read more: https://nextjs.org/docs/messages/built-in-next-font
```
This commit is the result of running the relevant codemod and using the built-in `next/font`
visually; locally
|before|after|
|-|-|
|<img width="828" alt="image" src="https://github.com/base-org/web/assets/5773490/8c3aa7ce-9933-49fd-bf41-0fc20585e55a">|<img width="843" alt="image" src="https://github.com/base-org/web/assets/5773490/528ca862-12f2-4bb8-8a97-c2c34613a5b2">|
=> chore: runs yarn dlx @next/codemod@latest built-in-next-font .

apps/base-docs/docs/building-with-base/network-information.md, apps/base-docs/docs/using-base.md, apps/base-docs/docusaurus.config.js, apps/bridge/src/components/Nav/DesktopNav.tsx, apps/bridge/src/components/Nav/MobileMenu.tsx, apps/web/src/components/Layout/Nav/DesktopNav.tsx, apps/web/src/components/Layout/Nav/MobileMenu.tsx
[Basescan is currently experiencing an outage](https://basescan.statuspage.io/incidents/vhp0m2pr0vdn). This updates relevant block explorer links to point to Blockscout in the interim.
N/A
Localhost
=> fix(block explorer): Point to Blockscout alongside outage

apps/web/package.json, yarn.lock
nextjs requests `sharp` for production builds, and we don't currently include it. Because of this our prod build falls back to dev-mode image processing. 
[docs link](https://nextjs.org/docs/messages/sharp-missing-in-production)
**running `yarn build`**
=> feat: add `sharp` for prod img processing

apps/base-docs/Dockerfile
Updated the Dockerfile in the Base-Docs app to build at runtime. This enables the inclusion of env variables that otherwise are not included in the build.
* Deployed internal test environment through CodeFlow. 
* Confirmed that SPRIG_ENVIRONMENT_ID is present and that the Sprig integration loads successfully.
=> Updated Dockerfile in Base-Docs to build at runtime

apps/base-docs/src/components/FooterCategory/index.tsx
Moved the react `key` property to the `<li>` tags instead of on the anchor tags, thereby resolving console errors.
Manually locally.
=> Moved key property to list items

apps/base-docs/docs/notices/preparing-for-fault-proofs-on-base-sepolia.md, apps/base-docs/sidebars.js
This adds a new section in the docs called 'Notices' and includes a notice (reviewed and approved) with important information that will be relevant for builders alongside fault proofs coming to Base Sepolia
N/A
Localhost
=> Add page with relevant information regarding fault proofs coming to Base Sepolia

apps/base-docs/tutorials/docs/0_run-a-base-node.md
Add new requirement that an NVMe is recommended when running a Base Node
N/A
Localhost
=> maintenance(node): Notate new requirement, NVME

apps/base-docs/base-camp/docs/frontend-setup/building-an-onchain-app.md, apps/base-docs/base-camp/docs/hardhat-deploy/hardhat-deploy-sbs.md, apps/base-docs/base-camp/docs/hardhat-forking/hardhat-forking.md, apps/base-docs/base-camp/docs/hardhat-setup-overview/hardhat-setup-overview-sbs.md, apps/base-docs/base-camp/docs/hardhat-testing/hardhat-testing-sbs.md, apps/base-docs/base-camp/docs/hardhat-verify/hardhat-verify-sbs.md, apps/base-docs/base-camp/docs/interfaces/contract-to-contract-interaction.md, apps/base-docs/base-camp/docs/reading-and-displaying-data/configuring-useReadContract.md, apps/base-docs/base-camp/docs/reading-and-displaying-data/useAccount.md, apps/base-docs/base-camp/docs/reading-and-displaying-data/useReadContract.md, apps/base-docs/base-camp/docs/writing-to-contracts/useSimulateContract.md, apps/base-docs/base-camp/docs/writing-to-contracts/useWriteContract.md, apps/base-docs/docs/tools/hardhat.md, apps/base-docs/tutorials/docs/0_deploy-with-hardhat.mdx, apps/base-docs/tutorials/docs/1_event-poap-nouns.md, apps/base-docs/tutorials/docs/1_thirdweb-unreal-nft-items.md, apps/base-docs/tutorials/docs/2_account-abstraction-with-particle-network.md, apps/base-docs/tutorials/docs/2_account-abstraction-with-privy-and-base-paymaster.md, apps/base-docs/tutorials/docs/2_coinbase-smart-wallet.md, apps/base-docs/tutorials/docs/2_onchain-nfts.md, apps/base-docs/tutorials/docs/2_signature-mint.md, apps/base-docs/tutorials/docs/3_farcaster-frames-gating-and-redirects.md, apps/base-docs/tutorials/docs/3_farcaster-frames-hyperframes.md, apps/base-docs/tutorials/docs/3_farcaster-frames-nft-minting.md, apps/base-docs/tutorials/docs/3_farcaster-frames-nocode-minting.md, apps/base-docs/tutorials/docs/3_farcaster-frames-transactions.md, apps/base-docs/tutorials/docs/4_hardhat-profiling-gas.md, apps/base-docs/tutorials/docs/4_hardhat-profiling-size.md, apps/base-docs/tutorials/docs/4_intro-to-providers.md, apps/base-docs/tutorials/docs/5_farcaster-cast-actions-simple.md
TypeScript code blocks, including tsx, were using ```typescript for syntax highlighting.  This doesn't appropriately highlight embedded html.  Swap to ```tsx, which renders TypeScript the same, but fixes html.  
Old:
New:
=> Swap typescript Code Blocks to tsx

.github/workflows/node.js.yml, .nvmrc, package.json
just housekeeping and allowing .nvmrc to be permissive w/ hydrogen LTS tag
https://nodejs.org/en/blog/release/v18.12.0
note: I've added 18.x to the gh build action matrix. I don't have privileges currently to modify the required build steps and move from 16->18 there.
=> chore: updated node versioning to be latest of 18 (hydrogen)

apps/base-docs/docs/tools/data-indexers.md
Changed tooling page to include Subsquid
=> Add Subsquid to tooling

apps/base-docs/docs/tools/oracles.md
**What changed? Why?**: Added [Chronicle](https://chroniclelabs.org/) to the Oracles page using the same template existing for the other Oracles
**How has it been tested?**:  Yes, it was run locally
=> Add Chronicle to Oracles page

apps/web/src/components/Ecosystem/List.tsx, apps/web/src/data/ecosystem.json
* Changed the value we use as the react-key for ecosystem cards from the app's name to the app URL. 
* Deleted duplicate entry for OpenCover
* Considered simply changing the names of the colliding entries to be unique. 
* Decided against that as it's less future-proof than using the URL. It's reasonable for apps to share the same name. They should never share the same url.
Locally.
=> Fix: Fixed colliding react keys in ecosystem search

apps/base-docs/docs/tools/data-indexers.md
* GhostGraph now support Base Sepolia
* A protocol (will announce it later) has integrated on Base Sepolia
=> Update data-indexers.md to include GhostGraph: base sepolia support

apps/base-docs/src/theme/NavbarItem/ComponentTypes.js, apps/web/src/components/ConnectWalletButton/ConnectWalletButton.tsx, libs/base-ui/utils/logEvent.ts, libs/base-ui/utils/sanitizeEventString.ts
* Added walletType to logEvent `eventData` schema
* Implemented walletType data capture on `wallet_connected` event
=> Feat: Add walletType to event data

apps/base-docs/tutorials/docs/0_deploy-with-foundry.md
You now need an api key for verifying with BaseScan for Base Sepolia.  Updated to reflect.
Changed "we" to "you" to match style guide.
=> Update api key requirement, minor style updates

apps/base-docs/tutorials/docs/0_run-a-base-node.md
Add the Reth snapshot URLs to the documentation.
=> Document Reth snapshot URLs

package.json, yarn.lock
nextjs was complaining about uncertain resolution, so this runs `yarn dedupe` (implicit `highest` strat) and adds a resolution entry for the cookie manager in the root package.json
=> chore: runs yarn dedupe and enforces a consistent version resolution for coinbase cookie manager

apps/web/package.json, yarn.lock
This should have been removed a while ago when its usage was removed, but I guess it slipped through.
=> remove unused dep

apps/web/src/hooks/useRegisterNameCallback.ts
smart wallet transactions were updated to use `useWriteContracts`. When that change was made the data, loading, and errors relevant to the transaction were incorrectly ignored. This returns those values from the `useRegisterNameCallback` hook.
=> add tx hash to smart wallet transactions

apps/base-docs/tutorials/docs/3_farcaster-frames-gating-and-redirects.md, apps/base-docs/tutorials/docs/3_farcaster-frames-hyperframes.md, apps/base-docs/tutorials/docs/3_farcaster-frames-nft-minting.md, apps/base-docs/tutorials/docs/3_farcaster-frames-nocode-minting.md, apps/base-docs/tutorials/docs/3_farcaster-frames-transactions.md, apps/base-docs/tutorials/docs/5_farcaster-cast-actions-simple.md
Frames tutorials predate onchainkit.xyz and linked to the repo in github.  Updated them to link to the site instead.
=> Change OnchainKit links from github to site

apps/base-docs/docusaurus.config.js
The `trailingSlash` setting in the `docusaurus.config.js` of `apps/base-docs` has to be set to `false`. This configuration change is necessary because URLs ending with a slash are causing pages to be misinterpreted as directories. This misinterpretation leads to to issues with relative links not resolving correctly, as seen in [**Deployment Exercise**](https://docs.base.org/base-learn/docs/deployment-to-testnet/deployment-to-testnet-exercise/) where the links [Basic Math](https://docs.base.org/base-learn/docs/contracts-and-basic-functions/basic-functions-exercise) and [Testnets](https://docs.base.org/base-learn/docs/deployment-to-testnet/test-networks) don't work. By removing the forced trailing slash every relative link in the page now works. …
=> fix: disable trailingSlash to fix relative link resolution in docs

apps/base-docs/src/components/FooterCategory/index.tsx, apps/base-docs/src/pages/tutorials/styles.module.css
* added overflow scroll for tutorial pills
=> Fix: Tutorial Pills Should Scroll On Overflow

apps/web/src/cdp/api/cb-gpt.ts
add errorResponse to cb-gpt.
We need more details to know why th ings might be forbidden. Example error in localhost:
`{"error":"failed to generate suggestions 403 go/sg/7b420819-a6a3-4e43-b1d2-38043fc2d53b"}`
This would help us debug
local test
=> add errorResponse to cb-gpt query

apps/web/src/cdp/api/cb-gpt.ts
stringify errorResponse to cb-gpt query.
If we get a json object, it will not show anything relevant, this fixes it.
local test
=> stringify errorResponse to cb-gpt query

apps/web/src/components/Basenames/RegistrationContext.tsx, apps/web/src/components/Basenames/RegistrationForm/index.tsx, apps/web/src/hooks/useRegisterNameCallback.ts
This should enable requesting from connected wallets the status of a `sendCalls` batch id for name registrations and ties the status of the batch transactions into the existing pending/success/fail logic flow for transaction hashes sent via the traditional flow.
=> feat: adds support for smart wallet's batched calls status tracking

apps/web/app/(base-org)/ecosystem/page.tsx, apps/web/src/components/Ecosystem/List.tsx, apps/web/src/components/Ecosystem/TagChip.tsx
- Move ecosystem page to App router
- fix the useRouter logic
- fix the scroll jumping issue
=> [CHORE]: Move ecosystem page to App router

apps/web/src/components/Basenames/RegistrationContext.tsx, apps/web/src/components/Basenames/RegistrationProfileForm/index.tsx, apps/web/src/components/Basenames/RegistrationSuccessMessage/index.tsx
Ref: https://linear.app/coinbase/issue/ECO-237/basename-profile-redirect-flash-white
=> ECO-237: Basename: redirect to profile without domain if mainnet

apps/web/app/(basenames)/name/[username]/page.tsx, apps/web/next.config.js
- https://linear.app/coinbase/issue/ECO-207/names[name]-does-not-redirect-to-name[name]
- https://linear.app/coinbase/issue/ECO-221/baseorgname-needs-to-redirect-to-names
=> Basename: Setup redirects in next-config

apps/web/src/components/Basenames/RegistrationFlow.tsx, apps/web/src/components/Basenames/RegistrationSuccessMessage/index.tsx
Ref: https://linear.app/coinbase/issue/ECO-219/mobile-register-name
=> ECO-219: Fix mobile / desktop success UI

apps/web/next.config.js
- coinbase domain (potentially related to some smart wallet/sdk failures)
- rainbow api for improved ens resolution when mainnet is not accessible to its provider
=> chore: add two csp entries

.eslintrc.js
* set the typescript-eslint rule `no-use-before-define` to `off`
locally
=> Chore: Turned off no-use-before-define ts-eslint rule

apps/web/src/components/Basenames/UsernameProfileSectionBadges/index.tsx
|before|after|
|-|-|
|<img width="385" alt="image" src="https://github.com/user-attachments/assets/722323fa-872c-4437-a128-087c1e1bc8a5">|<img width="377" alt="image" src="https://github.com/user-attachments/assets/b3942dcd-1d55-48e6-877f-e73c4b30c643">|
=> tiny viewports now get centered badges

apps/web/app/datadog.ts
=> Fix datadog env var name to be available on the FE

apps/web/src/components/Basenames/RegistrationContext.tsx
some people aren't getting the transition out of pending state--this adds a duplicate mechanism for executing that transition
=> fix: duplicate success transfer logic

apps/web/pages/api/proofs/bns/index.ts, apps/web/src/addresses/usernames.ts, apps/web/src/utils/proofs/proofs_storage.ts
Add bns discount validator endpoint. This will set up a merkle tree for all users that have Basenames.app names so that they can claim a discount
validator address is still not defined, however the merkle tree has been created.
tested locally using addresses on the merkle tree.
=> Add bns discount validator endpoint

apps/web/app/(base-org)/(root)/page.tsx, apps/web/src/components/Commitment/Commitment.tsx, apps/web/src/components/GetConnected/GetConnected.tsx, apps/web/src/components/GetConnected/GetConnectedButton.tsx, apps/web/src/components/Home/Hero.tsx, apps/web/src/components/Partnerships/Partnerships.tsx
* Added event logging to base.org homepage links, leveraging AnalyticsProvider
* GetConnected section required extracting the social links into a client-side sub-component
locally
=> Chore: Log Base.org Homepage Events

apps/base-docs/docs/building-with-base/base-contracts.md
Dispute game implementation re-deployed with new absolute prestate for Granite upgrade, `0x030de10d9da911a2b180ecfae2aeaba8758961fc28262ce989458c6f9a547922`
https://github.com/ethereum-optimism/superchain-ops/pull/295
=> [Base Sepolia Granite] Update dispute game implementation addresses to reflect upgrade

apps/base-docs/docs/tools/registry-faq.md, apps/base-docs/sidebars.js
Added in an FAQ for the Onchain Registry and edited the navbar to show the API docs and FAQ under a dropdown.
I ran the docs site and tested locally
=> Added Registry FAQ page

apps/base-docs/docusaurus.config.js, apps/web/src/components/GetStarted/BuildersMostWanted.tsx, apps/web/src/components/GetStarted/StartBuilding.tsx, apps/web/src/components/Home/Hero.tsx, apps/web/src/components/Layout/Nav/DesktopNav.tsx, apps/web/src/components/Layout/Nav/MobileMenu.tsx
* Added `Get Started` link to base-web navbar
* Added `Get Started` link to base-docs navbar (nesting `Tutorials` under Learn Dropdown)
* Updated baseweb hero CTAs: `Get Started` + `Read the Docs` (deprecating `Bridge Assets`)
* Updated copy/links for two resource cards
locally
=> Feat: GetStarted page Discoverability

apps/base-docs/docusaurus.config.js
* `Tutorials` now goes after `Learn to Build Onchain`
locally
=> Chore: Change order of Learn Dropdown links

apps/web/src/components/Jobs/JobsList.tsx
* added workaround to jobs page logic to rename BD to Ecosystem
locally
=> Chore: Rename BD to Ecosystem

apps/web/src/components/GetConnected/GetConnectedButton.tsx
* Made the GetConnected icons downsize for mobile screens
locally
=> Fix: GetConnected icon sizing

apps/base-docs/base-learn/docs/help-on-discord.md, apps/base-docs/base-learn/sidebars.js
I suspect part of the drop-off in chats in the Base Learn Discord channel is that people can't find it in all the channels we have now.
Added a page with signup info and a link in the nav sidebar of Base Learn pages.
Locally/manually
=> Add direct link to discord channel in Learn sidebar

apps/web/pages/api/proofs/cbid/index.ts, apps/web/src/utils/proofs/proofs_storage.ts, apps/web/src/utils/proofs/requests.ts
Make cbId search lowercase
Update cbid discount namespace
allow for exact match search on db
This is done to optimize to very large datasets like cbid. Searching through ilike would result in long delays and time outs.
tested locally with real data set
=> Make cbId search lowercase and case sensitive to search by index

apps/web/src/utils/proofs/proofs_storage.ts, apps/web/src/utils/proofs/requests.ts
Return the real discountValidator address on proof endpoints.
Currently discountValidator was always returning the CB.id address. this change will use the real discount validator based on namespace.
Tested against BNS, BaseEth, and CBID proof endpoints
=> Return the real discountValidator address on proof endpoints

apps/web/src/hooks/useActivePremiumAmount.ts
* changed logic in `useActivePremiumAmount` to always pull from base mainnet, not the user's current chain
locally
=> Chore: Update Active Eth Premium to pull from base mainnet

apps/web/src/components/Basenames/PremiumExplainerModal/index.tsx, apps/web/src/components/Basenames/RegistrationForm/index.tsx, apps/web/src/hooks/useRentPrice.ts
* created hook to use the `rentPrice` contract method, returning a tuple with base price and premium price
* leverage useRentPrice in the Registration form, updating:
* logic for when to show the banner
* the premium price displayed to users on the banner and in the learn more modal
* updated number of significant digits shown in the premium explainer modal
locally
=> Fix: updated logic for base and premium pricing in banner

apps/web/app/datadog.ts, apps/web/package.json, package.json, yarn.lock
Add datadog browser logs. We are currently getting metrics, but console.error are nos easily searchable. 
Have not tested the logs are actually flowing to our datadog instance.
built and init locally
=> Add datadog browser logs

apps/web/src/components/Basenames/UsernameProfileNotFound/index.tsx
Redirect user back to names page if they try to visit a reserved name profile. 
Because we redirect at the NotFound component, this will only affect reserved names and not ones that have a profile
=> Redirect user back to names page if they try to visit a reserved profile

apps/web/src/components/Basenames/RegistrationFlow.tsx
Using padding instead of margin meant that the transition element was invisibly covering the social share buttons making them unclickable.
=> Make the social share buttons clickable

apps/web/src/components/Basenames/UsernameProfileNotFound/index.tsx
Need to strip `.base.eth` from username before lookup
=> Strip username for reserved name lookup

apps/web/src/components/Basenames/RegistrationFlow.tsx
* added an effect triggered by `isSuccess` to remove the banners and modals on base-web and base-docs
locally
=> Fix: Remove Banners and Modal after successful claim

apps/web/src/components/Basenames/RegistrationForm/index.tsx, apps/web/src/hooks/useActiveEthPremiumAmount.ts
=> fix: show <0.001 instead of 0 when number gets small

apps/web/pages/api/basenames/avatar/upload.ts, apps/web/pages/api/proofs/baseEthHolders/index.ts, apps/web/pages/api/proofs/bns/index.ts, apps/web/pages/api/proofs/cb1/index.ts, apps/web/pages/api/proofs/cbid/index.ts, apps/web/pages/api/proofs/coinbase/index.ts, apps/web/pages/api/proofs/earlyAccess/index.ts, apps/web/src/utils/proofs/requests.ts, apps/web/src/utils/proofs/sybil_resistance.ts
Updating to something more standardized.
409 means user has already claimed
500 means server or unexpected error
This will help us have better monitoring and alerts
local testing directly to API calls
=> Update status codes on proofs API for better monitoring

apps/base-docs/docs/tools/oracles.md
Added [ORA](https://ora.io) to the Oracles page using the same template existing for the other Oracles.
Yes, it runs locally.
=> Add ORA to Oracles page

apps/web/src/components/Basenames/ProfilePromo/index.tsx, apps/web/src/components/Basenames/RegistrationForm/index.tsx, apps/web/src/components/SearchAddressInput/index.tsx
- Hide Basename Promo if user already has a basename
- fix the search address/basename explorer URL
- Add info icon and tooltip to the "Set as Primary Name" input in the registration flow.
=> Basename fixes aug 26

apps/web/pages/api/decorators.ts, apps/web/pages/api/name/[alreadyClaimedName].ts, apps/web/pages/api/proofs/baseEthHolders/index.ts, apps/web/pages/api/proofs/bns/index.ts, apps/web/pages/api/proofs/cb1/index.ts, apps/web/pages/api/proofs/cbid/index.ts, apps/web/pages/api/proofs/coinbase/index.ts, apps/web/pages/api/proofs/earlyAccess/index.ts, apps/web/pages/api/registry/entries.ts, apps/web/pages/api/registry/featured.ts
Add withTimeout decorator to APIs. This is to prevent APIs taking resources with no timeout limits.
tested locally faking a 10 second wait to provoke the 409
=> Add withTimeout decorator to APIs

apps/base-docs/src/theme/Navbar/index.js, apps/web/src/components/Layout/Nav/Nav.tsx
* removed basenames launch banner from base-web and base-docs
locally
=> Chore: Remove basenames banners from web and docs

apps/web/pages/api/decorators.ts, apps/web/pages/api/proofs/cb1/index.ts, apps/web/pages/api/proofs/coinbase/index.ts, apps/web/src/utils/logger.ts, apps/web/src/utils/metrics.ts, apps/web/src/utils/proofs/sybil_resistance.ts
Remove sendToDatadog from logger. This is being removed in favor of using the datadog agent and custom Coinbase infrastructure. 
tested locally
=> Remove sendToDatadog from logger and metrics

apps/web/app/(base-org)/ecosystem/page.tsx, apps/web/src/components/Ecosystem/Card.tsx, apps/web/src/components/Ecosystem/Content.tsx, apps/web/src/components/Ecosystem/List.tsx, apps/web/src/components/Ecosystem/SearchBar.tsx, apps/web/src/components/Ecosystem/TagChip.tsx
Use react state to display & filter ecosystems apps.
=> Remove url-based navigation in favor of client states

apps/base-docs/base-learn/docs/frontend-setup/building-an-onchain-app.md, apps/base-docs/base-learn/docs/frontend-setup/wallet-connectors.md, apps/base-docs/tutorials/docs/0_intro-to-providers.md
1.  "were" should be "where"
2. Markdown code block format ":::" should be "```"
3. Code example's `"use client":` should be `"use client";`
4. Consistent styling to RainbowKit and wagmi. Updated style to `'use client';`
5. Optimism's network information URL is broken. Updated link to https://docs.optimism.io/chain/networks
n/a
Visually.
=> Fix typos in frontend docs

apps/web/app/(basenames)/name/[username]/opengraph-image.tsx
Fix OG image when name has emoji within the URL
=> Fix Basename profile OG image

apps/web/pages/api/basenames/frame/constants.ts, apps/web/src/utils/frames.ts
* fixed environment variable references in the basenames claim frame
=> Fix: Frame env var references

apps/base-docs/base-learn/docs/writing-to-contracts/useWriteContract.md, apps/base-docs/tutorials/docs/4_intro-to-foundry-setup.md, apps/base-docs/tutorials/docs/5_oracles-chainlink-price-feeds.md
1. The tutorial `useWriteContract()` is using `isPending` instead of `isLoading`.
Updated demo code to reflect this.
2. `you'll'll` should be `you'll`
3. Consistent codeblock MarkDown format where `tsx:` should be `tsx`
4. `forge build:` should be `forge build`
5. Chainlink's AggregatorV3Interface path is wrong. Updated path.
https://docs.chain.link/data-feeds/using-data-feeds
n/a
Visually.
=> Fix typos and demo code in docs

apps/web/package.json, yarn.lock
Bump `@frames.js/render` from `^0.3.7` to `^0.3.12` to include a fix for some frames including this one [2048 frame](https://warpcast.com/m0nt0y4/0x1c93e658) and a couple others so that they work correctly. Here's the [upstream fix](https://github.com/framesjs/frames.js/pull/498).
This is tested via unit tests in frames.js. For this bugfix we added a new one [here](https://github.com/framesjs/frames.js/blob/b2f70cb00e127fde7a8e8b7f263394a02fb5240a/packages/frames.js/src/frame-parsers/open-frames.test.ts#L710) in [this PR](https://github.com/framesjs/frames.js/pull/498)
=> fix: bump @frames.js/render version

apps/web/src/components/Basenames/ConfigureFramesPageContent/FrameBuilder.tsx
makes it clear we support minting on Base, not Zora
=> chore: add BASE nft copy change

apps/web/src/components/Basenames/ProfilePromo/index.tsx
two issues:
1. it was not remembering if the user dismissed or acted on the banner
2. it was `position: absolute` when it should have been `position: fixed`
=> add two improvements/fixes to the basenames promo

apps/web/src/components/Basenames/UsernameProfileSectionFrames/index.tsx
|before|after|
|-|-|
|<img width="792" alt="image" src="https://github.com/user-attachments/assets/2d0d324b-5b9c-478a-8968-69f5e7bfd0c9">|<img width="836" alt="image" src="https://github.com/user-attachments/assets/21053588-f229-47e8-a68a-ba389d1bcfde">|
=> [Improvement] Remove “frames” title from the profile

apps/web/package.json, yarn.lock
Reverts base-org/web#1021
this bug was mis-attributed and the diff is safe to go in
=> Revert "Revert "fix: bump @frames.js/render version""

apps/web/src/components/GetStarted/StartBuilding.tsx
* fixes spelling mistake on `/getstarted`
=> Fix: spelling mistake

.github/workflows/main.yml, apps/web/app/frames/route.tsx, apps/web/jest.config.js, apps/web/jest.setup.js, apps/web/middleware.ts, apps/web/package.json, apps/web/src/middleware/ipSafe.spec.ts, apps/web/src/middleware/ipSafe.ts, apps/web/tsconfig.json, package.json, yarn.lock
https://linear.app/coinbase/issue/BAPP-653/create-blocklist-of-ips-we-should-not-resolve-dns-for-in-basenames
logic: `apps/web/src/middleware/ipSafe.ts`
called via a wrapper on frames.js's default route handlers: `apps/web/app/frames/route.tsx`
|before|after|
|-|-|
|500 error|403 error|
|<img width="1138" alt="image" src="https://github.com/user-attachments/assets/6915b898-cf0f-42f6-84a7-59e254b93b3c">|<img width="1152" alt="image" src="https://github.com/user-attachments/assets/b9a46adb-3d68-4229-864a-db9a7ef6f2bf">|
```json
// before
{
"message": {
"cause": {
"errno": -65,
"code": "EHOSTUNREACH",
"syscall": "connect",
"address": "169.254.169.254",
"port": 443
}
}
}
// after
{"message":"Forbidden: Unsafe IP"}
```
=> check for frame ip safety

apps/web/src/components/Basenames/UsernameProfileSectionFrames/index.tsx
|before|after|
|-|-|
|<img width="833" alt="image" src="https://github.com/user-attachments/assets/192f0da4-6904-4d65-9051-5d397eee6a02">|<img width="867" alt="image" src="https://github.com/user-attachments/assets/f5f46116-4d2b-43a1-b4f6-13914209826c">|
=> feat: add + icon instead of text

apps/web/app/frames/img-proxy/route.ts
enforces only image content, and disallows svg
=> require response content-type be an image

apps/web/src/components/Basenames/UsernameProfileSectionFrames/FrameTheme.tsx
|before|after|
|-|-|
|<img width="428" alt="image" src="https://github.com/user-attachments/assets/bfd41b7e-ce1d-4d72-a26b-b97abaca22e0">|<img width="428" alt="image" src="https://github.com/user-attachments/assets/efbcf373-5c6e-4a23-827b-47e722b3000a">|
=> feat: better invalid frame styling

apps/web/src/components/Basenames/UsernameProfileSectionHeatmap/index.tsx
This causes the heatmap to begin scrolling from a start position on the right-hand side of the div. Doing this keeps the most current date in view by default.
=> make the onchainscore heatmap scroll rtl

apps/web/src/components/Basenames/UsernameProfileSectionFrames/Context.tsx, apps/web/src/components/Basenames/UsernameProfileSectionFrames/Frame.tsx, apps/web/src/components/Basenames/UsernameProfileSectionFrames/index.tsx
This has each frame track its own errors, whereas before all errors were aggregated at the context level (dumb).
Errors quickly fade in, and fade out when clicked. 
|before|after|
|-|-|
|<img width="498" alt="image" src="https://github.com/user-attachments/assets/d5a373b0-dd47-43cb-9a66-7ba9de9608cc">|<img width="436" alt="image" src="https://github.com/user-attachments/assets/0c446b09-d416-4da3-a5b5-b7ca5edc08c7">|
=> fix: better error messages for frames

apps/web/src/components/Basenames/UsernameProfileSectionFrames/Frame.tsx
This adds some comments and a better name to the higher order function handling frame error discrimination per @kirkas 's suggestion
=> improve readability of the frame error wrapper

apps/web/src/components/SearchAddressInput/index.tsx
When you type in an ens or basename in the search input on the ownership change modal, it was case sensitive.
So `Garey.base.eth` wouldn't resolve, but `garey.base.eth` would resolve.
This change validates the ens name against `inputValue.toLocaleLowerCase()` and now the ens will resolve appropriately without casing sensitivity.
| BEFORE | AFTER |
| -------- | ------- |
| <img width="496" alt="Screenshot 2024-10-13 at 8 27 10 AM" src="https://github.com/user-attachments/assets/19eaae7b-3cf6-4e33-8ab6-51c0b498a4b2"> | <img width="495" alt="Screenshot 2024-10-13 at 8 47 18 AM" src="https://github.com/user-attachments/assets/717cd756-e0e1-455b-aedd-115a2fc2e5f0"> |
Locally tested, see screenshots.
=> fix: name ownership recipient ens casing sensitivity

apps/web/app/AppProviders.tsx
Added Phantom to ecosystem page and connect wallet modal, per [Jesse's tweet](https://x.com/jessepollak/status/1844909899962364304).
Thank you for the [warm welcome](https://x.com/jessepollak/status/1843348984926199815) to Base! Phantom added Base support on Monday 10/7.
Ran locally to confirm. See screenshot below
=> add phantom to connect wallet modal

apps/base-docs/docs/notices/preparing-for-fault-proofs-on-base.md, apps/base-docs/sidebars.js
Adds a notice to docs.base.org for fault proofs going live with helpful information
N/A
Localhost
=> docs: Add notice regarding fault proofs coming to mainnet on Base

apps/web/app/(base-org)/(root)/page.tsx, apps/web/src/components/ThreeHero/DynamicRigidBody.tsx, apps/web/src/components/ThreeHero/PhysicsMesh.tsx, apps/web/src/components/ThreeHero/index.tsx, apps/web/src/components/ThreeHero/models.tsx
We are globally bundling most of the 3D libraries (three, react-three/rapier, etc..).
This PR leverages dynamic() loading and import() to load the heaviest import asynchronously, and within 3D hero component only.
Results in a 50% javascript reduction across all pages.
=> Fix: Dynamically import three.js libraries

apps/web/app/(stats)/layout.tsx, apps/web/app/(stats)/stats/page.tsx, apps/web/next.config.js
Setup a page on `base.org/stats`, that will embed our public datadog dashboard.
Ran locally.
=> chore: add stats page w/ datadog iframe

apps/web/app/(base-org)/builder-anniversary-nft/page.tsx, apps/web/app/(basenames)/layout.tsx, apps/web/app/AppProviders.tsx, apps/web/app/CryptoProviders.tsx, apps/web/src/components/ConnectWalletButton/ConnectWalletButton.tsx, apps/web/src/components/base-org/shared/TopNavigation/GasPriceDropdown.tsx, apps/web/src/components/base-org/shared/TopNavigation/index.tsx
* removed gas estimator and connect wallet button from `/about`, `/jobs`, `/ecosystem`, and `/getstarted`
* removed Wagmi, QueryClient, RainbowKit, and OnchainKit from `<AppProviders>`, moved into `<CryptoProviders>`
locally
=> chore: limit usage of gas estimator and connect wallet

apps/web/src/components/ConnectWalletButton/ConnectWalletButton.tsx, apps/web/src/components/Layout/UsernameNav/index.tsx
=> Fix: OCK z-index overlay

apps/web/app/(base-org)/builder-anniversary-nft/page.tsx, apps/web/app/(basenames)/layout.tsx, apps/web/app/AppProviders.tsx, apps/web/app/CryptoProviders.dynamic.tsx, apps/web/app/CryptoProviders.tsx, apps/web/app/global.css, apps/web/src/components/ConnectWalletButton/ConnectWalletButton.tsx, apps/web/src/components/base-org/shared/TopNavigation/GasPriceDropdown.tsx, apps/web/src/components/base-org/shared/TopNavigation/index.tsx
* split providers into app-level and crypto, moved crypto providers down stack to be present only when needed
* created `DynamicCryptoProviders` that are created at page-load instead of build-time
* removed `ConnectWalletButton` and `GasPriceEstimator` from certain pages
* created crypto-provider-wrapped versions of `ConnectWalletButton` and `GasPriceEstimator` for conditional rendering in the navbar
locally
homepage layout correct (incorrect style had large metallic icons)
`/getstarted` layout correct (incorrect style forced flex-col instead of flex-row)
=> fix: dynamic crypto providers

apps/web/src/components/GetConnected/GetConnected.tsx
1. Changed `href` in GetConnectedButton from Twitter to X URL (https://x.com/base)
2. Updated `title` and `aria-label` to reflect "Join us on X" instead of "Join us on Twitter"
3. Kept `iconName` and `eventName` as "twitter" to ensure compatibility with existing icons and events
=> chore: update Twitter link and labels to X branding

apps/web/next.config.js
* changed the link at base.org/registry to redirect to a new form
locally
=> chore: change `/registry` redirect link

apps/web/app/(basenames)/name/[username]/page.tsx, apps/web/src/components/Basenames/UsernameProfile/index.tsx
* Added legal disclaimer on basenames profile pages (eg `base.org/name/shrekislife`)
locally
=> chore: add disclaimer to basenames profiles

apps/base-docs/base-learn/docs/learning-objectives.md, apps/base-docs/docs/security/report.md, apps/base-docs/tutorials/docs/2_1_simple-onchain-nfts.md, apps/base-docs/tutorials/docs/2_nft-minting-with-zora.md
This pull request contains changes to improve clarity, correctness and structure.
**Description correction:**
Corrected `OpenZepplin` to `OpenZeppelin` x2.
Corrected `SLA's` to `SLAs`
Corrected `getNFftsOwned` to `getNftsOwned` x2. (the word `NFT` is written with an extra `f`).
Corrected `TokenAndMetatdata` to `TokenAndMetadata` x10. (the word `Metatdata` is written with an extra `t`).
Corrected `expect` to `except`
**All corrections were validated through:**
- Unit tests to ensure functionality remains unaffected.
- Code review for readability and correctness.
- Manual verification of affected files to confirm accuracy of changes.
Please review the changes and let me know if any additional changes are needed.
=> fix: typos in documentation files

README.md, apps/web/src/data/ecosystem.json
Updated the steps in the `README` file related to the [Updating the Base Ecosystem Page
](https://github.com/base-org/web?tab=readme-ov-file#updating-the-base-ecosystem-page) to reflect the change from `tags` to `categories` and `subcategories`!
I've also fixed the `ecosystem.json` entry for `MADNFT` which was using the previous `tags` key.
See screenshot of the updated `README` below:
=> update README steps for updating the base ecosystem page - categories/subcategories

apps/base-docs/base-learn/docs/deployment-to-testnet/deployment-to-base-sepolia-sbs.md, apps/base-docs/tutorials/docs/0_deploy-with-remix.md
I found similar issues in other documentation files that need corrections. This pull request fixes incorrect video links in the following files:
apps/base-learn/docs/deployment-to-testnet/deployment-to-base-sepolia-sbs.md
apps/base-docs/tutorials/docs/0_deploy-with-remix.md
=> Fix Incorrect Video Links in Documentation Files

apps/base-docs/base-learn/docs/introduction-to-solidity/deployment-in-remix.md, apps/base-docs/base-learn/docs/introduction-to-solidity/introduction-to-remix.md, apps/bridge/src/components/Nav/DesktopNav.tsx
Minor typos fixed in docs, significant repetition adjusted in DesktopNav.tsx
=> chore: correct typos docs

apps/web/src/data/ecosystem.json
- Updating Privy to category "Infra", subcategory "Developer Tool"
- Fixing URL for bitwave.io
=> chore: update category and broken URL and 

apps/base-docs/tutorials/docs/2_dynamic-nfts.md
In this PR, the word `jason` has been corrected to `json` in several tutorial code examples. This was done to ensure consistency and accuracy in the documentation, as `json` is the correct term for the JavaScript Object Notation format used in the examples.
Please review all code examples in the affected tutorial sections to ensure that the correction does not impact other content. The change is purely cosmetic and should not affect the functionality or logic of the tutorial.
The change has been reviewed manually by checking all affected sections. Since this is a typo fix, no additional testing is required beyond reviewing the content to ensure clarity and correctness.
=> fix JSON syntax typo in tutorial examples

apps/base-docs/base-learn/docs/imports/imports-sbs.md, apps/base-docs/docs/tools/basenames-faq.md, apps/base-docs/docs/tools/cross-chain.md
This pull request fixes broken links and updates incorrect library names in the documentation to improve accuracy and relevance.
- Corrected the library name in imports-sbs.md.
- Updated broken links in basenames-faq.md.
- Fixed outdated URLs for LayerZero in cross-chain.md.
Please verify the correctness of the links and the accuracy of the information.
Links and library names were manually checked.
=> Fix: broken links and update library names in documentation

apps/base-docs/tutorials/docs/2_dynamic-nfts.md
Fixed a typo in the OpenSea Testnet URL:
Old URL: https://testnets.opensea.io/accoun
New URL: https://testnets.opensea.io/account
Reason for Change
The original URL was missing the 't' at the end of 'account', which resulted in a broken link. This fix ensures users can properly access their NFTs on OpenSea's testnet interface.
=> OpenSea Testnet URL

apps/base-docs/docs/security/app-blocklist.md
Replaced the outdated term "WalletLink" with the correct and current terminology, "Coinbase Wallet SDK," in the section discussing standard sign-in methods for dapps.
"WalletLink" has been rebranded as "Coinbase Wallet SDK" for consistency and clarity across the ecosystem. Using outdated terminology may confuse developers, especially those new to the space.
=> docs: Update Outdated Reference to WalletLink Update app-blocklist.md

apps/base-docs/tutorials/docs/0_run-a-base-node.md
Remove geth archive snapshot url as we deprecated it
N/A
localhost
=> docs(tutorials): Remove geth archive snapshot url as we deprecated it

apps/base-docs/tutorials/docs/5_cross-chain-with-layerzero.md
Updated outdated LayerZero documentation links to the new V2 documentation structure.
Changes made:
- Updated endpoint documentation link from `/explore/layerzero-endpoint` to `/v2/home/protocol/layerzero-endpoint`
- This change reflects the current LayerZero V2 documentation structure
- Ensures users are directed to the correct, up-to-date documentation
The old link was no longer working, and this update points to the current valid documentation page.
=> Update LayerZero Endpoint documentation links

apps/base-docs/src/css/root.css
This change is important because it ensures semantic correctness and proper styling in the CSS. The `--search-font-weight` variable was previously set to `16px`, which is incorrect because `font-weight` should be a numeric value (e.g., `400`, `700`) or a keyword (e.g., `normal`, `bold`). The old value could cause browsers to ignore the variable or render text incorrectly.
By updating the value to `400`, this fix aligns the variable with the expected format for `font-weight`, preventing visual inconsistencies and ensuring proper text rendering. This change improves the reliability and readability of the CSS.
=> Fix Incorrect Font-Weight Value in CSS Variable

apps/base-docs/docs/notices/decomissioning-public-geth-archive-snapshots.md, apps/base-docs/docs/tools/basenames-onchainkit-tutorial.md
**What changed?**
*File 1:* `decommissioning-public-geth-archive-snapshots.md`
Slug was updated:
*Old:* `/decommissioning-public-geth-archive-snapshots`
*New:* `/decommissioning-public-geth-archive-snapshots`
Reason: The slug path had unnecessary issues (though visually no change is visible, perhaps fixing unseen formatting or whitespace issues).
File 2: `basenames-onchaintkit-tutorial.md`
Fix in description text:
*Old:* "teaches how to intergrate Basenames"
*New:* "teaches how to integrate Basenames"
Reason: Corrected a typo in the word `intergrate` to `integrate` for better clarity and accuracy.
**Why?**
- To fix a typo (`intergrate` → `integrate`) in the Basenames tutorial.
- To clean up or standardize the slug in the `decommissioning-public-geth-archive-snapshots.md` file.
**Notes to …
=> Minor documentation improvements: typo fix and slug update

apps/base-docs/base-learn/docs/learning-objectives.md, apps/base-docs/base-learn/docs/reading-and-displaying-data/useAccount.md, apps/base-docs/base-learn/docs/storage/simple-storage-sbs.md
**What changed?**
*Fixed formatting issues with the useAccount variable:*
Replaced useAccount`` → useAccount` in two places to correct the syntax.
*Added the missing preposition "to" in the following sentence:*
Original: "It would also be good to be able update the age value."
Fixed: "It would also be good to be able to update the age value."
**Why?**
useAccount Fix: The incorrect syntax (double backtick `) caused inconsistency and likely formatting issues in markdown rendering.
Added "to": The sentence was grammatically incorrect without the preposition "to," which disrupted the readability and correctness.
- Ensure that all occurrences of useAccount are consistently formatted as code (using backticks).
- Verify grammar improvements, particularly with prepositions …
=> Correct Formatting and Improve Grammar in Docs

apps/base-docs/tutorials/docs/5_cross-chain-with-layerzero.md
Updated an incorrect documentation link to the correct one to ensure accurate navigation for developers.
Replaced the outdated link with the current one from the LayerZero documentation.  
Manually verified that the updated link navigates to the intended documentation page.
=> Fix: Update incorrect documentation link

apps/base-docs/tutorials/docs/5_cross-chain-with-layerzero.md
I fixed 5 broken links in the 5_cross-chain-with-layerzero.md file by replacing old LayerZero V1 documentation URLs with new LayerZero V2 documentation URLs. The main change was updating the path from docs.layerzero.network/contracts/... to docs.layerzero.network/v2/developers/evm/technical-reference/... to ensure links point to the current LayerZero V2 technical documentation.
=> Broken Link

apps/base-docs/docs/tools/hardhat.md
This update addresses a minor inaccuracy in the Hardhat configuration documentation.  
In the section detailing network configuration for Base, the comment for the Sepolia-based testnet was previously written as:  
```tsx
// for Sepolia testnet
```  
This phrasing could cause confusion, as the context pertains to **Base Sepolia**, a testnet specific to the Base network built on Sepolia, rather than the Ethereum Sepolia testnet itself.  
The comment has been updated to the following for improved clarity:  
```tsx
// for Base Sepolia testnet
```  
This adjustment ensures that developers configuring their Hardhat projects understand that the testnet refers to Base's implementation and not the original Ethereum testnet.
=> docs: typo Update hardhat.md

apps/base-docs/base-learn/docs/hardhat-deploy/hardhat-deploy-sbs.md, apps/base-docs/base-learn/docs/hardhat-testing/hardhat-testing-sbs.md, apps/base-docs/docs/tools/ethers.md, apps/base-docs/docs/tools/web3.md
This PR addresses several minor spelling and grammatical issues in multiple documentation files. Specifically:
- Corrected usage of "a" vs "an" in "hardhat-deploy-sbs.md" and "hardhat-testing-sbs.md".
- Fixed "double check" to "double-check" in "web3.md".
- Updated the incorrect article usage in "ethers.md".
These changes aim to enhance the clarity and correctness of the documentation.
- Corrected typos and grammatical errors to improve readability and consistency across the documentation.
- Replaced "a" with "an" where needed, added a hyphen to "double-check," and fixed other minor errors.
Please review the grammar and spelling fixes to ensure consistency in the documentation.
- No code changes were made. The changes only affect documentation.
=> Fix typos and improve article clarity across multiple documentation files

apps/web/app/(basenames)/name/[username]/opengraph-image.tsx, apps/web/pages/api/basenames/[name]/assets/cardImage.svg.tsx, apps/web/pages/api/basenames/metadata/[tokenId].ts
This pull request addresses the following errors in the documentation:
"exists" -> "exist"
"a SVG" -> "an SVG"
"hardcoded, the list will reduce when/if they get claimed" -> "hardcoded; the list will reduce when/if they are claimed"
Thank you for your work, and I hope my pull request proves useful!
=> Fix typos and spelling errors in documentation 

.vscode/settings.json
"// use ⌘-K S to format without saving": It might be clearer to say "// use ⌘-K S (or Ctrl-K S) to format without saving", to ensure users who aren't using macOS can also understand the keyboard shortcut.
=> typo improvement

apps/base-docs/docs/tools/basenames-onchainkit-tutorial.md, apps/base-docs/docs/tools/basenames-tutorial.md
Reason: Fixed incorrect attribute name from tile to title for proper code block metadata formatting. This ensures correct syntax highlighting and documentation rendering.
Reason: Removed duplicate 'use client' directive and React import statements. These declarations only need to appear once at the top of the file. Duplicate imports are unnecessary and can cause confusion in code maintenance.
=> Remove duplicate import statements

apps/base-docs/base-learn/docs/etherscan/etherscan-sbs.md
Hey! I'm not nitpicking, but it's better to fix the extra letter because if a user types it like yours, they'll end up on a scam site.
______________
True link
=> fix etherscan-sbs.md

apps/web/src/data/ecosystem.json
Added missing `https://` protocol prefix to several URLs in ecosystem.json to ensure proper functionality of links.
Changes:
1. Stack entry:
- Before: "url": "stack.so"
- After: "url": "https://stack.so"
2. Hypersub entry:
- Before: "url": "hypersub.xyz"
- After: "url": "https://hypersub.xyz"
3. Franklin Payroll entry:
- Before: "url": "www.hellofranklin.co"
- After: "url": "https://www.hellofranklin.co"
- URLs without protocol prefix may not work correctly in all contexts
- Adding `https://` ensures consistent behavior across browsers
- Follows web standards and best practices
- Verified all modified URLs are accessible
- Confirmed links work properly in the application
- Tested in multiple browsers
=> Fix URLs in ecosystem.json

apps/base-docs/docs/tokens/token-list.md, apps/bridge/src/data/useWithdrawals.ts, apps/web/app/AppProviders.tsx, apps/web/contexts/Analytics.tsx, apps/web/pages/api/proofs/coinbase/index.ts
Changes made:
Github - GitHub 
filter to transactions - filter transactions
Not all pages needs - Not all pages need
within a - within an
provided access - provided address
Thank you for your work. I hope my pull request is helpful.
=> Fixed typos and improved clarity in documentation

apps/bridge/src/utils/transactions/isETHOrERC20Deposit.ts
Fixed a typo in the comment from “desposit” to “deposit”.
=> Fixed in the comment from “desposit” to “deposit”.

.eslintrc.js, .gitignore, CONTRIBUTING.md
This pull request addresses several minor typos and grammatical errors across the repository:
1. Corrected a grammatical error in `.eslintrc.js` to improve clarity in comments.
2. Fixed a typo in `.gitignore` to align with standard usage.
3. Adjusted phrasing in `CONTRIBUTING.md` for grammatical accuracy and consistency.
These changes improve the readability and professionalism of the codebase and documentation.
---
- These are minor, non-functional changes focused solely on correcting text. 
- No logic or functional components of the codebase have been altered.
Please review the corrections to ensure consistency with the project's tone and style.
---
- Reviewed the modified files to ensure that the corrections align with the context and do not introduce any unintended changes.
- Verified …
=> fix: several typos

apps/base-docs/docs/tools/account-abstraction.md, apps/base-docs/docs/tools/onboarding.md
This PR adds Reown to the docs, under "Account Abstraction" and "User Onboarding" doc pages. Reown was previously known as WalletConnect and Reown provides fully free and open-sourced SDKs to build both Web3 apps and Web3 wallets.
N/A
Tested locally
=> Docs Update: Adding Reown to the Docs

apps/base-docs/base-learn/docs/reading-and-displaying-data/configuring-useReadContract.md
Corrected:
useBlocNumber - useBlockNumber
I hope this change is useful and helps improve clarity.
=> Fixing Typographical Errors in Documentation

apps/base-docs/tutorials/docs/5_basename-frames.md
**Description correction:**
Corrected `frame-payme-` to `frame-payme`. In the image description, `frame-payme-` has an extra hyphen at the end of the word `payme`
=> fix: typos

apps/base-docs/tutorials/docs/5_cross-chain-with-layerzero.md
Update LayerZero Message Design Patterns documentation link
Updated the outdated documentation URL to the new V2 path for Message Design Patterns in the cross-chain tutorial documentation.
Old: https://docs.layerzero.network/contracts/message-design-patterns
New: https://docs.layerzero.network/v2/developers/evm/oapp/message-design-patterns
=> Message Design Patterns

apps/base-docs/tutorials/docs/5_deploy-with-fleek.md
This PR fixes minor typos and improves clarity in the Fleek deployment tutorial. 
**Changes include:**
- Correcting grammatical errors such as `your are` → `you are`
- Updating markdown links to ensure proper rendering.
- Corrected two minor typos for improved readability and professionalism.
- Enhanced formatting for better user experience.
Manually reviewed changes in a markdown viewer to confirm correct formatting and readability.
Please review the changes and let me know if any additional changes are needed.
=> Fix typos and minor improvements in the Fleek deployment tutorial

apps/web/next.config.js, apps/web/src/components/Basenames/RegistrationForm/index.tsx, apps/web/src/components/Basenames/RegistrationSuccessMessage/USDCClaimModal.tsx, apps/web/src/components/Basenames/RegistrationSuccessMessage/index.tsx
Add USDC claim modal for eligible addresses for IRL activation. 
=> Add USDC claim modal for eligible addresses

apps/base-docs/tutorials/docs/0_deploy-with-tenderly.md
What changed & Why?
Updated Twitter URL to match the format used in other documentation links:
[Twitter] (https://twitter.com/TenderlyApp)
[Twitter] (https://x.com/TenderlyApp)
This change maintains consistency with other X/Twitter links across the documentation.
Testing: ✅ Link works correctly
=> Twitter URL 

apps/base-docs/tutorials/docs/2_paymaster-sponsor-using-wagi.md
I fixed a typo in the 2_paymaster-sponsor-using-wagi.md file by correcting the word "Experimenal" to "Experimental" in a section heading.
Specific Change:
Before:
:::info Experimenal Hooks and Capabilities
After:
:::info Experimental Hooks and Capabilities
This ensures accurate spelling and improves the readability of the documentation.
=> Typo fix Update 2_paymaster-sponsor-using-wagi.md

apps/base-docs/tutorials/docs/0_deploy-with-hardhat.md
Basescan now requires an API key to verify contracts on Base Sepolia; this change updates to clarify where to get one
N/A
Localhost
=> docs(hardhat): Clarify API key is required

apps/web/src/components/GetStarted/GetNoticed.tsx
* Added marketing amplification guidelines to Get Noticed section of `/build`
locally
=> add marketing amplification guidelines

apps/base-docs/docs/tools/block-explorers.md
I noticed a small typo in the Routescan section where the URL was pointing to `superscan.network` instead of the correct `routescan.io`.
I've updated the link to the proper destination.
This should help avoid any confusion for users trying to access Routescan.
=> docs: Fix incorrect URL in Routescan doc Update block-explorers.md

apps/base-docs/docs/tools/data-indexers.md
The issue is the capitalization of GhostGraph.xyz. URLs are case-insensitive, but it's a best practice to use lowercase for consistency and to avoid potential issues with certain systems or browsers.
Corrected
=> docs: typo fix Update data-indexers.md

apps/web/contexts/Analytics.tsx, libs/base-ui/utils/logEvent.ts
- Added AnalyticsContext enum to replace string-based context values
- Updated CCAEventData type to use AnalyticsContext enum
- Renamed React context to AnalyticsReactContext to avoid naming conflicts
- Consolidated all known context values into a single enum
These changes improve type safety by preventing typos in context values and make it easier to track all possible analytics contexts in one place. This resolves the TODO comment about converting context to enum.
- The change is mostly type-level, with no runtime behavior changes
- All existing context string values have been preserved in the enum
- The enum is split into two sections: Navigation/UI contexts and Feature-specific contexts
- The React context was renamed to avoid naming …
=> refactor: convert analytics context from string to enum

apps/base-docs/sidebars.js
Add a link to base.org/stats in our docs
Localhost
=> chore(sidebar): Add link to base.org/stats

apps/base-docs/docs/tools/onboarding.md, apps/base-docs/tutorials/docs/2_1_simple-onchain-nfts.md
Hi! This PR addresses broken links in the documentation, ensuring they now point to the correct and updated resources. The changes are focused on maintaining seamless navigation and providing accurate references.
=> fix: update broken links in docs

apps/web/src/components/Basenames/UsernameProfileSectionBadges/Badges/index.tsx, apps/web/src/components/Basenames/UsernameProfileSectionBadges/hooks/useBuildathon.ts
- Fix "Error Triags" -> "Error Flags" in badge description
- Fix "particpant" -> "participant" in comment
These changes correct spelling errors in both user-facing content and code comments to improve clarity and professionalism.
Files changed:
- apps/web/src/components/Basenames/UsernameProfileSectionBadges/Badges/index.tsx
- apps/web/src/components/Basenames/UsernameProfileSectionBadges/hooks/useBuildathon.ts
=> Fix typos in Base Learn badge description and comments

apps/web/next.config.js, apps/web/src/components/Basenames/UsernameProfileTransferOwnershipModal/context.tsx, apps/web/src/hooks/useRegisterNameCallback.ts, apps/web/src/hooks/useWriteBaseEnsTextRecords.ts, apps/web/src/hooks/useWriteContractWithReceipt.ts, apps/web/src/hooks/useWriteContractsWithLogs.ts
- Fixed minor spelling errors such as "successfull" to "successful" and "reigstration" to "registration" in various files.
- Ensures that code comments are clear, professional, and consistent.
=> Fix typographical errors

apps/web/src/components/base-org/Button/index.tsx
Hi! Corrected multiple typos in `index.tsx`, specifically changing "buton" to "button" in comments to ensure clarity and maintain code readability. These changes are minor but contribute to improving the overall quality of the codebase.
=> fix: typo correction index.tsx

apps/web/src/data/ecosystem.json
Rebrand GhostLogs to Ghost
Focus on the indexers (subgraphs) instead of gasless logs
Simple changes
=> revise ghostlogs to ghost with rebrand

apps/web/src/components/base-org/root/SlidingTextSection/index.tsx
Add Germany & Turkish translations of `Base is for everyone` on homepage
=> chore: add Germany & Turkish translations of `Base is for everyone` on homepage

apps/base-docs/tutorials/docs/4_account-abstraction-with-privy-and-base-paymaster.md, apps/base-docs/tutorials/docs/5_cross-chain-with-layerzero.md
Hi! I updated incorrect and outdated links in two tutorial files:
- Fixed duplicate and broken links in `4_account-abstraction-with-privy-and-base-paymaster.md`.
- Corrected a broken link in `5_cross-chain-with-layerzero.md`.
=> fix: update broken links in `tutorials/docs`

apps/base-docs/docs/building-with-base/quickstart.md
- Remove quotes from environment variables in .env example for better consistency with common practices
- Add warning message about requiring test ETH before contract deployment to prevent failed transactions
- Clean up excessive line breaks at the end of the document
- Improve readability by adding proper spacing after the foundryup command
1. Simplified .env variables format
2. Added explicit warning about test ETH requirements
3. Reduced redundant <br/> tags
4. Fixed spacing inconsistencies
- Verified all markdown formatting renders correctly
- Confirmed all links are working
- Checked that code examples are properly formatted
=> docs: Improve quickstart guide formatting and environment setup clarity

apps/web/contexts/Analytics.tsx, libs/base-ui/utils/logEvent.ts
=> fix: type error in Analytics and logEvent

apps/web/src/components/base-org/shared/TopNavigation/GasPriceDropdown.tsx
current:
This fixes the denomination from "Mgwei" to "Mwei":
=> fix: GasPriceDropdown denomination

README.md, apps/web/src/components/Ecosystem/Card.tsx, apps/web/src/components/Ecosystem/Content.tsx, apps/web/src/components/Ecosystem/EcosystemFilters.tsx, apps/web/src/data/ecosystem.json
* add AI as a top-level ecosystem category
* move projects from `category: infra, subcategory: ai` to AI category
* update card component to only show a single chip if the category and subcategory have the same value
=> feat: add AI ecosystem category

apps/web/app/(base-org)/ecosystem/page.tsx
Updates the title text on the Ecosystem page
Localhost
=> chore(ecosystem): Update title text

.codeflow.yml
We no longer deploy or use this image anymore, so remove it (it's currently failing to build).
=> Remove the Docker build of the bridge image

apps/web/src/components/Ecosystem/Content.tsx
* removed `ai` subcategory from `infra` — prevents toggling AI filter when Infra is selected
locally
=> fix: ecosystem filters

apps/web/src/components/GetStarted/GetNoticed.tsx
Removes OCN from the Resources page
Before:
After:
Localhost
=> chore(resources): Remove OCN

apps/web/src/components/GetStarted/Essentials.tsx
Updated Office Hours tile to be Virtual Events tile as well as Luma event page link from /base-officehours to /base-virtualevents
Please confirm that the Event Logging part of the URL will be unaffected? It seems to have the same URL ending as the rest of the URLs
We will update the Luma link from Office Hours to Virtual Events once approved or acked by approver.
=> Update Office Hours tile

apps/base-docs/docs/pages/buildathons/2025-02-flash.mdx
Fix flashblock buildathon doc page to use flashblock RPC only
=> Fix flashblock buildathon doc page to use flashblock RPC only

apps/base-docs/docs/pages/cookbook/account-abstraction/account-abstraction-on-base-using-privy-and-the-base-paymaster.mdx
Hello! I fixes a dead link in the `account-abstraction-on-base-using-privy-and-the-base-paymaster.mdx` file. The old link pointed to a non-existent page for the Privy website. It has been updated to the correct and current URL.
=> fix: update dead link to Privy website

apps/base-docs/docs/pages/cookbook/use-case-guides/creator/convert-farcaster-frame-to-open-frame.mdx
File Changed: deployment_instructions.md
Old Word: Redploy your frame
New Word: Redeploy your frame
Reason for Change: Corrected a typographical error to maintain professionalism and ensure clear communication.
=> Fix Typographical Error in Deployment Instructions

apps/base-docs/docs/pages/cookbook/nfts/thirdweb-unreal-nft-items.mdx, apps/base-docs/docs/pages/cookbook/use-case-guides/finance/access-real-world-data-chainlink.mdx, apps/base-docs/docs/pages/learn/reading-and-displaying-data/useAccount.md
Hey! I noticed a few broken links in the docs and updated them to their correct locations
=> docs: fix dead links across documentation

apps/web/src/components/Basenames/RegistrationForm/index.tsx
* wrap the isPremiumActive declaration in a Boolean
* this ensures that the claim form doesn't have an extraneous "0" string literal
Before
After
locally
=> fix: make `isPremiumActive` a boolean

apps/base-docs/docs/pages/builderkits/onchainkit/paymaster/erc20-paymaster.mdx, apps/base-docs/docs/pages/builderkits/onchainkit/paymaster/quickstart-guide.mdx
This PR includes the following changes:
Corrected `Adress` → `Address`
Corrected `exsiting` → `existing`
These changes enhance documentation accuracy and readability.
=> Update paymaster documentation and fix address typo

apps/base-docs/docs/pages/builderkits/onchainkit/paymaster/security.mdx, apps/base-docs/docs/pages/builderkits/onchainkit/paymaster/troubleshooting.mdx
This PR fixes two typos in the paymaster documentation:
- Corrects `reccomend` to `recommend` in `security.mdx`
- Corrects `occured` to `occurred` in `troubleshooting.mdx`
These changes improve the documentation readability and accuracy.
=> Fix typos in paymaster documentation

apps/base-docs/docs/pages/cookbook/use-case-guides/commerce/build-an-ecommerce-app.mdx
Old Header: `# Build a eCommerce
New Header: `# Build an eCommerce
Reason: "an" is grammatically correct before "eCommerce" for better readability.
=> Fix Typographical Errors in Documentation

apps/base-docs/docs/pages/use-cases/defi-your-app.mdx
I’ve corrected a typo in the "Swap Settings" section where "cusotomizable" was used instead of the correct spelling, "customizable."
=> docs: fix typo in "Swap Settings" section

apps/web/src/components/Builders/Shared/LiveDemo/index.tsx
Added a button that opens OCK playground in a new tab
Locally
=> chore: add link to OCK Playground

apps/bridge/src/utils/hooks/usePrepareERC20DepositTo.ts
This PR updates the L1StandardBridge import and implementation in the bridge utilities:
- Fixed import statement for L1StandardBridge
- Updated bridge configuration to use correct L1StandardBridge reference
- Ensures consistent bridge implementation across deposit functions
These changes improve the stability and correctness of the bridge integration.
=> fix: fix `L1StandardBridge` import and usage in `usePrepareBridge` hook

apps/base-docs/docs/components/Button/index.tsx
I fixed a typo in the button styles where "buton" was used instead of "button". This ensures proper spelling and consistency in the code.
Please review the changes to ensure the correct spelling of "button" in the styles. There should be no other changes to the functionality.
The code was reviewed for correctness. No functional tests are needed as this change only affects the style definitions.
=> fix: Fix typo in button styles

libs/base-ui/components/Layout/Nav/Banner.tsx
Removed unnecessary dependencies (`ActionType`, `ComponentType`, `AnalyticsEventImportance`) from the `useCallback` dependency array in `linkClick`. These are imported constants and don’t change between renders, so including them was unnecessary. This prevents unnecessary re-creations of the function.  
This is a small cleanup to improve performance and ensure best practices with React hooks. Let me know if you see any edge cases I might have missed.  
Manually tested by checking that the `linkClick` function still fires correctly and that React doesn’t trigger unnecessary re-renders. No functional changes expected.
=> fix: clean up unnecessary dependencies in useCallback

apps/bridge/src/utils/hooks/useCCTPBridgeStatus.ts, apps/bridge/src/utils/hooks/useIsWalletConnected.ts, apps/web/src/utils/usernames.ts
=> fix: fix code comments and variables errors

apps/base-docs/docs/pages/identity/smart-wallet/guides/spend-permissions/api-reference/spendpermissionmanager.mdx
Added `revokeAsSpender` function to documented interface of Smart Wallet's Spend Permissions.
=> Add revokeAsSpender function to SpendPermissionManager interface

apps/base-docs/docs/contexts/CookieBannerWrapper.tsx, apps/base-docs/docs/pages/builderkits/onchainkit/identity/get-avatars.mdx, apps/base-docs/docs/pages/builderkits/onchainkit/identity/get-names.mdx, apps/base-docs/docs/pages/builderkits/onchainkit/identity/types.mdx, apps/base-docs/docs/pages/builderkits/onchainkit/identity/use-avatars.mdx, apps/base-docs/docs/pages/builderkits/onchainkit/identity/use-names.mdx, apps/base-docs/sidebar.ts
Add OnchainKit docs for `getNames`, `useNames`, `getAvatars`, `useAvatars`. 
=>  chore: Add OnchainKit docs for getNames, useNames, getAvatars, and useAvatars.

apps/base-docs/sidebar.ts
Fix Mint hooks path. 
`Page not found` error for the OnchainKit Mint hooks:
- https://docs.base.org/builderkits/onchainkit/mint/use-token-details
- https://docs.base.org/builderkits/onchainkit/mint/use-mint-details
=> fix: OnchainKit Mint hooks navigation

apps/web/src/components/Ecosystem/Card.tsx, apps/web/src/data/ecosystem.json
* removed duplicate entry in ecosystem json that caused filtering / display issues
* added text truncation on project descriptions to limit to 200 chars
after:
normal font size:
very large font:
before (note incorrect 20lab inclusion because it is a duplicate entry, causing a duplicate key react issue):
* used string slicing (always showing 200 chars) instead of line clamping / height restrictions for accessibility reasons
* this approach always shows the same number of characters regardless of text size
locally
=> chore: truncate ecosystem project descriptions

apps/web/app/layout.tsx
* added black background to layout so that scrolling doesn't result in white background peeking out
after:
before:
=> fix: add black background behind content body

apps/web/app/global.css, apps/web/app/layout.tsx
* removed bg color from global layout
* added `overscroll-behavior: none` to global css to prevent the "peaking" background color
locally, vercel preview
=> fix: prevent overscroll to avoid "peaking" background colors

apps/base-docs/docs/pages/chain/base-contracts.mdx
We re-deployed our Sepolia `FaultDisputeGame` and `PermissionedDisputeGame` contracts today to prepare for testnet Pectra upgrades.
You can confirm the new FDG and PDG contract addresses [here](https://github.com/base/contract-deployments/blob/main/sepolia/2025-03-12-upgrade-fault-proofs/addresses.json).
=> fix: update dispute game addresses

apps/base-docs/docs/pages/builderkits/onchainkit/api/get-portfolios.mdx
* added supported network info to OnchainKit's `getPortoflios` endpoint documentation
vercel preview:
=> fix: add supported network info to getPortfolios doc

apps/base-docs/docs/pages/builderkits/onchainkit/identity/use-address.mdx, apps/base-docs/docs/pages/builderkits/onchainkit/identity/use-avatar.mdx, apps/base-docs/docs/pages/builderkits/onchainkit/identity/use-avatars.mdx, apps/base-docs/docs/pages/builderkits/onchainkit/identity/use-name.mdx, apps/base-docs/docs/pages/builderkits/onchainkit/identity/use-names.mdx
Update Identity docs with new TanStack support info. 
- Docs update from [feat: Enhance Identity hooks with full TanStack Query options support](https://github.com/coinbase/onchainkit/pull/2116#top)
- [] base.org
- [] base.org/build
=> chore: Update OCK Identity hooks with TanStack support

apps/base-docs/sidebar.ts
Add orphaned page, "Custom Supplemental Providers" to the side navigation.
=> chore: add Custom Supplemental Providers to sidebar

apps/base-docs/docs/pages/builderkits/onchainkit/identity/badge.mdx, apps/base-docs/docs/pages/builderkits/onchainkit/identity/identity-card.mdx
All links in the Badge and Identity Card documentation page are broken - this PR fixes them. 
Tested locally. 
- [] base.org
- [] base.org/build
=> fix: OnchainKit Badge and Identity Card links

apps/base-docs/sidebar.ts
It's difficult to find a few pages for Sub Accounts. This PR adds them to the sidebar
| Before | After |
|--------|--------|
| ![DS 2025-03-20 at 11 20 04@2x](https://github.com/user-attachments/assets/bb799838-29c3-423d-82ba-f84d40e342f4) | ![DS 2025-03-20 at 11 19 36@2x](https://github.com/user-attachments/assets/fed2b611-8c68-483c-93bb-eeb51465ee64) |
- [] base.org
- [] base.org/build
=> docs: add sub-pages to navigation for Sub Accounts

apps/base-docs/docs/contexts/CookieBannerWrapper.tsx, apps/base-docs/docs/pages/chain/bridge-an-l1-token-to-base.mdx
* Fix `cookie-banner` import to fix destructure error
* FIx 404 link to Optimism docs + Base contract addresses page
=> docs: Fix 404 on Base Token List page

apps/web/app/(basenames)/name/[username]/configure-frames/page.tsx, apps/web/app/(basenames)/name/[username]/opengraph-image.tsx, apps/web/app/(basenames)/name/[username]/page.tsx, apps/web/app/(basenames)/names/page.tsx
We have been getting this error, and running the codemod to update our `params` usage fixes the problem ahead of next.js's deprecation of the pattern. 
```
Error: Route "/name/[username]" used `params.username`. `params` should be awaited before using its properties. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis
at username (app/(basenames)/name/[username]/page.tsx:38:71)
36 |
37 | export default async function Username({ params }: UsernameProfileProps) {
> 38 |   let username = await formatDefaultUsername(decodeURIComponent(params.username) as Basename);
|                                                                       ^
39 |   await redirectIfNotNameOwner(username);
40 |
41 |   const usernameProfilePageClasses = classNames(
Error: Route …
```
=> @next/codemod@canary next-async-request-api .

apps/base-docs/docs/pages/builderkits/onchainkit/identity/badge.mdx, apps/base-docs/docs/pages/builderkits/onchainkit/identity/identity-card.mdx, apps/base-docs/docs/pages/builderkits/onchainkit/identity/identity.mdx, apps/base-docs/docs/pages/builderkits/onchainkit/identity/types.mdx
Adding documentation for the following OnchainKit feature - [feat: Add Badge tooltip display](https://github.com/coinbase/onchainkit/pull/2140#top)
The Identity, IdentityCard, and Badge components now support a tooltip parameter. 
BaseWeb
BaseDocs
=> chore: Add OCK Badge, Identity, and IdentityCard tooltip docs

apps/web/app/CryptoProviders.dynamic.tsx, apps/web/app/CryptoProviders.tsx
* change onchainkit config to use `base` mode instead of default
BaseWeb
BaseDocs
=> feat: use `base-light` for ock components

apps/base-docs/docs/pages/chain/run-a-base-node.mdx
Base now only support Reth snapshots.
BaseWeb
- [] base.org
BaseDocs
=> fix: removes reference to geth archive snapshot

apps/base-docs/docs/pages/chain/run-a-base-node.mdx
This PR adds copy that was overwritten by an older version of this page alongside the recent docs.base.org update. It readds the overwritten copy.
N/A
Localhost
BaseWeb
BaseDocs
=> chore(run-a-base-node): Re-add snapshot deprecation copy

apps/base-docs/docs/pages/chain/wallet.md
I corrected a small typo in the "Send via text" section. The word "sShare" was replaced with the correct spelling "**Share**" in the sentence: "Copy the link and Share it on any platform."
=> docs: Fix typo in "Send via text" section

apps/base-docs/docs/pages/identity/smart-wallet/quickstart/quick-demo.mdx
Incorrect reown link included in quick demo guide
One URL Fixed
Locally
BaseWeb
- [] base.org
BaseDocs
=> fix broken reown link

apps/base-docs/docs/pages/cookbook/smart-contract-development/foundry/verify-contract-with-basescan.md, apps/web/src/components/Bootcamp/WhatsIncluded.tsx
1️⃣ File: docs/cookbook/smart-contract-development/foundry/verify-contract-with-basescan.md
Old: https://docs.base.org/base-learn/docs/welcome/
New: https://docs.base.org/learn/welcome/
2️⃣ File: apps/web/src/components/Bootcamp/WhatsIncluded.tsx
Old: https://docs.base.org/base-learn/docs/welcome/
New: https://docs.base.org/learn/welcome/
=> Fix Broken Links to Base Learn Docs 

apps/base-docs/docs/pages/identity/smart-wallet/guides/sub-accounts/incorporate-spend-permissions.mdx, apps/base-docs/docs/pages/identity/smart-wallet/guides/sub-accounts/overview.mdx, apps/base-docs/docs/pages/identity/smart-wallet/guides/sub-accounts/setup.mdx
Updated Sub account guide to make it easier to find the final repo that is a reference for the guide. These changes were made based on feedback. 
Specific changes:
1. Link to the repo file directly when referenced
2. Change from using "tip" sections to sub sections to reference guide repo
3. show git command to clone guide repo
Yes. Preview: https://web-base-docs-2gv9rfypd-coinbase-vercel.vercel.app/identity/smart-wallet/guides/sub-accounts/overview
BaseWeb
- [] base.org
BaseDocs
=> chore: make sub account guide repo easier to find

apps/web/src/components/Builders/MiniKit/Hero.tsx
Fixed broken Get Started URL
BaseWeb
- [] base.org
BaseDocs
=> Fix broken get started url on MiniKit product page

apps/web/src/utils/kv/index.ts
* changed the default KV url to handle both dev and prod environments
base.org/api/registry/entries will load data
BaseWeb
BaseDocs
=> fix: fix default kv url

apps/web/src/data/ecosystem.json
Updated joker race web link
**What changed? Why?** 
The previous link on base ecosystem page is invalid and does not go to the intended page [https://www.jokerace.xyz/](url)
This is what the previous link shows
The new link has been tested and it’s their updated link on all their social media pages
=> Fix joker race website link

apps/base-docs/docs/pages/cookbook/IPFS/deploy-with-fleek.mdx
I spotted a typo in the tutorial: "Once your are connected, click the `Visit Dashboard` button." The word "your" was corrected to "you" for proper grammar. The sentence now reads: "Once **you** are connected, click the `Visit Dashboard` button."
Thanks
The change was reviewed manually by reading through the tutorial text. There is no need for additional testing since it’s a minor text correction.
=> docs: Fix typo in tutorial text

apps/base-docs/docs/pages/identity/smart-wallet/guides/erc20-paymasters.mdx
The original sentence contained a redundant "the," which was a typographical error. Removing the duplicate word improves the clarity and readability of the documentation.
=> Fix Typographical Error 

apps/base-docs/docs/pages/builderkits/minikit/overview.mdx
Remove useTBADeepLink documentation from MiniKit overview
BaseWeb
- [] base.org
BaseDocs
=> fix: Remove useTBADeepLink documentation from MiniKit overview

apps/base-docs/docs/pages/builderkits/onchainkit/fund/get-onramp-buy-url.mdx
We replaced the incorrect anchor `getonrampurlwithsessiontokenparams` with the correct anchor `getonrampurlwithprojectidparams` so the link points to the correct type section.
=> Correction Explanation

apps/web/package.json, apps/web/pages/api/checkNftProof/index.ts, apps/web/pages/api/registry/entries.ts, apps/web/pages/api/registry/featured.ts, apps/web/src/utils/proofs/sybil_resistance.ts, yarn.lock
* reverted to vercel/kv implementation
* this enables us to continue to deploy to base/web while we investigate the memory leak issue
BaseWeb
BaseDocs
=> fix: reimplement vercel/kv

apps/base-docs/docs/pages/learn/deployment-to-testnet/contract-verification-sbs.mdx, apps/base-docs/docs/pages/learn/hardhat-forking/hardhat-forking.mdx, apps/base-docs/docs/pages/use-cases/defi-your-app.mdx, apps/base-docs/docs/pages/use-cases/launch-ai-agents.mdx, apps/base-docs/docs/pages/use-cases/onboard-any-user.mdx
- Fixed several typos across multiple documents in the Base web documentation.
- Corrected minor spelling and formatting errors in the following files:
- `contract-verification-sbs.mdx`: Fixed the phrase "Please select Compiler Type" from `_Solidity (Single file)_` to `Solidity (Single file)`.
- `hardhat-forking.mdx`: Fixed incorrect method access, replacing `ethers.formatUnits` with `ethers.utils.formatUnits`.
- `defi-your-app.mdx`: Corrected the misspelling of "unidiectional" to "unidirectional".
- `launch-ai-agents.mdx`: Fixed the typo "significnatly" to "significantly".
- `onboard-any-user.mdx`: Corrected the typo "createion" to "creation".
**Notes to reviewers:**
- All changes are purely for typo fixes and should not affect the functionality of the documents. …
=> Typos fix base web

apps/web/src/components/base-org/root/SlidingTextSection/index.tsx
* doubled the animation duration of the "Base is for everyone" marquee
* Base is for everyone, not just speed readers 😂
https://github.com/user-attachments/assets/7144dccb-850d-4235-87b7-5ec99dad0aa1
BaseWeb
BaseDocs
=> fix: slow down "Base is for everyone" marquee

apps/web/src/components/Builders/Stories/BottomCta/index.tsx
Updates link that should go to quick start instead of back to stories
BaseWeb
BaseDocs
=> fix(stories): Incorrect link

apps/base-docs/docs/pages/identity/smart-wallet/features/sub-accounts.mdx
Added information about Smart Wallet Sub Accounts scoping 
BaseWeb
- [] base.org
BaseDocs
=> chore: add domain scoping info to sub account doc

apps/base-docs/docs/pages/identity/smart-wallet/guides/sub-accounts/creating-sub-accounts.mdx, apps/base-docs/docs/pages/identity/smart-wallet/sdk/snippets/sdk-parameters.mdx, apps/base-docs/docs/pages/identity/smart-wallet/sdk/sub-account-reference.mdx
Update sub account docs based on API changes
n/a
Manually
BaseWeb
BaseDocs
=> Update docs to match new canary

apps/base-docs/docs/pages/identity/smart-wallet/guides/spend-permissions/overview.mdx
- Removed the note about batch approvals for spend permissions because this isn't true until/unless we implement the necessary changes in the frontend.
- Added a note in the "revoke" section that calls out `revokeAsSpender` as an option for spenders to revoke their own permissions without user interaction, since an app needed this and wasn't aware of the option.
Linear issue: https://linear.app/coinbase/issue/BW-1440/update-spend-permissions-docs
Removed bit about batches
Added bit about `revokeAsSpender`
BaseWeb
- [] base.org
BaseDocs
- …
=> Update Spend Permission docs

apps/base-docs/docs/pages/cookbook/client-side-development/introduction-to-providers.mdx
=> fix error introduction-to-providers.mdx

apps/base-docs/docs/pages/identity/smart-wallet/guides/spend-permissions/overview.mdx
- Fixed "perissions" typo in spend-permissions overview
=> fix: fix permissions typo

apps/base-docs/docs/pages/cookbook/smart-contract-development/hardhat/deploy-with-hardhat.md, apps/base-docs/docs/pages/learn/deployment-to-testnet/contract-verification-sbs.mdx, apps/base-docs/docs/pages/learn/deployment-to-testnet/deployment-to-base-sepolia-sbs.mdx
This pull request updates incorrect links to the Base network faucets in multiple documentation files. The old links pointed to https://docs.base.org/tools/network-faucets, which has been replaced with the correct link https://docs.base.org/chain/network-faucets.
=> Fix Incorrect Faucet Links in Documentation 

yarn.lock
What:
* reverted yarnlock to version from [last stable](https://github.com/base/web/pull/2093) 
* then reinstalled deps to get minimum viable changes
Why:
* deploys after PR 2093 have caused CPU utilization / memory leak issues
* we've already reverted the code changes that were made between the stable version and the first incidence of the issue
* another change between the stable PR and the first incidence was an update of the yarn lock file, updating many dependency versions
* this PR attempts to revert yarnlock to as close to the stable version as possible
Locally and vercel previews. 
This will be considered a success if, after deployment, it resolves the CPU utilization issues.
Have you tested the following …
=> fix: update yarnlock

apps/base-docs/docs/pages/builderkits/onchainkit/wallet/wallet-modal.mdx
Updated the `WalletModal` docs to show additional wallet support feature for `Rabby`, `Trust`, and `Frame` wallet. These can be enabled through the new `OnchainKitProvider` `supportedWallets` parameter.
Update WalletModal docs after this source code change - [feat: Add Rabby, Trust, and Frame wallet connection support](https://github.com/coinbase/onchainkit/pull/2178#top)
BaseWeb
- [] base.org
BaseDocs
=> chore: Update WalletModal docs to support Rabby, Frame, and Trust wallet connection

apps/base-docs/docs/pages/learn/control-structures/control-structures.mdx
Fix logical error in requireAddEvenNumbers function
File: apps/base-docs/base-learn/docs/control-structures/control-structures.md
Change:
Old: require(_second % 2 != 0, "Second number is not even");
New: require(_second % 2 == 0, "Second number is not even");
Reason:
The current condition checks for odd numbers (!= 0) while the error message and function name indicate it should check for even numbers. Changed to check for even numbers (== 0) to align with function's purpose and maintain consistency with other examples.
=> Fix logical error in requireAddEvenNumbers function

apps/base-docs/docs/public/serve.json
https://docs.base.org/identity/smart-wallet/guides/react-native-integration is outdated and should redirect to https://docs.base.org/identity/smart-wallet/quickstart/react-native-project
BaseWeb
- [] base.org
BaseDocs
=> fix: add redirect for broken link in Smart Wallet docs

apps/base-docs/package.json, apps/web/package.json, apps/web/src/hooks/useBaseEnsName.ts, yarn.lock
Updating the OnchainKit docs to their latest version - v0.38.3
BaseWeb
- [] base.org
BaseDocs
=> OnchainKit Docs: latest

apps/web/app/CryptoProviders.tsx, apps/web/app/global.css, apps/web/package.json, apps/web/src/components/Basenames/ConfigureFramesPageContent/FrameBuilder.tsx, apps/web/src/components/Basenames/UsernameProfileSectionFrames/Context.tsx, yarn.lock
* replaced rainbowkit with walletmodal
* used `useBoolean` hook to control WalletModal visibility in FramesContext
* added raby and trust wallet to onchainkit config
BaseWeb
BaseDocs
=> chore: replace rainbowkit with onchainkit's WalletModal

apps/base-docs/docs/pages/builderkits/onchainkit/config/is-base.mdx, apps/base-docs/docs/pages/builderkits/onchainkit/config/is-ethereum.mdx, apps/base-docs/package.json, apps/web/package.json, yarn.lock
Improve isBase and isEthereum code samples to be more clear and comprehensive. 
This PR also bumps the OnchainKit version to the latest, `v0.38.5`
BaseWeb
- [] base.org
BaseDocs
=> chore: Improve isBase and isEthereum code examples

apps/web/package.json, apps/web/pages/api/checkNftProof/index.ts, apps/web/pages/api/registry/entries.ts, apps/web/pages/api/registry/featured.ts, apps/web/src/utils/datastores/kv/index.ts, apps/web/src/utils/proofs/sybil_resistance.ts, yarn.lock
What:
* implemented KV client using ioredis
* replaced @vercel/kv with ioredis for KV client
* updated all KV usage from @vercel/kv to ioredis
Why:
1. vercel is deprecating their package
2. we are migrating the datastore to CBHQ infra, which is incompatible with the vercel package
* Tested in dev env, hitting API 1x/s to simulate prod load
BaseWeb
BaseDocs
=> chore: use ioredis as kv client

apps/web/src/components/Builders/Landing/Hero/SearchModal.tsx, apps/web/src/components/Builders/Shared/BottomCta/index.tsx
https://docs.base.org/llms.txt is outdated - https://docs.base.org/llms-full.txt is the new valid URL
BaseWeb
- [] base.org
BaseDocs
=> chore: Update llms-full.txt links

apps/web/Dockerfile, apps/web/scripts/startup.sh
* created `startup.sh` to fetch env vars from config service
* integrated `startup.sh` into dockerfile
* In dev env
BaseWeb
- [] base.org
BaseDocs
=> feat: update startup process to use envmapper

apps/base-docs/docs/public/serve.json, apps/base-docs/sidebar.ts
I added a few patches to Smart Wallet sidebar and redirects following the latest restructuring
BaseDocs
=> Smart Wallet Docs: Add patches to sidebar and serve

apps/base-docs/docs/components/SignatureComponents.tsx, apps/base-docs/docs/pages/builderkits/onchainkit/signature/signature.mdx, apps/base-docs/docs/pages/builderkits/onchainkit/signature/types.mdx, apps/base-docs/sidebar.ts
Playground links:
* [Signature](https://web-base-docs-git-alessey-docs-signature-coinbase-vercel.vercel.app/builderkits/onchainkit/signature/signature)
* [Types](https://web-base-docs-git-alessey-docs-signature-coinbase-vercel.vercel.app/builderkits/onchainkit/signature/types)
BaseWeb
- [] base.org
BaseDocs
=> docs: add signature docs

apps/base-docs/sidebar.ts
BaseWeb
- [] base.org
BaseDocs
=> Add Fetch Permissions API page to Spend Permissions technical reference

apps/base-docs/sidebar.ts
Small change to the sidebar, in order to explicitly expose guides in the Sub Accounts sub section.
BaseDocs
=> Expose guides in Sub Accounts Sub-section

apps/base-docs/docs/pages/chain/bridges-mainnet.mdx, apps/base-docs/docs/public/llms-full.txt
Superbridge.app was erroneously referenced in FAQ as Superbridge.com
Localhost
BaseWeb
BaseDocs
=> docs(bridges): Fix incorrect references to Superbridge.app

apps/base-docs/docs/pages/chain/bridges-mainnet.mdx
Fixed an unnatural phrase in a comment. “Only can” was awkward and incorrect in English. Updated it to:  
**“This implementation can only bridge assets to Base.”**  
This version is grammatically correct and easier to understand.
Just a small language fix in a comment — no logic or functionality touched.
No functional changes, so no testing required.
BaseWeb  
BaseDocs
=> docs: fix awkward phrasing in bridge implementation comment

apps/base-docs/docs/pages/chain/run-a-base-node.mdx
Updates callout to mention that Geth Archive nodes are now no longer officially supported and to use Reth instead
N/A
Localhost
BaseWeb
BaseDocs
=> docs(node): Update note mentioning Geth Archive support

apps/web/src/components/Basenames/RegistrationFaq/index.tsx
Fixed a broken link in the Basenames FAQ section on base.org/names. The "tutorial here" link in the answer to "I am a builder. How do I integrate Basenames to my app?" was pointing to a non-existent URL (https://docs.base.org/docs/basenames-tutorial-with-onchainkit) which returns a 404 error. 
This PR updates the link to the correct URL (https://docs.base.org/identity/basenames/basenames-onchainkit-tutorial) to ensure builders can easily access the proper documentation when integrating Basenames into their applications.
This is a simple link correction in the FAQ component. The new link directs to the existing OnchainKit tutorial page that contains the correct integration instructions.
- Verified the new link …
=> Fix: Correct broken Basenames OnchainKit tutorial link in FAQ

apps/web/package.json, apps/web/src/cdp/constants.ts, yarn.lock
What: update to nextjs v15.3.1
Why:
* addresses cloudflare rule set up due to the [nextjs middleware bug](https://vercel.com/blog/postmortem-on-next-js-middleware-bypass)
BaseWeb
BaseDocs
=> chore: update next

apps/web/app/CryptoProviders.tsx
- Passed the app name (Base) to OnchainKitProvider
- Without the name, OnchainKit defaults to "Dapp", which doesn't look good in the keys.coinbase.com popup
- Manually
| Before  | After |
| ------------- | ------------- |
| <img src="https://github.com/user-attachments/assets/029de90c-aea8-4f4d-8336-d48d8ee96494">  | <img src="https://github.com/user-attachments/assets/930dec62-7634-4328-801b-6c094613d68c"> |
BaseWeb
BaseDocs
=> chore: add app name to OnchainKitProvider

apps/web/src/hooks/useRegisterNameCallback.ts, apps/web/src/utils/usernames.ts
Basenames have historically been registered using the vestigial `addr` fwd resolution path. This is technically not correct since `addr` refers to the Ethereum Mainnet cointype (`60`). This PR adds the ENSIP-11 compliant forward resolution data to register new names with the Base chain id cointype `0x80002105`. 
Registered a name on testnet and validated that we got the chainid address record set as expected: [see log 222](https://sepolia.basescan.org/tx/0x9bb2df82efe662eefc7de3c9d90ed843f7bc7458da14bd1539797f301de51a53#eventlog) 
BaseWeb
- [] base.org
- [] …
=> feat: Register new basenames with base cointype fwd resolution data

apps/base-docs/docs/public/serve.json
The /tutorials/ page has been deprecated and this routes folks hitting that URL
N/A
Localhost
BaseWeb
BaseDocs
=> fix(redirect): Route tutorials to docs homepage

apps/web/app/CryptoProviders.tsx, apps/web/src/cdp/constants.ts
* Updated wagmi `createConfig` to use CDP RPC instead of the public mainnet.base.org
* Updated env var to be available client side
* locally
previously network requests were routed to the public mainnet.base.org RPC fallback
after the change, network requests are routed to the CDP RPC
previously the console had many errors (429s on mainnet due to rate limiting)
after the change, these errors are gone
BaseWeb
BaseDocs
=> fix: wagmi rpc

apps/base-docs/docs/pages/chain/base-contracts.mdx
We have updated contract addresses as a result of the OP Stack [Upgrade 14](https://docs.optimism.io/notices/upgrade-14) on Base Mainnet.
The [upgrade transaction](https://etherscan.io/tx/0xfd06079372fea0ef0c8907b71931fc6907cc88c39f0dc036d3ebf267686fb6da) can be used to confirm the state changes by looking at the [events](https://etherscan.io/tx/0xfd06079372fea0ef0c8907b71931fc6907cc88c39f0dc036d3ebf267686fb6da#eventlog) or [state](https://etherscan.io/tx/0xfd06079372fea0ef0c8907b71931fc6907cc88c39f0dc036d3ebf267686fb6da#statechange) sections.
BaseWeb
- [] base.org
- [] …
=> chore(CHAIN-1140): update out-dated contract addresses

apps/base-docs/docs/pages/wallet-app/mini-apps.mdx, apps/base-docs/sidebar.ts
This PR adds a new root-level section called "Wallet App" and a doc/guide in that section called "Mini Apps" that goes over best practices for building mini apps.
I tested both the dev server and build locally, and I also tested the changes on a demo Vercel build
BaseWeb
BaseDocs
=> docs: Adds Mini Apps doc in Wallet App section

apps/base-docs/docs/pages/identity/smart-wallet/guides/sub-accounts/index.mdx, apps/base-docs/docs/pages/identity/smart-wallet/guides/sub-accounts/using-sub-accounts.mdx
Little patch to fix the wrong linking
BaseDocs
=> Quick fix to a link in Sub Accounts guide

apps/base-docs/docs/pages/chain/security-council.mdx
docs(sc): Add link to blog announcement post
N/A
Localhost
BaseWeb
BaseDocs
=> docs(sc): Add link to blog announcement post

apps/web/app/(basenames)/api/basenames/metadata/[tokenId]/route.ts, apps/web/app/(basenames)/api/basenames/talentprotocol/[address]/route.ts, apps/web/app/(basenames)/api/name/[alreadyClaimedName]/route.ts, apps/web/app/api/decorators.ts
* updated api routes with dynamic route segments to pull `params` using [dynamic params](https://nextjs.org/docs/app/building-your-application/routing/dynamic-routes) instead of searchParams
* created decorator `withTimeoutWithParams` to handle routes that have dynamic route segments
* locally, vercel preview
BaseWeb
BaseDocs
=> fix: dynamic route params

apps/web/next.config.js
This creates a vanity URL to point to our virtual events page on Luma, by request of the Base Global Builders team
N/A
Localhost
BaseWeb
BaseDocs
=> chore(redirect): Set up vanity link pointing to Luma

apps/web/package.json, apps/web/src/utils/bugsnag.ts, apps/web/src/utils/logger.ts, yarn.lock
What:
* added Bugsnag error logging to `logger.ts`
Why:
* currently `logger`'s methods simply console.[log/warn/error]
* Bugsnag captures these errors, with full stack trace in the message
* Please see [internal test PR](https://github.cbhq.net/protocols/base-web/pull/586#issuecomment-7850882) for important note about triaging errors in Bugsnag
* Tested api routes and client-side pages/components in staging environment, all documented in [test PR](https://github.cbhq.net/protocols/base-web/pull/586) 
BaseWeb
BaseDocs
=> feat: implement bugsnag

apps/base-docs/sidebar.ts
Removing Profiles from Sidebar
BaseDocs
=> Remove profiles from sidebar

apps/base-docs/docs/public/serve.json, apps/base-docs/sidebar.ts
This PR fixes some duplicated links that were added to the sidebar under 'Chain' earlier today that got erroneously removed as part of a rebase to resolve a merge conflict
Localhost
BaseWeb
BaseDocs
=> docs(sidebar): Fix links

apps/base-docs/docs/pages/index.mdx
The MiniKit card on the docs homepage was still pointing at the old Replit. Updated the href so that it points to the overview page in the MiniKit section of docs
=> Update docs overview page to direct MiniKit card to MiniKit Overview

.github/ISSUE_TEMPLATE/feature_request.yml
-Context structure change from "ex. " to "e.g.,"
-Grammar in "additional context"
**What changed? Why?** 
"ex." to "e.g.,"
"E.g." means for example, you use "e.g.," to introduce examples of something.
while
"Ex." is short for "exercise.", "ex." is used to introduce exercises.
BaseWeb
- [] base.org
BaseDocs
=> context fix in feature_request.yml

apps/base-docs/docs/pages/identity/mobile-wallet-protocol/encryption.mdx
Updated the Tink repository link from `github.com/google/tink` to `github.com/tink-crypto/tink` since the project has moved. This ensures users land on the correct, actively maintained repo and avoids confusion from dead links.  
- No functional changes—just a documentation fix.  
- Confirmed the new link resolves correctly.  
Manually verified the link redirects properly.  
**Have you tested the following pages?**  
**BaseWeb**  
**BaseDocs**
=> docs: Fix Tink repository link

apps/base-docs/docs/pages/builderkits/minikit/quickstart.mdx
This PR addresses several typos and formatting issues in the MiniKit quickstart documentation:
- Fixed link formatting for CDP Portal
- Corrected spelling of `eliminating` (was `elimintaing`)
- Fixed spelling of `Primary` (was `Priamry`)
- Corrected spelling of `social` (was `socail`)
- Removed extra quotation mark in className attribute
- Fixed spelling of `Farcaster` (was `Farcster`)
These changes improve readability and maintain consistency throughout the documentation.
*
=> Fix typos and formatting issues in MiniKit quickstart documentation

apps/base-docs/docs/pages/cookbook/smart-contract-development/hardhat/reducing-contract-size.md
Replaced the outdated URL for the "modifiers" link in reducing-contract-size.md with the correct working path (https://docs.base.org/learn/advanced-functions/function-modifiers).
This ensures users are directed to the live and relevant documentation.
=> Fix broken link to Function Modifiers

apps/base-docs/docs/pages/identity/wallet-sdk/developer-settings.mdx
Fixed a grammar issue in the phrase "Developer settings provides...". Since "Developer settings" is plural, it should be "provide". This improves clarity and correctness in the UI text.
Just a small wording correction — no functional changes.
Checked the updated text in the UI to confirm it displays correctly.
BaseWeb  
BaseDocs
=> docs: Fix verb agreement in "Developer settings" description

apps/base-docs/docs/pages/learn/erc-721-token/openzeppelin-erc-721-vid.mdx
`Review__the`  -  `Review_the `
=> deleted double space openzeppelin-erc-721-vid.mdx

apps/base-docs/docs/pages/learn/erc-721-token/erc-721-standard.mdx
Returns the number of tokens owned by a specific address. Reverts if the address is the zero address.
https://eips.ethereum.org/EIPS/eip-721#balanceof
=> Retrieving Token Balance with balanceOf(address owner)

apps/base-docs/docs/pages/learn/hardhat-verify/hardhat-verify-sbs.mdx
=> fix link to display image hardhat-verify-sbs.mdx

apps/base-docs/docs/pages/chain/flashblocks/node-providers.mdx
Fix broken link
N/A
Localhost
BaseWeb
BaseDocs
=> docs(flashblocks): Fix broken link in node providers section

apps/base-docs/docs/pages/builderkits/minikit/quickstart.mdx
**Description:**  
This pull request corrects two typographical errors in the MiniKit Quickstart documentation:
- Replaces "applie" with "applies" in the MiniKitProvider section.
- Fixes "teamplate" to "template" in the review section.
These changes improve the clarity and professionalism of the documentation. No functional code changes were made.
=> Fix typos in MiniKit Quickstart documentation

apps/web/app/(basenames)/api/basenames/talentprotocol/[address]/route.ts, apps/web/src/components/Basenames/UsernameProfileSectionBadges/hooks/useTalentProtocol.ts
Talent protocol deprecated their old passport endpoint and suggested we update to using the new `v2/score` endpoint: https://docs.talentprotocol.com/docs/developers/talent-api/api-reference-v2/score
Updated the route and the return data struct to match the new endpoint's response. 
Local branch fetched the score correctly. 
On prod: 
On local: 
BaseWeb
- [] base.org
BaseDocs
=> Fix: use new talentprotocol endpoint to fetch builder score

apps/base-docs/docs/pages/learn/error-triage/error-triage.mdx
BaseWeb
- [] base.org
BaseDocs
=> fix: function name error

apps/base-docs/docs/pages/cookbook/cross-chain/bridge-tokens-with-layerzero.mdx
https://docs.layerzero.network/contracts/oapp - broken link
https://docs.layerzero.network/v2/developers/evm/oapp/overview - new link
=> chore: fix error links bridge-tokens-with-layerzero.mdx

apps/base-docs/docs/pages/chain/oracles.mdx, apps/base-docs/docs/public/llms-full.txt
This PR updates broken links to the Supra Oracles documentation. The original link https://supraoracles.com/docs/ currently results in a 404 error. It has been replaced with the correct and working link: https://docs.supra.com/.
=> Fix Broken Documentation Link for Supra Oracles

apps/web/src/components/Layout/Footer/Footer.tsx
there was a TODO with a reminder to add a discord link, 
since the link is already there, 
I suppose there's no need in the TODO reminder anymore
=> chore: removed no more relevant reminder

apps/web/app/api/registry/entries/route.ts, apps/web/app/api/registry/featured/route.ts, apps/web/package.json, apps/web/src/utils/datastores/rds/index.ts, apps/web/src/utils/proofs/discount_code_storage.ts, apps/web/src/utils/proofs/proofs_storage.ts, yarn.lock
What changed? Why?
* change all postgres usage to the new rds infra
* remove vercel's kysely package as it's no longer used
Notes to reviewers
How has it been tested?
extensively in dev env (some example testing [here](https://github.cbhq.net/protocols/base-web/pull/575)).
BaseWeb
- [] base.org
BaseDocs
=> chore: use new rds

apps/base-docs/docs/pages/wallet-app/mini-apps.mdx
Edited `/wallet-app/mini-apps.mdx` in `base-docs` to add callouts about using `composeCast`, the new mini app metadata, and best practices for interacting with wallets.
Note: I [had a duplicate PR open for this yesterday](https://github.com/base/web/pull/2405) but accidentally closed it this morning as I was rebasing some new changes.
=> docs: add latest metadata and wallet recommendations for mini apps

apps/web/src/components/Basenames/UsernameProfileSectionFrames/Frame.tsx, apps/web/src/components/Basenames/UsernameProfileSectionFrames/FrameListItem.tsx
Frames are failing to render. Broadly, frames are deprecated, specifically Frames v1. We want to move to mini-app support, but in the meantime should make sure that failing frames do not render on the profile page. 
Before:
With fix: 
BaseWeb
- [] base.org
BaseDocs
=> [BA-2007] Check for failing frames and filter based on failure state

apps/web/src/components/Basenames/UsernameProfileSectionFrames/Frame.tsx
* removed redundant null check from `Frame` — error state handled by the UI parent, `FrameListItem`
* there should be no change to behavior, this is a code simplification
BaseWeb
BaseDocs
=> chore: remove redundant null check

apps/web/src/middleware/ipSafe.ts
* added IP addresses to `ipSafe`'s blocklists
* cidr ranges handled by `ipaddr` range blocking
BaseWeb
BaseDocs
=> chore: update ipSafe blocklists

apps/web/app/(basenames)/name/[username]/renew/page.tsx, apps/web/src/components/Basenames/RegistrationBackground/index.tsx, apps/web/src/components/Basenames/RegistrationFlow.tsx, apps/web/src/components/Basenames/RegistrationForm/index.tsx, apps/web/src/components/Basenames/RenewalFlow.tsx, apps/web/src/components/Basenames/RenewalForm/RenewalButton.tsx, apps/web/src/components/Basenames/RenewalForm/index.tsx, apps/web/src/components/Basenames/YearSelector/index.tsx, apps/web/src/utils/formatEtherPrice.ts, apps/web/src/utils/formatUsdPrice.ts
- Added a new page for renewing Basenames
- This page is heavily inspired by the existing Basename registration flow. Some code has been abstracted and re-used
- In upcoming PRs, this page will be navigated to from various entry points, and the existing renewal modal will be removed
- Manually
https://github.com/user-attachments/assets/9cfe4ad7-b988-4976-a01a-ca36cc93884c
BaseWeb
BaseDocs
=> [BA-1973] Basenames renewals page

apps/web/src/components/Banner/index.tsx, apps/web/src/components/BannerWithCTA/index.tsx
- Added a re-useable banner component. This component will be used to remind users of their Basename expiring, and provide them with a CTA to renew. 
- Next PR will implement the logic for showing this banner
- Manually 
https://github.com/user-attachments/assets/d8870f08-a005-4a4e-adc2-a7c846ebf59c
(rendered it just for the demo)
BaseWeb
- [] base.org
=> [BA-1968] Add re-useable banner component

apps/web/app/(basenames)/api/basenames/getUsernames/route.ts
Previously, we used a hardcoded prod-specific endpoint for manage-names. We should use the env-provided cdp URI so that the manage-names page works on dev. 
Tested by setting local env to dev's config w/ cbhq endpoints/tokens/secrets. 
BaseWeb
- [] base.org
=> [bug] Use ENV config CDP uri for manage-names route 

apps/web/app/CryptoProviders.tsx, apps/web/src/hooks/useCapabilitiesSafe.ts, apps/web/src/hooks/useWriteContractsWithLogs.ts
Our paymaster and scw integrations are outdated (untouched since July last year). Since then, the tooling and patterns have formalized and we want to ensure we're using the most modern, safe patterns. 
BaseWeb
- [] base.org
=> Update paymaster and SCW integrations

apps/web/src/utils/redirectIfNameDoesNotExist.ts, apps/web/src/utils/usernames.ts
Added handling for names in grace period so that they don't get redirected to the "name-not-found" page. 
BaseWeb
- [] base.org
=> Feat: graceful grace period redirects

apps/web/src/components/Layout/Navigation/navigation.ts
fix footer link
CO-179
BaseWeb
- [] base.org
=> feat: CO-179 fix footer link to go to proper brand site

apps/web/src/hooks/useBasenameExpirationBanner.tsx
- The following error would appear on the server when loading the profile page:
- This PR fixes by checking if document is defined
BaseWeb
- [] base.org
=> fix: Fix document undefined error on profile page

apps/web/app/CryptoProviders.tsx, apps/web/app/global.css, apps/web/e2e/tests/connectWallet.spec.ts, apps/web/e2e/tests/registration-failed.spec.ts, apps/web/e2e/tests/registration-rejected.spec.ts, apps/web/e2e/tests/registration-success.spec.ts, apps/web/package.json, apps/web/src/components/Basenames/RegistrationForm/index.tsx, apps/web/src/components/ConnectWalletButton/ConnectWalletButton.tsx, yarn.lock
- This PR reverts the majority of the changes in the following PRs:
- #2003
- #2147 
- Users that registered a basename last year using wallets like Rainbow and WalletConnect are unable to renew their name because we switched to OnchainKit which does not support these wallets.
- To solve this, we need to switch back to RainbowKit to be able to support all wallets that users were using to register basenames
- Since all E2E tests depend on onchainkit, i've temporarily disabled them so that we can fix and re-enable in the future
BaseWeb
- [] base.org
- [] …
=> feat: Add back RainbowKit support

apps/web/src/components/Basenames/RenewalForm/RenewalButton.tsx
- The connect button on the renewal page was using OnchainKit, instead it needs to use RainbowKit
- The code for this is copied from the Registration flow https://github.com/base/web/blob/master/apps/web/src/components/Basenames/RegistrationForm/index.tsx#L263
https://github.com/user-attachments/assets/0367e31f-dcb0-4e3a-99ac-a8b7b77caee6
BaseWeb
- [] base.org
=> chore: Use rainbowkit for renewal page

apps/web/src/hooks/useSetPrimaryBasename.ts
- Updated the flow for setting a primary Basename to be compatible with ensip19 
- This PR only updates the transaction made for smart accounts. A separate PR will be made for EOAs.
- The transaction bundles two calls - one for calling the existing `setNameForAddr` on the ReverseRegistrar, and one for calling `setName` on the L2ReverseRegistrar
https://github.com/user-attachments/assets/04a42f2f-c124-4306-85eb-e345eee042cc
BaseWeb
- [] base.org
=> [ENSIP 19] Update set primary flow for SCWs

apps/web/src/components/Basenames/UsernameProfileTransferOwnershipModal/context.tsx, apps/web/src/components/Modal/index.tsx, apps/web/src/components/WalletIdentity/index.tsx, apps/web/src/hooks/useBasenameResolver.ts
This [tx](https://basescan.org/tx/0x39f4af11b007b7ea5e9a834900e6e8e1389fb5d877880f37a3380ff881683ee7) was submitted via the ownership transfer flow. Can see in the calldata that this is a multicall resolver set. Querying the resolver directly shows that the data was updated according to expectations: 
[Tenderly sim](https://www.tdly.co/tx/0x39f4af11b007b7ea5e9a834900e6e8e1389fb5d877880f37a3380ff881683ee7)
BaseWeb
- [] base.org
=> feat(BA-2817): Ensip-11 address setting during ownership transfer modal

apps/web/src/components/Basenames/UsernameProfileTransferOwnershipModal/context.tsx
When a user actions through the change ownership modal, the last step is to clear their primary name record. With legacy reverse resolution, this is needed since the data is read directly from state and is not close-loop checked against forward resolution data.
In #2622 I incorrectly added a regression that cleared the data in the ENS L2ReverseRegistrar. This _isn't_ necessary since all ENSIP-19 requests are proprely close-loop checked and the data that would be involved in said check is edited in step one of this flow. 
This PR fixes that regression by going back to clearing only the legacy data. We will be able to remove this entirely once we deprecate legacy reverse writes.  …
=> chore(BA-2884): Fix regression in clearing primary name

apps/web/src/components/Layout/Footer/Footer.tsx, apps/web/src/components/Layout/Navigation/Sidebar/Base-Sidebar.tsx
- Change base.org/build secondary button text from 'Grow your app' to 'See the docs'
- Update base.org/build secondary button link to docs.base.org/get-started/base
- Update base.org/build primary button link from docs to base.dev
- Update footer social links
locally
BaseWeb
- [] base.org
=> Update Base Build page CTAs and footer social links

apps/web/app/(basenames)/api/proxy/route.ts, apps/web/src/components/Basenames/UsernameProfileSectionHeatmap/index.tsx
This PR updates the route that feeds our onchain score component at base.org/name/YOUR_BASENAME.
Before:
After:
BaseWeb
- [] base.org
=> Fix "onchain score" component by updating to Etherscan API V2
